### ISSUE TITLE
Both controllers restart when only zookeepers are forcefully restarted.

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#3954] opened 2019-06-25 07:33 UTC
**When zookeepers are restarted forcefully, this makes both the controllers to restart: **
Deleted 2 zookeepers forcefully:
`kubectl delete pods pravega-zk-2 pravega-zk-0 --grace-period=0 --force`
This made both the controllers also to restart:
```
root@osboxes:/usr/local/go/bin/src/github.com/pravega-longevity# kubectl get po
NAME                                                 READY     STATUS    RESTARTS   AGE
pravega-bookie-0                                     1/1       Running   0          33m
pravega-bookie-1                                     1/1       Running   0          33m
pravega-bookie-2                                     1/1       Running   0          33m
pravega-bookie-3                                     1/1       Running   0          33m
pravega-operator-554d769d4c-jjhlr                    1/1       Running   0          34m
pravega-pravega-controller-5cf97b5ccd-qk4bc          0/1       Running   0          33m
pravega-pravega-controller-5cf97b5ccd-x85dx          0/1       Running   0          33m
pravega-pravega-segmentstore-0                       1/1       Running   0          33m
pravega-pravega-segmentstore-1                       1/1       Running   0          32m
pravega-pravega-segmentstore-2                       1/1       Running   0          32m
pravega-zk-0                                         0/1       Running   1          1m
pravega-zk-1                                         1/1       Running   0          37m
pravega-zk-2                                         0/1       Running   1          1m
pravega-zk-3                                         1/1       Running   0          36m
pravega-zk-4                                         1/1       Running   0          35m
shaka-zulu-nfs-client-provisioner-5bcd87b9dc-hhrkr   1/1       Running   0          41m
zookeeper-operator-7b96d9d548-j9ctv                  1/1       Running   0          39m
```
Pravega details:
```
Pravega version : 0.5.0-2269.6f8a820
Zookeeper Operator : pravega/zookeeper-operator:latest
zk image: pbelgundi/zookeeper:21.0
Pravega Operator: pravega/pravega-operator:0.3.2
```
Attaching K8 logs for the same.
[pravega-k8s-logging-2019-06-24-12-06-11.zip](https://github.com/pravega/pravega/files/3324047/pravega-k8s-logging-2019-06-24-12-06-11.zip)

**Comment by fpj** [comment] 2019-07-01 14:17
I'm wondering why this issue is marked as `P0`. What is `P0`-like about it?

**Comment by RaulGracia** [comment] 2019-07-01 16:46
It looks lie this issue (and other similar ones) are pointing to an infrastructure problem (not a Pravega problem). The reasoning behind this is statement is that I'm able to reproduce this problem consistently in all the PKS cluster I have tried. On the other hand, in GKE (Google Cloud), the restart works much faster and, in general, there are no Controller restarts when Zookeeper pods are deleted:

1)
```
kubectl delete pods zookeeper-0 zookeeper-2 --grace-period=0 --force
```
2)
```
NAME                                        READY   STATUS    RESTARTS   AGE
coiling-shark-nfs-server-provisioner-0      1/1     Running   0          5h54m
pravega-bookie-0                            1/1     Running   1          6m22s
pravega-bookie-1                            1/1     Running   0          6m22s
pravega-bookie-2                            1/1     Running   0          6m22s
pravega-operator-687bbf897b-82z69           1/1     Running   0          155m
pravega-pravega-controller-f4dfc887-9gzb4   1/1     Running   0          6m22s
pravega-pravega-segmentstore-0              1/1     Running   0          6m22s
zookeeper-0                                 1/1     Running   0          72s
zookeeper-1                                 1/1     Running   0          8m57s
zookeeper-2                                 1/1     Running   0          23s
zookeeper-3                                 1/1     Running   0          7m49s
zookeeper-4                                 1/1     Running   0          7m5s
zookeeper-operator-5fb6d7cf4d-tlpsr         1/1     Running   0          5h
```

This is seems to be related to the DNS resolution of `zookeeper-client` name in the `zookeeperReady` script of our Zookeeper image. Probably due to some infrastructure issue, the script gets stuck on that point, and takes +10 seconds to progress, so the readiness probe fails. After 3 failures, we see a restart of the pod, and then also restarts of Controllers. The reason that motivates us to believe that is a DNS problem is that in PKS, once Zookeeper comes back to stability (e.g., 6 mins to 15 mins), subsequent deletions of pods are recovered fast without additional Controller restarts. This may indicate that the IP for that `zookeeper-client` has been cached, so the resolution is faster.

Still, the fact that it works in GKE indicates that there is little we can do at the Pravega level, other than try with larger liveness prove intervals (e.g., 20 secs) to explore whether it is enough time for a successful name resolution the first time a Zookeeper pod is delete.

If there is no strong point against, I'm inclined to concentrate all the info about the issue, which is currently scattered and duplicated across multiple issues, into a single one. All the existing related issues will be superseded by that one. Is that ok @sumit-bm?

**Comment by sumit-bm** [comment] 2019-07-01 17:00
@RaulGracia Sure you may collate all the issues and maintain one.
A few questions, 
1. What was the recovery timing in GKE environment? 
2. Would any IO workload run for longer tenure affect the timing as well? 
3. What would be our intended customer base usage? If most of them use GKE then might be this issue is of less severity as per your observations, but if most customers use PKS we need to have a solution on PKS as well.

**Comment by RaulGracia** [comment] 2019-07-01 17:01
Thanks @sumit-bm. We need to improve the situation in PKS, which will perhaps require involvement from infrastructure team.

**Comment by RaulGracia** [comment] 2019-07-01 18:27
Superseded by https://github.com/pravega/zookeeper-operator/issues/72.

**Closed by RaulGracia** 2019-07-01 18:27 UTC
Labels: kind/bug, priority/P0, version/0.5.0
