### ISSUE TITLE
Fencing fails with `org.apache.hadoop.ipc.RemoteException: No sources given`

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2165] opened 2017-12-07 04:11 UTC
**Problem description**
```
2017-12-06 20:11:22,026 2895503 [segment-store-39] DEBUG o.a.h.i.r.RetryInvocationHandler - Exception while invoking call #110187 ClientNamenodeProtocolTranslatorPB.concat over null. Not retrying because try once and fail.
org.apache.hadoop.ipc.RemoteException: No sources given
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:88)
        at org.apache.hadoop.hdfs.server.namenode.FSDirConcatOp.concat(FSDirConcatOp.java:53)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.concat(FSNamesystem.java:1884)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.concat(NameNodeRpcServer.java:889)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.concat(ClientNamenodeProtocolServerSideTranslatorPB.java:564)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2049)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2045)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2043)

        at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1481)
        at org.apache.hadoop.ipc.Client.call(Client.java:1427)
        at org.apache.hadoop.ipc.Client.call(Client.java:1337)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:227)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
        at com.sun.proxy.$Proxy13.concat(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.concat(ClientNamenodeProtocolTranslatorPB.java:547)
        at sun.reflect.GeneratedMethodAccessor115.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:398)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:163)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:155)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:335)
        at com.sun.proxy.$Proxy14.concat(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.concat(DFSClient.java:1574)
        at org.apache.hadoop.hdfs.DistributedFileSystem.concat(DistributedFileSystem.java:676)
        at io.pravega.segmentstore.storage.impl.hdfs.FileSystemOperation.combine(FileSystemOperation.java:196)
        at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.cleanup(OpenWriteOperation.java:140)
        at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.fenceOut(OpenWriteOperation.java:123)
        at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.call(OpenWriteOperation.java:68)
        at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.call(OpenWriteOperation.java:24)
        at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.call(HDFSStorage.java:240)
        at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.openWrite(HDFSStorage.java:154)
        at io.pravega.segmentstore.storage.rolling.RollingStorage.openHandle(RollingStorage.java:593)
        at io.pravega.segmentstore.storage.rolling.RollingStorage.openWrite(RollingStorage.java:289)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$openWrite$0(AsyncStorageWrapper.java:71)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$supplyAsync$11(AsyncStorageWrapper.java:141)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Problem location**

**Suggestions for an improvement**

**Comment by andreipaduroiu** [comment] 2018-01-04 01:22
I couldn't reproduce this and I haven't seen it in the logs since. If it doesn't occur again by Jan 31st, 2018. I will close this.

**Closed** 2018-05-14 20:13 UTC
Labels: area/server, area/testing, area/tier2, status/in-progress
