### ISSUE TITLE
IO Failure observed on docker swarm setup while scaling segment store using "docker service scale pravega_segmentstore=N"

### ISSUE THREAD

**Issue by vedanthh** [pravega/pravega#3041] opened 2018-10-30 11:22 UTC
**IO Failure observed on docker swarm setup while scaling segment store using "docker service scale pravega_segmentstore=N"**

In a Docker Swarm environment, started moderate IO with Pravega Benchmark tool and tried scale up segment store from 1 to 3 using docker service scale pravega_segmentstore=3. IO failures had been observed (console snip below)

**Docker swarm setup**
```
4 Nodes - 1 Master, 3 Workers. Deployment:
1 Controller
1 Zookeeper
1 Segment Store
3 BookKeeper
1 Pravega_HDFS
```
**Steps Followed**
```
1. Created Docker swarm setup
2. Started IO using pravega-benchmark tool
3. Scaled up segment store to 3 using "docker service scale pravega_segmentstore=3"
```
**Snip of console**
```
pravega-benchmark]# time ./pravega-benchmark/bin/pravega-benchmark  --controller tcp://<PUBLISHED_IP>:9090 --stream StreamName-r11  -producers 1 --size 200  -eventspersec 3000 --runtime 600 --randomkey true  --writeonly true
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.240.124.151:9090
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=7206184435398083750] Tagging client request (createScope-Scope).
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[addrs=[/10.240.124.151:9090], attrs={}]]
[grpc-default-executor-0] WARN io.pravega.client.stream.impl.ControllerImpl - [requestId=7206184435398083750] Scope already exists: Scope
[main] INFO io.pravega.client.admin.impl.StreamManagerImpl - Creating scope/stream: Scope/StreamName-r11 with configuration: StreamConfiguration(scope=Scope, streamName=StreamName-r11, scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=1), retentionPolicy=null)
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=4777385341592413374] Tagging client request (createStream-Scope-StreamName-r11).
[grpc-default-executor-0] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=4777385341592413374] Stream created successfully: StreamName-r11
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.240.124.151:9090
[main] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Shutting down ControllerNameResolver
[main] INFO io.pravega.client.netty.impl.ConnectionFactoryImpl - Shutting down connection factory
[main] INFO io.pravega.client.stream.impl.ClientFactoryImpl - Creating writer for stream: StreamName-r11 with configuration: EventWriterConfig(initalBackoffMillis=1, maxBackoffMillis=20000, retryAttempts=10, backoffMultiple=10, transactionTimeoutTime=29999)
[main] INFO io.pravega.client.stream.impl.SegmentSelector - Refreshing segments for stream StreamImpl(scope=Scope, streamName=StreamName-r11)
[clientInternal-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[addrs=[/10.240.124.151:9090], attrs={}]]
[clientInternal-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Fetching endpoint for segment Scope/StreamName-r11/0.#epoch.0, writerID: 3f623e60-e6e5-4a74-9c08-2e20e9378226
[clientInternal-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=172.16.11.20, port=12345) for Scope/StreamName-r11/0.#epoch.0, writerID: 3f623e60-e6e5-4a74-9c08-2e20e9378226
[epollEventLoopGroup-5-1] INFO io.pravega.client.netty.impl.ClientConnectionInboundHandler - Connection established ChannelHandlerContext(ClientConnectionInboundHandler#0, [id: 0x7e4a8572])
[epollEventLoopGroup-5-1] INFO io.pravega.shared.protocol.netty.FailingReplyProcessor - Received hello: WireCommands.Hello(type=HELLO, highVersion=5, lowVersion=5)
[epollEventLoopGroup-5-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Received AppendSetup WireCommands.AppendSetup(type=APPEND_SETUP, requestId=1, segment=Scope/StreamName-r11/0.#epoch.0, writerId=3f623e60-e6e5-4a74-9c08-2e20e9378226, lastEventNumber=-9223372036854775808)
[epollEventLoopGroup-5-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection setup complete for writer 3f623e60-e6e5-4a74-9c08-2e20e9378226
200 records Writing, 6896.6 records/sec (1.31541 MB/sec), 21.1 ms avg latency, 27.0 max latency.
 WINDOW: 200, 200, 6896.6 ,1.31541 MB/sec, 21.1, 27.0
200 records Writing, 6896.6 records/sec (1.31541 MB/sec), 21.5 ms avg latency, 27.0 max latency.
 WINDOW: 200, 200, 6896.6 ,1.31541 MB/sec, 21.5, 27.0
200 records Writing, 9523.8 records/sec (1.81652 MB/sec), 19.8 ms avg latency, 30.0 max latency.
 WINDOW: 200, 200, 9523.8 ,1.81652 MB/sec, 19.8, 30.0
200 records Writing, 1666.7 records/sec (0.31789 MB/sec), 30.6 ms avg latency, 112.0 max latency.
 WINDOW: 200, 200, 1666.7 ,0.31789 MB/sec, 30.6, 112.0
[epollEventLoopGroup-5-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Failing connection for writer 3f623e60-e6e5-4a74-9c08-2e20e9378226 with exception io.pravega.shared.protocol.netty.ConnectionFailedException
[epollEventLoopGroup-5-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Handling exception io.pravega.shared.protocol.netty.ConnectionFailedException for connection io.pravega.client.netty.impl.ClientConnectionInboundHandler@25289917 on writer 3f623e60-e6e5-4a74-9c08-2e20e9378226. SetupCompleted: true, Closed: false
[epollEventLoopGroup-5-1] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection for segment Scope/StreamName-r11/0.#epoch.0 on writer 3f623e60-e6e5-4a74-9c08-2e20e9378226 failed due to: class io.pravega.shared.protocol.netty.ConnectionFailedException
[pool-1-thread-1] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection 3f623e60-e6e5-4a74-9c08-2e20e9378226 failed due to:
io.pravega.shared.protocol.netty.ConnectionFailedException: java.nio.channels.ClosedChannelException
        at io.pravega.common.concurrent.Futures.getAndHandleExceptions(Futures.java:180)
        at io.pravega.client.netty.impl.ClientConnectionInboundHandler.send(ClientConnectionInboundHandler.java:120)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl.write(SegmentOutputStreamImpl.java:443)
        at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEventInternal(EventStreamWriterImpl.java:120)
        at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEvent(EventStreamWriterImpl.java:104)
        at com.emc.pravega.perf.PravegaPerfTest$WriterWorker.lambda$sendFunction$0(PravegaPerfTest.java:298)
        at com.emc.pravega.perf.PravegaPerfTest$WriterWorker.lambda$runLoop$1(PravegaPerfTest.java:327)
        at com.emc.pravega.perf.PerfStats.runAndRecordTime(PerfStats.java:150)
        at com.emc.pravega.perf.PravegaPerfTest$WriterWorker.runLoop(PravegaPerfTest.java:320)
        at com.emc.pravega.perf.PravegaPerfTest$WriterWorker.run(PravegaPerfTest.java:367)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.ClosedChannelException
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
[clientInternal-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Fetching endpoint for segment Scope/StreamName-r11/0.#epoch.0, writerID: 3f623e60-e6e5-4a74-9c08-2e20e9378226
[clientInternal-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=172.16.11.20, port=12345) for Scope/StreamName-r11/0.#epoch.0, writerID: 3f623e60-e6e5-4a74-9c08-2e20e9378226
[epollEventLoopGroup-5-2] INFO io.pravega.client.netty.impl.ClientConnectionInboundHandler - Connection established ChannelHandlerContext(ClientConnectionInboundHandler#0, [id: 0xd4a6ed9d])
[epollEventLoopGroup-5-2] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Failing connection for writer 3f623e60-e6e5-4a74-9c08-2e20e9378226 with exception io.pravega.shared.protocol.netty.ConnectionFailedException
[epollEventLoopGroup-5-2] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Handling exception io.pravega.shared.protocol.netty.ConnectionFailedException for connection io.pravega.client.netty.impl.ClientConnectionInboundHandler@e15103c on writer 3f623e60-e6e5-4a74-9c08-2e20e9378226. SetupCompleted: false, Closed: false
[epollEventLoopGroup-5-2] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection for segment Scope/StreamName-r11/0.#epoch.0 on writer 3f623e60-e6e5-4a74-9c08-2e20e9378226 failed due to: class io.pravega.shared.protocol.netty.ConnectionFailedException
[epollEventLoopGroup-5-2] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - 3f623e60-e6e5-4a74-9c08-2e20e9378226 Failed to connect:
java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
```
[logs.zip](https://github.com/pravega/pravega/files/2529357/logs.zip)

**Comment by fpj** [comment] 2018-12-10 13:46
The snippet shows a connection failure stack trace, which could have happened because of the segment container rebalancing. For how long does the problem persist? If it is temporary, then it is expected. It is only a real issue in the case the client is never able to recover.

**Comment by vedanthh** [comment] 2018-12-11 07:33
It is not a temporary IO buffering instead its an IO Failure observed, hence i reported this issue.

**Comment by shrids** [comment] 2018-12-11 09:42
**Summary:**
The client does retry to connect to the stream after the newer SegmentStores are up but receives a `NoSuchSegmentException`. The reason for this exception is not know from the existing logs.


From the available logs was able to reconstruct the following :

1. SegmentStore observes that BookKeeperLog is not primary anymore @ `2018-10-30 08:52:14,461 59412` [1]
2. SegmentContainer 3 was stopped on the segmentstore. [2]
3. The writer (`3f623e60-e6e5-4a74-9c08-2e20e9378226`) is not able to setup connection as it receives wrong host since the segment container is down.
4. The segment containers recover at `2018-10-30 08:52:46,189 91140` around 36 seconds post the error observed. [4]
5. The last `SetupAppend` request sent by the client was at `2018-10-30 08:52:14,791 59742` . There are no further requests were sent from the client to this particular Segmentstore.
6. Observing that post a retry the writer receives `NoSuchSegmentException`
7. The controller too received a `NoSuchSegmentException` [7]

Couple of questions:
- Was StreamRetention policy configured for this `StreamName-r11` ? 
- What was the exception observed by the console/client application?
- The logs.zip has the logs of a single segment store instead of 3 !
- The client/console logs does not have timestamps.!

```
[1]
2018-10-30 08:52:14,461 59412 [BookKeeperClientWorker-orderedsafeexecutor-1-0] ERROR i.p.s.s.h.handler.AppendProcessor - Error (Segment = 'Scope/StreamName-r11/0.#epoch.0', Operation = 'append')
io.pravega.segmentstore.storage.DataLogWriterNotPrimaryException: BookKeeperLog is not primary anymore.
	at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.handleWriteException(BookKeeperLog.java:623)
	at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.addCallback(BookKeeperLog.java:571)
	at org.apache.bookkeeper.client.PendingAddOp.submitCallback(PendingAddOp.java:311)
	at org.apache.bookkeeper.client.LedgerHandle.errorOutPendingAdds(LedgerHandle.java:1242)
	at org.apache.bookkeeper.client.LedgerHandle$3.safeRun(LedgerHandle.java:424)
	at org.apache.bookkeeper.util.SafeRunnable.run(SafeRunnable.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.bookkeeper.client.BKException$BKLedgerFencedException: null
	at org.apache.bookkeeper.client.BKException.create(BKException.java:83)
	at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.handleWriteException(BookKeeperLog.java:619)
	... 12 common frames omitted
	
	
[2] 
2018-10-30 08:52:14,475 59426 [core-20] WARN  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[3]: DurableLog failed. Shutting down StreamSegmentContainer.

[3]
2018-10-30 08:52:14,791 59742 [epollEventLoopGroup-3-4] WARN  i.p.s.s.h.handler.AppendProcessor - Wrong host. Segment 'Scope/StreamName-r11/0.#epoch.0' (Container 3) is not owned and 3f623e60-e6e5-4a74-9c08-2e20e9378226 cannot perform operation 'setting up append'.

[4]
2018-10-30 08:52:16,088 61039 [core-26] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 1, 2, 3], Current = [0, 1, 2], PendingTasks = [], ToStart = [3], ToStop = [].
2018-10-30 08:52:26,116 71067 [core-13] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 1, 2, 3], Current = [0, 1], PendingTasks = [], ToStart = [2, 3], ToStop = [].
2018-10-30 08:52:36,167 81118 [core-9] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 1, 2, 3], Current = [1, 2, 3], PendingTasks = [], ToStart = [0], ToStop = [].
2018-10-30 08:52:46,189 91140 [core-25] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 1, 2, 3], Current = [0, 1, 2, 3], PendingTasks = [], ToStart = [], ToStop = [].

[5]
2018-10-30 08:52:14,791 59742 [epollEventLoopGroup-3-4] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: 3f623e60-e6e5-4a74-9c08-2e20e9378226 on segment: Scope/StreamName-r11/0.#epoch.0

[6] (the timestamp is missing)
[epollEventLoopGroup-5-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Ending reconnect attempts on writer 3f623e60-e6e5-4a74-9c08-2e20e9378226 to Scope/StreamName-r11/0.#epoch.0 because segment is truncated

[7]
2018-10-30 08:52:35,070 228119 [Delegate] WARN  i.p.c.e.impl.EventProcessorCell - Restarting event processor: EventProcessor[abortStreamReaders:0] due to exception: {}
io.pravega.client.segment.impl.NoSuchSegmentException: Segment does not exist:No such segment: _system/_RGabortStreamReaders/0.#epoch.0
```

**Comment by shrids** [comment] 2019-02-19 16:37
Closing this as we have not been able to reproduce this in the last 2 months.
@vedanthh please re-open the bug if you observe the same issue.

**Closed** 2019-02-19 16:37 UTC
Labels: area/client, area/testing, kind/bug
