### ISSUE TITLE
Observing "java.lang.OutOfMemoryError: GC overhead limit exceeded" in docker swarm setup while running IO using pravega benchmark

### ISSUE THREAD

**Issue by vedanthh** [pravega/pravega#3801] opened 2019-05-20 11:56 UTC
**Observing "java.lang.OutOfMemoryError: GC overhead limit exceeded" in docker swarm setup while running IO using pravega benchmark**

In a Docker Swarm environment, started moderate IO with Pravega Benchmark tool and tried scale up/scale down segment between range 10 and 2000 and segmentstore docker exited with error "java.lang.OutOfMemoryError: GC overhead limit exceeded"

**Docker swarm setup**
```
Deployment:
Pravega version : 0.5.0-2236.5228e2d
1 Controller
1 Zookeeper
1 Segment Store
4 BookKeeper
1 Pravega_HDFS
```
**Steps Followed**
```
1. Created Docker swarm setup
2. Started IO using pravega-benchmark tool and performed segment scaling and descaling between range 10 to 2000 with 10 readers and 10 writers - IO size 100 bytes and events/sec 100
```

**Snip of error and segmentstore log:** 
[ss_docker_Sw.txt](https://github.com/pravega/pravega/files/3197758/ss_docker_Sw.txt)

```
2019-05-19 21:06:14,847 890069 [core-13] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 1, 2, 3], Current = [0, 1, 2, 3], PendingTasks = [], ToStart = [], ToStop = [].
java.lang.OutOfMemoryError: GC overhead limit exceeded
Dumping heap to java_pid1.hprof ...
Heap dump file created [922820685 bytes in 11.788 secs]
Aborting due to java.lang.OutOfMemoryError: GC overhead limit exceeded
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (debug.cpp:308), pid=1, tid=0x00007f34d9ec9ae0
#  fatal error: OutOfMemory encountered: GC overhead limit exceeded
#
# JRE version: OpenJDK Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
# Java VM: OpenJDK 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.9.0
# Distribution: Custom build (Tue Oct 23 11:27:22 UTC 2018)
# Core dump written. Default location: /opt/pravega/core or core.1
#
# An error report file with more information is saved as:
# /opt/pravega/hs_err_pid1.log
#
# -XX:OnError="kill -9 p%"
#   Executing /bin/sh -c "kill -9 p%" ...
```

**Comment by andreipaduroiu** [comment] 2019-05-21 15:07
The only think I notice here is that there are 36K log lines for "Setting up appends for writer" and 3.5K instances of "Bad attribute update". There are lots of writers for lots of segments.

Unfortunately without a core dump, OOM errors cannot be debugged too easily. Please re-run this with core dump on and share the core dump so we can take a look at what's going on.

**Comment by RaulGracia** [comment] 2019-05-21 15:13
Apart from the comments from @andreipaduroiu, it would be necessary to know which are the resources committed to the container running the segment store.

**Comment by sumit-bm** [comment] 2019-05-27 21:19
@andreipaduroiu @RaulGracia we have reproduced it with recent build `0.5.0-2260.b477eec` below are the manifest used, logs are posted in internal channel due size limitation here.
```
  segmentstore:
    image: devops-repo.isus.emc.com:8116/nautilus/pravega:0.5.0-2260.b477eec
    command: segmentstore
    ports:
      - "12345:12345"
    environment:
      WAIT_FOR: bookkeeper:3181,${HDFS_URL:-hdfs:8020}
      HDFS_URL: hdfs://${HDFS_URL:-hdfs:8020}
      TIER2_STORAGE: HDFS
      HDFS_REPLICATION: 1
      ZK_URL: ${ZK_URL:-zookeeper:2181}
      CONTROLLER_URL: tcp://controller:9090
      JAVA_OPTS: |
        -Dmetrics.enableCSVReporter=false
        -Dpravegaservice.publishedIPAddress=${PUBLISHED_ADDRESS}
        -Dpravegaservice.listeningIPAddress=${LISTENING_ADDRESS}
        -Dbookkeeper.bkEnsembleSize=2
        -Dbookkeeper.bkAckQuorumSize=2
        -Dbookkeeper.bkWriteQuorumSize=2
        -Xmx900m
        -XX:OnError="kill -9 p%"
        -XX:+ExitOnOutOfMemoryError
        -XX:+CrashOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/opt/pravega
```

**Comment by RaulGracia** [comment] 2019-05-27 21:36
@sumit-bm @vedanthh In the `yml` above there is no information on the resources provided to the docker containers of the Swarm, which is important. Moreover, you are assuming that a single Segment Store instance in that experiment is able to handle `2000` segments with a "maximum" JVM heap space of 900MB (`-Xmx900m`). This sounds as a provisioning problem and in this situation the Segment Store is expected to run out of memory. In the [guidelines we have for provisioning](https://github.com/pravega/pravega-tools/blob/bc1c8ccc9b0151e52e8578e00909f903c8314bf2/pravega-provisioner/model/constants.py#L29), we recommend to provision 6GB of memory to a Segment Store instance. Please, reproduce the experiment following the provisioning guidelines and check if in that case you still see the OOM error.

**Comment by sumit-bm** [comment] 2019-05-27 21:40
@RaulGracia There was IO failure observed with segmentstore scale up, please see #3800 and that's the reason we couldn't expose more segment store. Could you once take a look on that and let us know if IO failure could be mitigated with segmentstore scale up, in that case we could run with higher number of segement stores in the docker swarm setup

**Closed** 2019-05-29 10:05 UTC
Labels: kind/bug, priority/P0, version/0.5.0
