### ISSUE TITLE
Sporadic unit test failure: StoreClientFactoryTest.testZkSessionExpiryRetry

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#3699] opened 2019-04-25 16:56 UTC
**Problem description**
```
io.pravega.controller.store.client.StoreClientFactoryTest > testZkSessionExpiryRetry FAILED
    java.lang.RuntimeException: Exception of the wrong type. Was expecting class org.apache.zookeeper.KeeperException$SessionExpiredException but got: org.apache.zookeeper.KeeperException$NoNodeException
        at io.pravega.test.common.AssertExtensions.assertThrows(AssertExtensions.java:75)
        at io.pravega.controller.store.client.StoreClientFactoryTest.testZkSessionExpiryRetry(StoreClientFactoryTest.java:84)
        Caused by:
        org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /test/test
            at org.apache.zookeeper.KeeperException.create(KeeperException.java:115)
            at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
            at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:2019)
            at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:327)
            at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:316)
            at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64)
            at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)
            at org.apache.curator.framework.imps.GetDataBuilderImpl.pathInForeground(GetDataBuilderImpl.java:313)
            at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:304)
            at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:35)
            at io.pravega.controller.store.client.StoreClientFactoryTest.lambda$testZkSessionExpiryRetry$4(StoreClientFactoryTest.java:84)
            at io.pravega.test.common.AssertExtensions.assertThrows(AssertExtensions.java:64)
            ... 1 more
```

**Problem location**
Controller.

**Suggestions for an improvement**
Fix unit test or underlying code.

**Comment by tkaitchuck** [comment] 2019-04-25 17:37
Or alternately: 
```
io.pravega.controller.store.client.StoreClientFactoryTest > testZkSessionExpiryRetry FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
        at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
        at io.pravega.controller.store.client.StoreClientFactoryTest.testZkSessionExpiryRetry(StoreClientFactoryTest.java:81)
```

**Comment by shiveshr** [comment] 2019-07-23 10:15
This is duplicate of issue #3271. 

PS: We closed #3271 yesterday for lack of reproduction in recent times.

**Comment by fpj** [comment] 2019-07-23 10:20
I have been seeing this frequently on travis.

**Comment by tkaitchuck** [comment] 2020-06-03 23:42
Updated stack trace.

```
io.pravega.controller.store.client.StoreClientFactoryTest > testZkSessionExpiryRetry FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
        at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1947)
        at io.pravega.controller.store.client.StoreClientFactoryTest.testZkSessionExpiryRetry(StoreClientFactoryTest.java:81)
```

**Comment by derekm** [comment] 2021-01-10 04:33
Observed assertion failure:

```
io.pravega.controller.store.client.StoreClientFactoryTest > testZkSessionExpiryRetry FAILED
    java.lang.AssertionError: expected:<3> but was:<4>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.pravega.controller.store.client.StoreClientFactoryTest.testZkSessionExpiryRetry(StoreClientFactoryTest.java:90)
```

**Comment by pbelgundi** [comment] 2021-01-27 14:09
Looks like there have been some changes in the way Curator handles ZK Session Expiration, post version 3.0 of Apache curator. See:
https://curator.apache.org/errors.html
https://stackoverflow.com/questions/41862575/how-does-apache-curator-try-to-reconnect-when-session-expires

**Comment by RaulGracia** [comment] 2021-02-11 07:53
Found another instance of this failure:
```
io.pravega.controller.store.client.StoreClientFactoryTest > testZkSessionExpiryRetry FAILED
    java.lang.AssertionError: expected:<3> but was:<4>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.pravega.controller.store.client.StoreClientFactoryTest.testZkSessionExpiryRetry(StoreClientFactoryTest.java:90)
```

**Comment by pbelgundi** [comment] 2021-02-12 07:21
Re-opening this issue, as I could reproduce the "test timeout exception" after running this single test in a loop for > 3 hours...
The probability of the failure occurring is pretty low about 1/180, but it still does occur and the root cause really seems to be a problem with curator not doing session expiry soon enough:
Here is the stack trace:
```
> Task :controller:test

Running test: io.pravega.controller.store.client.StoreClientFactoryTest > testZkSessionExpiryRetry

Output of io.pravega.controller.store.client.StoreClientFactoryTest.testZkSessionExpiryRetry (Last 300 lines):
 > 2021-02-11 22:26:18,985 504  [Test worker] INFO  io.pravega.test.common.TestUtils - Available free port is 58692
 > 2021-02-11 22:26:19,326 845  [Thread-4] INFO  o.a.c.test.TestingZooKeeperMain - Starting server
 > 2021-02-11 22:26:19,886 1405 [Time-limited test] INFO  o.a.c.f.imps.CuratorFrameworkImpl - Starting
 > 2021-02-11 22:26:19,897 1416 [Time-limited test] DEBUG o.a.curator.CuratorZookeeperClient - Starting
 > 2021-02-11 22:26:19,899 1418 [Time-limited test] DEBUG org.apache.curator.ConnectionState - Starting
 > 2021-02-11 22:26:19,901 1420 [Time-limited test] DEBUG org.apache.curator.ConnectionState - reset
 > 2021-02-11 22:26:20,001 1520 [Time-limited test] INFO  o.a.c.f.imps.CuratorFrameworkImpl - Default schema
 > 2021-02-11 22:26:20,013 1532 [Time-limited test-EventThread] WARN  org.apache.curator.ConnectionState - Session expired event received
 > 2021-02-11 22:26:20,014 1533 [Time-limited test-EventThread] DEBUG org.apache.curator.ConnectionState - reset
 > 2021-02-11 22:26:20,113 1632 [NIOWorkerThread-1] WARN  o.a.zookeeper.server.NIOServerCnxn - Unable to read additional data from client sessionid 0x100013511ad0000, likely client has closed socket
 > 2021-02-11 22:26:20,122 1641 [Time-limited test-EventThread] INFO  o.a.c.f.s.ConnectionStateManager - State change: LOST
 > 2021-02-11 22:26:35,299 16818 [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background operation retry gave up
 > org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
 >      at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
 >      at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:844)
 >      at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:972)
 >      at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:925)
 >      at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:73)
 >      at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:322)
 >      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 >      at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
 >      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 >      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 >      at java.base/java.lang.Thread.run(Thread.java:834)
 > 2021-02-11 22:26:35,312 16831 [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background retry gave up
 > org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
 >      at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:954)
 >      at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:925)
 >      at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:73)
 >      at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:322)
 >      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 >      at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
 >      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 >      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 >      at java.base/java.lang.Thread.run(Thread.java:834)
 > 2021-02-11 22:26:35,335 16854 [Time-limited test] DEBUG org.apache.curator.RetryLoop - Retry-able exception received
 > org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /test
 >      at org.apache.zookeeper.KeeperException.create(KeeperException.java:134)
 >      at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
 >      at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:2021)
 >      at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:2049)
 >      at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:274)
 >      at org.apache.curator.framework.imps.NamespaceImpl$1.call(NamespaceImpl.java:90)
 >      at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64)
 >      at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)
 >      at org.apache.curator.framework.imps.NamespaceImpl.fixForNamespace(NamespaceImpl.java:83)
 >      at org.apache.curator.framework.imps.CuratorFrameworkImpl.fixForNamespace(CuratorFrameworkImpl.java:713)
 >      at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:295)
 >      at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:35)
 >      at io.pravega.controller.store.client.StoreClientFactoryTest.lambda$testZkSessionExpiryRetry$2(StoreClientFactoryTest.java:71)
 >      at io.pravega.test.common.AssertExtensions.lambda$assertEventuallyThrows$1(AssertExtensions.java:104)
 >      at io.pravega.test.common.TestUtils.awaitException(TestUtils.java:92)
 >      at io.pravega.test.common.AssertExtensions.assertEventuallyThrows(AssertExtensions.java:102)
 >      at io.pravega.controller.store.client.StoreClientFactoryTest.testZkSessionExpiryRetry(StoreClientFactoryTest.java:71)
 >      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 >      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 >      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 >      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 >      at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
 >      at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 >      at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
 >      at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 >      at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
 >      at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
 >      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 >      at java.base/java.lang.Thread.run(Thread.java:834)
 > 2021-02-11 22:26:35,342 16861 [Time-limited test] DEBUG org.apache.curator.RetryLoop - Retry policy not allowing retry
 > 2021-02-11 22:26:35,342 16861 [Time-limited test] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Ensure path threw exception
 > org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /test
 >      at org.apache.zookeeper.KeeperException.create(KeeperException.java:134)
 >      at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
 >      at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:2021)
 >      at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:2049)
 >      at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:274)
 >      at org.apache.curator.framework.imps.NamespaceImpl$1.call(NamespaceImpl.java:90)
 >      at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64)
 >      at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)
 >      at org.apache.curator.framework.imps.NamespaceImpl.fixForNamespace(NamespaceImpl.java:83)
 >      at org.apache.curator.framework.imps.CuratorFrameworkImpl.fixForNamespace(CuratorFrameworkImpl.java:713)
 >      at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:295)
 >      at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:35)
 >      at io.pravega.controller.store.client.StoreClientFactoryTest.lambda$testZkSessionExpiryRetry$2(StoreClientFactoryTest.java:71)
 >      at io.pravega.test.common.AssertExtensions.lambda$assertEventuallyThrows$1(AssertExtensions.java:104)
 >      at io.pravega.test.common.TestUtils.awaitException(TestUtils.java:92)
 >      at io.pravega.test.common.AssertExtensions.assertEventuallyThrows(AssertExtensions.java:102)
 >      at io.pravega.controller.store.client.StoreClientFactoryTest.testZkSessionExpiryRetry(StoreClientFactoryTest.java:71)
 >      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 >      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 >      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 >      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 >      at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
 >      at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 >      at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
 >      at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 >      at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
 >      at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
 >      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 >      at java.base/java.lang.Thread.run(Thread.java:834)
 > 2021-02-11 22:34:22,299 483818 [Time-limited test] DEBUG org.apache.curator.RetryLoop - Retry-able exception received
 > org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /test/test
 >      at org.apache.zookeeper.KeeperException.create(KeeperException.java:134)
 >      at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
 >      at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:2131)
 >      at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:327)
 >      at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:316)
 >      at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64)
 >      at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)
 >      at org.apache.curator.framework.imps.GetDataBuilderImpl.pathInForeground(GetDataBuilderImpl.java:313)
 >      at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:304)
 >      at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:35)
 >      at io.pravega.controller.store.client.StoreClientFactoryTest.lambda$testZkSessionExpiryRetry$2(StoreClientFactoryTest.java:71)
 >      at io.pravega.test.common.AssertExtensions.lambda$assertEventuallyThrows$1(AssertExtensions.java:104)
 >      at io.pravega.test.common.TestUtils.awaitException(TestUtils.java:92)
 >      at io.pravega.test.common.AssertExtensions.assertEventuallyThrows(AssertExtensions.java:102)
 >      at io.pravega.controller.store.client.StoreClientFactoryTest.testZkSessionExpiryRetry(StoreClientFactoryTest.java:71)
 >      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 >      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 >      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 >      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 >      at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
 >      at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 >      at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
 >      at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 >      at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
 >      at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
 >      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 >      at java.base/java.lang.Thread.run(Thread.java:834)
 > 2021-02-11 22:34:22,457 483976 [Time-limited test] DEBUG org.apache.curator.RetryLoop - Retry policy not allowing retry

io.pravega.controller.store.client.StoreClientFactoryTest > testZkSessionExpiryRetry FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
```

**Closed** 2021-02-22 04:10 UTC
Labels: area/controller, tag/flakeyTest
