### ISSUE TITLE
While segmentstore container respawned in docker swarm environment(after OutOfMemoryError), IO restart ends up with ‘NullPointerException’ or ‘Authentication failed’

### ISSUE THREAD

**Issue by sumit-bm** [pravega/pravega#2998] opened 2018-10-21 07:30 UTC
In a 3 node docker swarm environment (1 controller, 1 segmentstore, 3 Bookkeeper, 1 Zk), started benchmark IO tool with moderate progressive IO workload (multiple writers producing 100 KBps to 10 MBps IO workload with 1000 to 10000 events per sec). 

sample IO: 
`./pravega-benchmark/bin/pravega-benchmark  --controller tcp://controller-ip:9090 --stream StreamName-r1  -producers 5 --size 100  -eventspersec 10000 --runtime 60 --randomkey true  --writeonly true`

`8166 records Writing,    8166.0 records/sec,     2.336 MB/sec,  0.1225 ms avg latency.`

Segmentstore defult configuration had been used for deployment, (Ref: pravega/docker/compose/swarm/pravega.yml) snip below:

segmentstore:
--
  | image: pravega/pravega
  | command: segmentstore
  | ports:
  | - "12345:12345"
  | environment:
  | WAIT_FOR: bookkeeper:3181,${HDFS_URL:-hdfs:8020}
  | HDFS_URL: hdfs://${HDFS_URL:-hdfs:8020}
  | ZK_URL: ${ZK_URL:-zookeeper:2181}
  | CONTROLLER_URL: tcp://controller:9090
  | JAVA_OPTS: \|
  | -Dmetrics.enableCSVReporter=false
  | -Dpravegaservice.publishedIPAddress=${PUBLISHED_ADDRESS}
  | -Dpravegaservice.listeningIPAddress=${LISTENING_ADDRESS}
  | -Xmx900m
  | -XX:OnError="kill -9 p%"
  | -XX:+ExitOnOutOfMemoryError
  | -XX:+CrashOnOutOfMemoryError
  | -XX:+HeapDumpOnOutOfMemoryError

While monitoring memory usage for segmentstore, it is been observed that segmentstore ends up with outofmemory and respawned from failure. IO failure have been observed.

`406251 root      20   0   30.4g  1.7g  22628 D  36.8  5.7  95:10.17 java`
`406251 root      20   0       0      0      0 Z  26.8  0.0  95:10.98 java`

Where ‘406251’ is segmentstore process in swarm node

`[root@qe2-slave-2 ~]# docker ps -a
CONTAINER ID        IMAGE                                                                                        COMMAND                  CREATED             STATUS                      PORTS                                 NAMES
8a77a5a466e0        pravega/pravega@sha256:e944e214d4bedfd3c835444b087968278c0cf0ca2fff67126a371f4b1212e778      "/opt/pravega/scri..."   21 hours ago        Up 21 hours                 9090-9091/tcp, 10000/tcp, 12345/tcp   pravega_segmentstore.1.mjifid85pest86mb4z29lk1xm
404a44cedda6        pravega/pravega@sha256:e944e214d4bedfd3c835444b087968278c0cf0ca2fff67126a371f4b1212e778      "/opt/pravega/scri..."   22 hours ago        Exited (139) 21 hours ago                                         pravega_segmentstore.1.5gd3x8fa28wu27zcf6ipn0trk`

Where container id “404a44cedda6” exited with out of memory and new segmentsotre container re-spawned “8a77a5a466e0”

Now if the IO had been restarted after segmentstore re-spawned, IO is not progressing and showing following issues ‘NullPointerException’ or ‘Authentication failed’, snip below:

`[ScalingRetransmition-Scope/StreamName-r1-1] ERROR io.pravega.client.stream.impl.EventStreamWriterImpl - Encountered excemption when handeling a sealed segment:
java.lang.NullPointerException
        at io.pravega.client.stream.impl.StreamSegments.getSegmentForKey(StreamSegments.java:67)
        at io.pravega.client.stream.impl.StreamSegments.getSegmentForKey(StreamSegments.java:61)
        at io.pravega.client.stream.impl.SegmentSelector.getSegmentForEvent(SegmentSelector.java:80)
        at io.pravega.client.stream.impl.SegmentSelector.getSegmentOutputStreamForKey(SegmentSelector.java:69)
        at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEventInternal(EventStreamWriterImpl.java:114)
        at io.pravega.client.stream.impl.EventStreamWriterImpl.writeEvent(EventStreamWriterImpl.java:104)
        at com.emc.pravega.perf.PravegaPerfTest$WriterWorker.lambda$sendFunction$0(PravegaPerfTest.java:497)
        at com.emc.pravega.perf.PravegaPerfTest$WriterWorker.lambda$runLoop$1(PravegaPerfTest.java:527)
        at com.emc.pravega.perf.PerfStats.writeAndRecordTime(PerfStats.java:147)
        at com.emc.pravega.perf.PravegaPerfTest$WriterWorker.runLoop(PravegaPerfTest.java:526)
        at com.emc.pravega.perf.PravegaPerfTest$WriterWorker.run(PravegaPerfTest.java:564)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
`
Or:

`[grpc-default-executor-27] WARN io.pravega.client.stream.impl.ControllerImpl - gRPC call for getEndpointForSegment with trace id 0 failed with                                               server error.
io.grpc.StatusRuntimeException: UNAUTHENTICATED: Authentication failed
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:418)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:663)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:443)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:525)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:446)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:557)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by arvindkandhare** [comment] 2018-10-23 21:13
@sumit-bm thanks for reporting this. Can you share the logs of the new container (i.e. `8a77a5a466e0`)? I think `docker logs 8a77a5a466e0` should get these.

**Comment by sumit-bm** [comment] 2018-10-25 10:59
@arvindkandhare , I recreated fresh setup and collected controller logs, exited_SS and respawned_SS logs. Please take a look.
[logs_issue_2998.zip](https://github.com/pravega/pravega/files/2514514/logs_issue_2998.zip)

**Comment by arvindkandhare** [comment] 2018-10-26 00:28
Thanks for the logs. From the logs here are some observations:
```
2018-10-25 09:34:54,082 1325 [storage-io-16] WARN  i.p.s.s.writer.SegmentAggregator - StorageWriter[2-10]: Segment 'Scope/StreamName-r1/0.#epoch.0' does not exist in Storage. Ignoring all further operations on it.
```
The root cause is not authentication failure but segment not being available in tier-2. This may be most prob because of this issue #2960 . In the deployment I do not see the tier-2 set explicitly. This means that it is mot prob taking the default which is most probably `INMEMORY`. This explains the non-existence of segments in tier-2 after the restart. 
I recommend setting the tier-2 config by hand and trying again.

**Comment by sumit-bm** [comment] 2018-10-28 18:38
Thanks for the response.
Raul and I was experimenting and would like to mention couple of points.

1. Tier 2 is in HDFS container and the consumption for the workload is similar between one DCOS based deployment and Docker swarm based deployment. On a same IO workload (100 MBps) on DCOS Tier 2 consumption was ~ 10 GB (started from 3.3 GB and ended in 14 GB) where Docker swarm based deployment consumption is similar (free space reduced from 89.7 GB and ended 79.8 GB). 

2. We have seen 3 Bookie also consuming memory for keeping tag on IO process

3. There was good amount of memory consumption on segment store on Docker swarm based deployment compared to DCOS (1 min IO of 100 MBps, Docker swarm SS memory consumption was 8.6 GB where same workload DCOS based SS memory consumption was 1.4 GB)

When Segmentstore had been respawned there were two issues seen ‘NullPointerException’ or ‘Authentication failed’, the controller log (attached in this issue) showed ‘NullPointerException’ and it seems respawned SS is not receiving any IO, does controller is not sending it or recovery of SS is not happened properly, even if Bookie and tier 2 worked fine?

**Comment by RaulGracia** [comment] 2018-11-06 18:10
Similarly to #3051, I think that we can close this issue as we confirmed that the problems are related to a bad configuration of Tier2 (HDFS), as @arvindkandhare suggested.

**Closed** 2018-11-06 18:11 UTC
Labels: area/server, kind/bug, priority/P0, status/needs-attention
