### ISSUE TITLE
Java Heap OutOfMemoryError if metrics can't be published to InfluxDB

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#4071] opened 2019-08-01 20:22 UTC
**Problem description**
In one of the longevity runs, we have discovered that metrics could not be published to InfluxDB. After a few hours, the Segment Store process crashed with Java Heap OutOfMemoryError. The heap dump indicated there were 29 million objects in the heap, the majority of which were from metrics/micrometer; all summed up to more than 3GB of usage. There was no Segment Store data whatsoever in this heap dump, so that was not a contributing factor.

**Problem location**
Metrics.

**Suggestions for an improvement**
Set a maximum retention policy for unpublished metrics. Keep them under an upper bound of memory/counts and discard older values. 

The inability to publish metrics due to infrastructure problems should not cause adverse side effects on the host that's generating them.

**Comment by kevinhan88** [comment] 2019-08-09 23:35
@andreipaduroiu - when metrics "could not be published to influxDB", what is the config? Is metrics.enableInfluxDBReporter=true but no influxdb running?

**Comment by kevinhan88** [comment] 2019-08-09 23:39
![image](https://user-images.githubusercontent.com/24516773/62814207-4675ea80-bac4-11e9-9336-08355730acbc.png)

**Comment by andreipaduroiu** [comment] 2019-08-10 14:48
@Tristan1900 Can you clarify @kevinhan88 's question? I believe you were the one running and monitoring the test. Thx!

**Comment by kevinhan88** [comment] 2019-08-19 07:50
Deployed latest pravega (38b1b001f8) and running longevity small against it for over 6 hours now. The memory usage of all 3 segments and the controller seems fine. The heapdump of all 3 segmentstores also look fine. (See attached screenshots)

**Comment by kevinhan88** [comment] 2019-08-19 07:51
<img width="697" alt="LongevitySmall-MemoryUsed-segmentstore-0" src="https://user-images.githubusercontent.com/24516773/63248078-6f605300-c21b-11e9-94f5-646b16cbd7d2.PNG">
<img width="698" alt="LongevitySmall-MemoryUsed-controller-0" src="https://user-images.githubusercontent.com/24516773/63248079-6f605300-c21b-11e9-96d0-f0664c0dfc25.PNG">
<img width="696" alt="LongevitySmall-MemoryUsed-segmentstore-2" src="https://user-images.githubusercontent.com/24516773/63248080-6f605300-c21b-11e9-9e3e-bf8d83ef113c.PNG">
<img width="698" alt="LongevitySmall-MemoryUsed-segmentstore-1" src="https://user-images.githubusercontent.com/24516773/63248081-6f605300-c21b-11e9-82b0-55ec56f20d15.PNG">

**Comment by kevinhan88** [comment] 2019-08-19 07:51
<img width="693" alt="Heapdump-Segmentstore-2" src="https://user-images.githubusercontent.com/24516773/63248134-88690400-c21b-11e9-9c33-285c1aa7f9a1.PNG">
<img width="694" alt="Heapdump-Segmentstore-1" src="https://user-images.githubusercontent.com/24516773/63248135-88690400-c21b-11e9-9596-655d136c2994.PNG">
<img width="696" alt="Heapdump-Segmentstore-0" src="https://user-images.githubusercontent.com/24516773/63248138-88690400-c21b-11e9-9a53-f13429237513.PNG">

**Comment by kevinhan88** [comment] 2019-08-19 07:55
It seems the metrics may hold up memory for certain time (currently the default cache timeout is 30 minutes, which is unnecessarily long), however the mechanism will eventually bring the memory usage back. But if the max mem is reached before the "cooling down", OOM might happen.

I'll make the following two changes first to mitigate the situation:
1. bump micrometer version to 2.0 from 1.1.3
2. reduce metrics cache default timeout from 30 min to 3 min

**Comment by kevinhan88** [comment] 2019-08-20 16:35
Tested again with 1 segmentstore and mid-scale longevity - firstly bookies run out of space and kept rebooting, and finally SS got restarted too.

**Comment by kevinhan88** [comment] 2019-08-20 16:36
<img width="681" alt="Cluster-bookie-segmentstore-restarted" src="https://user-images.githubusercontent.com/24516773/63366146-f30a6480-c32d-11e9-94b3-1cd338f0de19.PNG">
<img width="610" alt="cluster-screenshot-longevity-midscale-4hours-noinfluxdb" src="https://user-images.githubusercontent.com/24516773/63366147-f30a6480-c32d-11e9-81c0-be697f28d1fe.PNG">
<img width="629" alt="bookie-logs-longevity-midscale-4hr" src="https://user-images.githubusercontent.com/24516773/63366148-f3a2fb00-c32d-11e9-871a-699efe2e3125.PNG">

**Comment by kevinhan88** [comment] 2019-08-21 15:41
Also it is now a common practice for the QE team to turn on metrics in their longevity test. They have done many longevity tests for many days, so far there's no report of similar issue.
So my conclusion is: in general there is no memory leaking caused by metrics. It is of course possible to observe OOM if pravega was not configured with sufficient resources.

https://github.com/pravega/pravega/pull/4117 reduced the cache eviction timeout from 30 min down to 3 min. This will further reduce the memory usage of metrics.

**Comment by kevinhan88** [comment] 2019-08-29 18:59
Close this issue as it's confirmed there is no memory leaking caused by Influxdb no-responding.
https://github.com/pravega/pravega/issues/4148 is created instead to enhance StreamSegmentContainer - it should release timers when closes.

**Closed by kevinhan88** 2019-08-29 18:59 UTC
Labels: kind/bug, priority/P1, version/0.6.0
