### ISSUE TITLE
Getting this error `ERROR o.a.bookkeeper.client.LedgerHandle` in segment-store

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#3685] opened 2019-04-24 11:41 UTC
Getting this error `ERROR o.a.bookkeeper.client.LedgerHandle` in segment-store-0

IO was running with small load(IO workload (Total - 3readers, 3 writers, 120 events/sec, ~ 100 KB/sec IO))

Deployment Details:-
```
bookkeeper:0.5.0-2222.8ba5431
pravega:0.5.0-2222.8ba5431
zookeeper:3.5.4-beta-operator
pravega-operator:0.3.2
zookeeper-operator:0.2.1
```
Environment details: PKS / K8 with medium cluster:
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```

Snippet of error log:
```
2019-04-23 17:43:45,999 364529256 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR o.a.bookkeeper.client.LedgerHandle - [EnsembleChange-L7145-1] : could not persist ledger metadata : info = Ensemble Info : failed bookies = {0=pravega-bookie-2.pravega-bookie-headless.default.svc.cluster.local:3181}, replaced bookies = [0], new ensemble = [pravega-bookie-1.pravega-bookie-headless.default.svc.cluster.local:3181, pravega-bookie-3.pravega-bookie-headless.default.svc.cluster.local:3181, pravega-bookie-0.pravega-bookie-headless.default.svc.cluster.local:3181], closing ledger : -9.
2019-04-23 17:43:45,999 364529256 [main-EventThread] WARN  o.a.b.meta.AbstractZkLedgerManager - Conditional update ledger metadata failed: CONNECTIONLOSS
2019-04-23 17:43:45,999 364529256 [main-EventThread] WARN  o.a.b.meta.AbstractZkLedgerManager - Conditional update ledger metadata failed: CONNECTIONLOSS
2019-04-23 17:43:45,999 364529256 [main-EventThread] WARN  o.a.b.meta.AbstractZkLedgerManager - Conditional update ledger metadata failed: CONNECTIONLOSS
2019-04-23 17:43:45,999 364529256 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR o.a.bookkeeper.client.LedgerHandle - Closing ledger 7145 due to ZKException: Error while using ZooKeeper
2019-04-23 17:43:45,999 364529256 [main-EventThread] WARN  o.a.b.meta.AbstractZkLedgerManager - Conditional update ledger metadata failed: CONNECTIONLOSS
2019-04-23 17:43:45,999 364529256 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR o.a.bookkeeper.client.LedgerHandle - [EnsembleChange-L110753-1] : could not persist ledger metadata : info = Ensemble Info : failed bookies = {2=pravega-bookie-2.pravega-bookie-headless.default.svc.cluster.local:3181}, replaced bookies = [2], new ensemble = [pravega-bookie-3.pravega-bookie-headless.default.svc.cluster.local:3181, pravega-bookie-1.pravega-bookie-headless.default.svc.cluster.local:3181, pravega-bookie-0.pravega-bookie-headless.default.svc.cluster.local:3181], closing ledger : -9.
2019-04-23 17:43:45,999 364529256 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR o.a.bookkeeper.client.LedgerHandle - Closing ledger 110753 due to ZKException: Error while using ZooKeeper
2019-04-23 17:43:45,999 364529256 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR o.a.bookkeeper.client.LedgerHandle - [EnsembleChange-L7145-2] : could not persist ledger metadata : info = Ensemble Info : failed bookies = {2=pravega-bookie-0.pravega-bookie-headless.default.svc.cluster.local:3181}, replaced bookies = [2], new ensemble = [pravega-bookie-1.pravega-bookie-headless.default.svc.cluster.local:3181, pravega-bookie-3.pravega-bookie-headless.default.svc.cluster.local:3181, pravega-bookie-2.pravega-bookie-headless.default.svc.cluster.local:3181], closing ledger : -9.
2019-04-23 17:43:45,999 364529256 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR o.a.bookkeeper.client.LedgerHandle - Closing ledger 7145 due to ZKException: Error while using ZooKeeper
2019-04-23 17:43:45,999 364529256 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR o.a.bookkeeper.client.LedgerHandle - [EnsembleChange-L7145-3] : could not persist ledger metadata : info = Ensemble Info : failed bookies = {1=pravega-bookie-3.pravega-bookie-headless.default.svc.cluster.local:3181}, replaced bookies = [1], new ensemble = [pravega-bookie-1.pravega-bookie-headless.default.svc.cluster.local:3181, pravega-bookie-0.pravega-bookie-headless.default.svc.cluster.local:3181, pravega-bookie-2.pravega-bookie-headless.default.svc.cluster.local:3181], closing ledger : -9.
2019-04-23 17:43:45,999 364529256 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR o.a.bookkeeper.client.LedgerHandle - Closing ledger 7145 due to ZKException: Error while using ZooKeeper
2019-04-23 17:43:45,999 364529256 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR o.a.bookkeeper.client.LedgerHandle - [EnsembleChange-L110753-2] : could not persist ledger metadata : info = Ensemble Info : failed bookies = {0=pravega-bookie-3.pravega-bookie-headless.default.svc.cluster.local:3181}, replaced bookies = [0], new ensemble = [pravega-bookie-2.pravega-bookie-headless.default.svc.cluster.local:3181, pravega-bookie-1.pravega-bookie-headless.default.svc.cluster.local:3181, pravega-bookie-0.pravega-bookie-headless.default.svc.cluster.local:3181], closing ledger : -9.
2019-04-23 17:43:45,999 364529256 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR o.a.bookkeeper.client.LedgerHandle - Closing ledger 110753 due to ZKException: Error while using ZooKeeper
2019-04-23 17:43:45,999 364529256 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR o.a.bookkeeper.client.LedgerHandle - [EnsembleChange-L110753-3] : could not persist ledger metadata : info = Ensemble Info : failed bookies = {1=pravega-bookie-1.pravega-bookie-headless.default.svc.cluster.local:3181}, replaced bookies = [1], new ensemble = [pravega-bookie-2.pravega-bookie-headless.default.svc.cluster.local:3181, pravega-bookie-3.pravega-bookie-headless.default.svc.cluster.local:3181, pravega-bookie-0.pravega-bookie-headless.default.svc.cluster.local:3181], closing ledger : -9.
2019-04-23 17:43:45,999 364529256 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR o.a.bookkeeper.client.LedgerHandle - Closing ledger 110753 due to ZKException: Error while using ZooKeeper
2019-04-23 17:43:45,999 364529256 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR o.a.bookkeeper.client.PendingAddOp - Write of ledger entry to quorum failed: L7145 E127077
2019-04-23 17:43:45,999 364529256 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR i.p.s.s.h.handler.AppendProcessor - Error (Segment = 'longevity/smallScaleYoung/4879.#epoch.3161', Operation = 'append')
io.pravega.segmentstore.storage.DurableDataLogException: General exception while accessing BookKeeper.
	at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.handleWriteException(BookKeeperLog.java:638)
	at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.addCallback(BookKeeperLog.java:570)
	at org.apache.bookkeeper.client.AsyncCallback$AddCallback.addCompleteWithLatency(AsyncCallback.java:91)
	at org.apache.bookkeeper.client.PendingAddOp.submitCallback(PendingAddOp.java:361)
	at org.apache.bookkeeper.client.LedgerHandle.errorOutPendingAdds(LedgerHandle.java:1546)
	at org.apache.bookkeeper.client.LedgerHandle$5.safeRun(LedgerHandle.java:523)
	at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.bookkeeper.client.BKException$ZKException: Error while using ZooKeeper
	at org.apache.bookkeeper.client.BKException.create(BKException.java:74)
	at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.handleWriteException(BookKeeperLog.java:618)
	... 10 common frames omitted
```

**Comment by sumit-bm** [comment] 2019-04-24 16:53
From the logs we are seeing the issue with ZK, could be a duplicate of the ZK issue and controller restart persisting. 
@RaulGracia We are assigning this to you as you are looking into ZK issue

**Comment by RaulGracia** [comment] 2019-07-02 14:16
We expect this kind of Zookeeper issues to be significantly reduced with https://github.com/pravega/zookeeper-operator/pull/69 (you need to use the latest Zookeeper image in the Pravega dockerhub repository to test it). In the presence of pod deletions, the recovery time of Zookeeper (and therefore, the exceptions in dependent components) may take longer in PKS until this issue is solved: https://github.com/pravega/zookeeper-operator/issues/72. However, if you can reproduce this issue and you detect that it is not transient, please re-open the issue or create a new one with the specific scenario in which this occurs.

**Closed by RaulGracia** 2019-07-02 14:16 UTC
Labels: kind/bug, version/0.5.0
