### ISSUE TITLE
Transaction commit is issued but stuck waiting without committing after 10 hours of longevity run

### ISSUE THREAD

**Issue by deenav** [pravega/pravega#3958] opened 2019-06-25 12:32 UTC
**Started a new Txn-scale test which consists of `1 Reader and 1 Writer with "transactionSize" as 10` and scaling policy enabled based on "BYTES_PER_SECOND" with `targetRate": 3, "scaleFactor": 2, &   "minNumSegments": 1` Observing Transactions/IO stall after ~10hrs of longevity operation.** 

From the longevity manager pod log, I am seeing the transaction events stalls at `2019-06-24 23:22:12`. Events are not increasing after that.
```
INFO  [2019-06-24 23:22:12,451] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 10h 20m
INFO  [2019-06-24 23:22:12,451] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:564,691, events/sec:15, KB/sec:11.637695
INFO  [2019-06-24 23:22:12,451] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 37648, perSec:0.5104032258064516, committed:18987, failed:0, aborted:18661, aborted but read: 0
INFO  [2019-06-24 23:22:12,451] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 120,576, average block time (ms): 166
INFO  [2019-06-24 23:22:12,451] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:564,691, events/sec:15, KB/sec:11.637695
INFO  [2019-06-24 23:22:12,451] io.pravega.longevity.utils.PerformanceUtils: New runtime for 3164d694-218b-45b5-a649-3e653713545b  Running for 10h 20m
INFO  [2019-06-24 23:22:12,451] io.pravega.longevity.utils.PerformanceUtils: Dumping stats for stream longevity/smallScaleTxBytes
INFO  [2019-06-24 23:22:12,451] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:564,691, events/sec:15, KB/sec:11.637695
INFO  [2019-06-24 23:22:12,451] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 37648, perSec:0.5104032258064516, committed:18987, failed:0, aborted:18661, aborted but read: 0
INFO  [2019-06-24 23:22:12,451] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 120,576, average block time (ms): 166
INFO  [2019-06-24 23:22:12,451] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:564,691, events/sec:15, KB/sec:11.637695
172.24.182.2 - - [24/Jun/2019:23:22:12 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 1213 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 2
```  

There is no POD restart had been observed:
```
NAMESPACE           NAME                                                 READY   STATUS      RESTARTS   AGE
default             pravega-bookie-0                                     1/1     Running     0          22h
default             pravega-bookie-1                                     1/1     Running     0          22h
default             pravega-bookie-2                                     1/1     Running     0          22h
default             pravega-bookie-3                                     1/1     Running     0          22h
default             pravega-operator-77554dc594-8b2tz                    1/1     Running     0          23h
default             pravega-pravega-controller-8566874d59-2t5mv          1/1     Running     0          22h
default             pravega-pravega-controller-8566874d59-snl2b          1/1     Running     0          22h
default             pravega-pravega-segmentstore-0                       1/1     Running     0          22h
default             pravega-pravega-segmentstore-1                       1/1     Running     0          22h
default             pravega-pravega-segmentstore-2                       1/1     Running     0          22h
default             pravega-zk-0                                         1/1     Running     0          23h
default             pravega-zk-1                                         1/1     Running     0          23h
default             pravega-zk-2                                         1/1     Running     0          23h
default             shaka-zulu-nfs-client-provisioner-5bcd87b9dc-zg64q   1/1     Running     0          23h
default             zookeeper-operator-747c796d9-7xgnf                   1/1     Running     0          24h
```

Environment details: PKS / K8 with medium cluster:
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
```
Pravega version: 0.5.0-2284.8c6176
Zookeeper Operator : pravega/zookeeper-operator:0.2.2
Pravega Operator: pravega/pravega-operator:0.4.0
```

**Comment by deenav** [comment] 2019-06-25 12:47
Attaching  `pravega-pravega-segmentstore-1`  and `pravega-pravega-controller-8566874d59-2t5mv` pod logs here. [issue-3958.zip](https://github.com/pravega/pravega/files/3325299/issue-3958.zip)


And will be sharing the complete cluster logs in the internal channel due to size limits.

**Comment by shiveshr** [comment] 2019-06-27 12:33
The cause of transaction not getting committed is that when the processing for the event posted corresponding to this transaction was performed, for yet to be ascertained reason, the transaction was not found to be in `committing` state. Hence it was not committed. And since no subsequent transaction commit requests were sent in the system there was no new event which could be used to commit the transaction. 
However, when we create and send commit for newer transactions, this and newer transactions are committed and in correct order. So I am reducing the severity for the issue and will keep investigating to find the root cause.

**Comment by shiveshr** [comment] 2019-06-27 12:34
This is a duplicate of #3755 where we had observed exactly same behaviour. 
Linking the two issues together.

**Comment by deenav** [comment] 2019-07-01 13:06
This issue is reproducible again after `~4 days` of longevity run. Looks like it is happening more frequently with Pravea build #0.5.0-2284.8c6176 and it would be good to have the fix soon.

**Comment by sumit-bm** [comment] 2019-07-01 18:10
@shiveshr @fpj As we are seeing more frequent repro, would it be possible to get this in 0.5.0 release?

**Closed** 2019-07-03 07:21 UTC
Labels: area/controller, area/transaction, kind/bug, priority/P1, status/accepted, version/0.6.0
