### ISSUE TITLE
Sporadic build failure: HDFSIntegrationTest> testEndToEndWithFencing

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#4317] opened 2019-10-24 07:46 UTC
**Problem description**
This test failed on travis:
```
io.pravega.segmentstore.server.host.HDFSIntegrationTest > testEndToEndWithFencing FAILED
java.util.concurrent.CompletionException: java.util.concurrent.CancellationException: OperationProcessor is shutting down.
Caused by:java.util.concurrent.CancellationException: OperationProcessor is shutting down.
```
**Problem location**
HDFSIntegrationTest

**Suggestions for an improvement**
The test should pass consistently

**Comment by andreipaduroiu** [comment] 2019-10-24 14:28
Duplicate of #2933.

**Closed by andreipaduroiu** 2019-10-24 14:28 UTC
Labels: area/tier2, kind/bug, priority/P1, version/0.6.0, version/0.7.0
