### ISSUE TITLE
User scope "streamsInScope" present out of the box

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#3442] opened 2019-03-08 15:58 UTC
**Problem description**
A fresh instance of Pravega cluster has a non-system scope `streamsInScope` present  out of the box.

**Problem location**
ZKScope.java

**Suggestions for an improvement**
Please, make it a system scope (start the name with underscore).

**Comment by fpj** [comment] 2019-03-14 07:28
This is a parent znode that has been introduced to help with the pagination of streams when listing them. It is a bug that we are interpreting it as a scope, it is not a scope.

**Comment by shiveshr** [comment] 2019-07-01 18:27
We have moved the default store to Pravega Tables. So this issue is no longer directly observable. 
The issue is present if someone chooses zk over pravega tables as the store for controller metadata. 
Moving this issue to 0.6 and will address there.

**Closed** 2019-07-01 20:08 UTC
Labels: area/controller, kind/bug, priority/P2, status/needs-attention, version/0.6.0
