### ISSUE TITLE
Pravega Segment Store and Bookkeeper got restarted on running 100 streams with 10 segments and 100 KB record size

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega#4156] opened 2019-09-05 15:52 UTC
**Problem description**

On running 100 streams with 5 workers ( writers and readers ), **100 KB record size**, 5 events/sec over 10 segments for 10 mins run time, observed **1 segment store** out of 3 and **1 bookkeeper** out of 4 getting **restarted**.

The stream run was divided into 4 parts ( 25 streams in each pod ) between 4 pks pods all together, each pod having resource limit of `12 GB`.

Segment Store log shows `BadAttributeUpdateException` :
```
2019-09-05 13:38:20,011 111639160 [core-25] WARN  i.p.s.s.h.handler.AppendProcessor - Bad attribute update by 0be678de-8bc0-4422-88f0-83ca9c0e594f on segment Scope/pps5d75/1.#epoch.0.
io.pravega.segmentstore.contracts.BadAttributeUpdateException: [Segment 'Scope/pps5d75/1.#epoch.0'] Bad Attribute Update (AttributeId = 0be678de-8bc0-4422-88f0-83ca9c0e594f, Value = 26, UpdateType = ReplaceIfEquals): 
Expected existing value to be '25', actual '29'..
        at io.pravega.segmentstore.server.logs.SegmentMetadataUpdateTransaction.preProcessAttributes(SegmentMetadataUpdateTransaction.java:469)
        at io.pravega.segmentstore.server.logs.SegmentMetadataUpdateTransaction.preProcessOperation(SegmentMetadataUpdateTransaction.java:276)
        at io.pravega.segmentstore.server.logs.ContainerMetadataUpdateTransaction.preProcessOperation(ContainerMetadataUpdateTransaction.java:313)
        at io.pravega.segmentstore.server.logs.OperationMetadataUpdater.preProcessOperation(OperationMetadataUpdater.java:224)
        at io.pravega.segmentstore.server.logs.OperationProcessor.processOperation(OperationProcessor.java:365)
        at io.pravega.segmentstore.server.logs.OperationProcessor.processOperations(OperationProcessor.java:289)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Bookkeeper log shows `TooLongFrameException` :
```
2019-09-05 13:39:22,843 - ERROR - [bookie-io-1-1:BookieRequestHandler@70] - Unhandled exception occurred in I/O thread or handler
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 5242880: 1229736271 - discarded
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:522)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:500)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:387)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:430)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:806)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:386)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.
Environment details: PKS / K8 with large cluster:
```
1 master nodes @ large.cpu (16 CPU, 16 GB Ram)
10 worker nodes @ xlarge.cpu(16 cpu, 16 GB Ram)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Pravega version : 0.6.0-2347.cd6bfe7
Zookeeper Operator : pravega/zookeeper:0.2.2
Pravega Operator:  pravega/zookeeper-operator:0.2.2
```

**Comment by SomeshJoshi19** [comment] 2019-09-05 15:52
Sharing the log location in internal channel due to size limit

**Comment by kevinhan88** [comment] 2019-09-05 16:47
Please provide metrics (memory usage in particular) along the test, plus the heapdump of the crashed segmentstore and bookkeeper for troubleshooting purpose.

**Comment by SomeshJoshi19** [comment] 2019-09-06 06:13
@kevinhan88 Metrics was not enabled for this stream run. Heap dump as generated for bookie is already being provided in the shared location along with the k8s logs and there was no heap dump generated by segment store. Please, find the necessary at the shared location.

**Comment by kevinhan88** [comment] 2019-09-10 16:19
Seems something happened to the VM sharing logs - the logs got erased.
@SomeshJoshi19 in your next test could you also turn on metrics?

**Comment by kevinhan88** [comment] 2019-09-12 00:45
<img width="537" alt="Heapdump_InstanceCounts" src="https://user-images.githubusercontent.com/24516773/64745235-e9eb5e00-d4bb-11e9-973f-cea8a43ef98d.PNG">
<img width="681" alt="Heapdump_Histogram" src="https://user-images.githubusercontent.com/24516773/64745237-ebb52180-d4bb-11e9-8d38-0c9d7f5ab527.PNG">

**Comment by kevinhan88** [comment] 2019-09-12 01:00
Observed the following errors from bookies events/logs:
13:33:37,408 ERROR Could not get additional bookie to remake ensemble, closing ledger: 44609
13:33:37,408 ERROR Closing ledger 44609 due to NotEnoughBookiesException: Not enough non-faulty bookies available
13:33:37,409 ERROR Write of ledger entry to quorum failed: L44609 E0
13:33:37,411 WARN  Error in bookie sanity test

**Comment by kevinhan88** [comment] 2019-09-13 22:37
Alternatively, if we want to make this test more comparable to other benchmark testings, is to stick with 3 bookies but increase the memory limit for each individual bookie, say from existing 6G to 12G.

**Comment by kevinhan88** [comment] 2019-09-20 18:07
Status update: the root cause of this issue has already been identified - it is due to OutOfMemory in bookkeeper.
The suggested solution was given out as well: either increase the number of bookies, or increase the max memory of existing bookies.

Per Somesh Joshi, QE team was not able to re-run the test due to no cluster available. Joshi, Somesh please update this jira once you're unblocked and making progress, thanks!

**Comment by andreipaduroiu** [comment] 2019-11-13 19:06
As stated above, this was due to an environment issue.

**Closed by andreipaduroiu** 2019-11-13 19:06 UTC
Labels: area/bookkeeper, area/segmentstore, kind/bug, priority/P1
