### ISSUE TITLE
Reader created before container failover reads after a delay post container recovery.

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#1307] opened 2017-05-11 10:14 UTC
**Problem description**
Summary: An old reader created before an SSS failover can't read from a segment whose container was recovered. {The reader(recovered) i.e. was able to read events only when a new writer post failover wrote events into that segment.}

Details:
The relevant log snippets which led to the above inference is present @
`https://emcnautilus.slack.com/archives/G3EP14GK1/p1494313594156471`
`https://emcnautilus.slack.com/archives/G3EP14GK1/p1494313681173743`
`https://emcnautilus.slack.com/archives/G3EP14GK1/p1494350639888639`

SSS failover: io.pravega.test.system.MultiSegmentStoreTest creates a failover in this case.

Logs: Detailed logs have been uploaded @ https://emcnautilus.slack.com/archives/G3EP14GK1/p1494261725357201

Note: This issue is observed when ControllerFailoverTest runs after MultiSegmentStoreTest

**Problem location**
Client. (as per current analysis)

**Comment by tkaitchuck** [comment] 2017-05-15 18:36
I suspect this is a duplicate of #1280. Lets see if #1303 fixes this.

**Closed** 2017-06-15 00:21 UTC
Labels: area/client
