### ISSUE TITLE
Readers failed with "java.lang.OutOfMemoryError:" on scaling up segments from 1000 to 5000

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega#3957] opened 2019-06-25 11:29 UTC
**Problem description**

On scaling up number of segments from 1000 to 5000, observed `java.lang.OutOfMemoryError: Java heap space`  error and `SegmentTruncatedException`  warning messages.

**6 parallel Pravega streams** from 6 separate client pods were running during the scaling operation with IO workload supplied by each stream is: - 1 worker ( 1 reader & 1 writer ), 100 events/sec, 100 bytes data and run time as 600 secs.

1) Writing operation passed for all the 6  streams running parallelly, matching the expected results: -
```
59112 records Writing, 95.269 records/sec, 100 bytes record size, 0.01 MB/sec, 33656.9 ms avg latency, 183810.0 ms max latency, 3083 ms 50th, 18136 ms 75th, 39423 ms 95th, 44866 ms 99th, 46285 ms 99.9th, 46453 ms 99.99th.
```
2) Reading operation failed for all the 6 streams running together with OOM error: -
```
[grpc-default-executor-0] INFO io.pravega.client.netty.impl.ConnectionPoolImpl - Reusing connection: Connection(uri=PravegaNodeUri(endpoint=172.24.24.16, port=12345), flowHandler=io.pravega.client.netty.impl.FlowHandler@3a86bc1e, connected=java.util.concurrent.CompletableFuture@7608718d[Completed normally])
[grpc-default-executor-0] INFO io.pravega.client.netty.impl.FlowHandler - Creating Flow 2174 for endpoint 172.24.24.16. The current Channel is [id: 0x77e74122, L:/172.24.24.17:50908 - R:172.24.24.16/172.24.24.16:12345].
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid1161.hprof ...
Heap dump file created [1262610900 bytes in 1.261 secs]
[grpc-default-executor-1] INFO io.pravega.client.netty.impl.ConnectionPoolImpl - Reusing connection: Connection(uri=PravegaNodeUri(endpoint=172.24.24.15, port=12345), flowHandler=io.pravega.client.netty.impl.FlowHandler@6ae82baa, connected=java.util.concurrent.CompletableFuture@5b00f831[Completed normally])
[grpc-default-executor-1] INFO io.pravega.client.netty.impl.FlowHandler - Creating Flow 2175 for endpoint 172.24.24.15. The current Channel is [id: 0x587b2178, L:/172.24.24.17:59724 - R:172.24.24.15/172.24.24.15:12345].
```
and SegmentTruncationException: -

```
[epollEventLoopGroup-4-2] INFO io.pravega.client.netty.impl.FlowHandler - Connection established with endpoint 172.24.24.15 on ChannelId [id: 0x5d4f6c92]
[epollEventLoopGroup-4-1] INFO io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl - Received segmentIsTruncated WireCommands.SegmentIsTruncated(type=SEGMENT_IS_TRUNCATED, requestId=4294967296, segment=Scope/_RGitr2Test1/0.#epoch.0, startOffset=571922, serverStackTrace=, offset=0)
[epollEventLoopGroup-4-1] WARN io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl - Exception while reading from Segment : Scope/_RGitr2Test1/0.#epoch.0
io.pravega.client.segment.impl.SegmentTruncatedException
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.segmentIsTruncated(AsyncSegmentInputStreamImpl.java:87)
        at io.pravega.shared.protocol.netty.WireCommands$SegmentIsTruncated.process(WireCommands.java:202)
        at io.pravega.shared.protocol.netty.ReplyProcessor.process(ReplyProcessor.java:20)
        at io.pravega.client.netty.impl.FlowHandler.lambda$channelRead$2(FlowHandler.java:209)
        at java.util.Optional.ifPresent(Optional.java:159)
        at io.pravega.client.netty.impl.FlowHandler.channelRead(FlowHandler.java:207)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```
3) The heap dump analysis suspects instances from `io.pravega.client.stream.impl.EventStreamReaderImpl` class for memory leakage problem.
Class Histogram report: -
```

Class Name                                                                  | Objects | Shallow Heap |    Retained Heap
------------------------------------------------------------------------------------------------------------------------
io.pravega.common.util.Retry$RetryWithBackoff                               |   1,175 |       47,000 |        >= 47,000
io.pravega.client.netty.impl.ClientConnectionImpl                           |   1,170 |       37,440 |        >= 57,232
io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl                  |   1,167 |       74,688 |       >= 598,640
io.pravega.client.segment.impl.SegmentInputStreamImpl                       |   1,167 |       65,352 | >= 1,223,365,864
io.pravega.common.util.CircularBuffer                                       |   1,167 |       28,008 | >= 1,222,798,424
io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor|   1,167 |       18,672 |        >= 19,080
io.pravega.client.segment.impl.EventSegmentReaderImpl                       |   1,166 |       27,984 | >= 1,223,494,704
io.pravega.shared.protocol.netty.WireCommands$SegmentRead                   |     966 |       46,368 |       >= 451,872
io.pravega.client.segment.impl.Segment                                      |   6,004 |      192,128 |       >= 912,136
io.pravega.common.util.Retry$RetryAndThrowBase$$Lambda$24             	    |     201 |        8,040 |        >= 13,208
io.pravega.common.concurrent.Futures$Loop                                   |     201 |        6,432 |        >= 28,544
io.pravega.common.util.Retry$RetryAndThrowBase$$Lambda$23                   |     201 |        3,216 |         >= 3,216
io.pravega.shared.protocol.netty.WireCommands$ReadSegment                   |     200 |        9,600 |        >= 30,456
io.pravega.common.util.Retry$RetryAndThrowBase$$Lambda$35                   |     200 |        6,400 |         >= 6,400
io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$$Lambda$148      |     200 |        4,800 |         >= 4,952
io.pravega.common.util.Retry$RetryAndThrowConditionally                     |     200 |        4,800 |         >= 8,000
------------------------------------------------------------------------------------------------------------------------
```
4) None of the client pod were evicted due to lack of resources. The resource allocation for all the 6 pods: -
```
        Started:      Mon, 24 Jun 2019 10:53:09 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     4
      memory:  6Gi
    Requests:
      cpu:        2
      memory:     4Gi
```

Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.
Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Pravega version : 0.5.0-2269.6f8a820
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```

**Comment by SomeshJoshi19** [comment] 2019-06-25 11:36
Sharing the logs and heap dump location on internal channel due to size limit.

**Comment by tkaitchuck** [comment] 2019-06-27 23:09
What was the jvm heap size limit on the reader process. My understanding of the above is that it attempting to read from 6*5000 segments at the same time. If that is from a single process, and is not overriding the default read buffer size that is going to attempt to allocate 30gb of read buffers. (5*6000*1mb) which is likely the cause of the OOM.

**Comment by SomeshJoshi19** [comment] 2019-06-28 15:30
@tkaitchuck minimum heap size allocation was 512 mb (xms) but maximum limit (xmx) value was not given while performing this stream run

**Comment by RaulGracia** [comment] 2019-07-01 10:48
This looks as a resource provisioning issue: the test attempted to target an scenario for which it was not provisioned accordingly, specifically in terms of memory. While understanding the memory/cpu consumption of a Pravega reader/writer in function to the number of segments would be an interesting exercise, it is a separate task not related to this bug report.

**Comment by fpj** [comment] 2019-07-02 09:59
Reopening so that we can respond with a way of running it appropriately.

**Comment by shrids** [comment] 2019-07-02 10:42
- The way to read a Pravega stream 5000 segment stream would be to increase the number of reader processes . All these event readers (which are part of the same reader group) will distribute the load of reading from different segments (5000). Each reader process needs to be configured with appropriate memory resources which takes care of having a read buffer of around 1MB per segment owned by a given reader.
- Do specify the jvm heap size limit of the reader and writer processes since by default the java server jvm would take around 1/4 of the available memory if Xmx is not specified.

**Comment by fpj** [comment] 2019-07-04 15:32
This is a general point about using Pravega and not specifically tied to a version. Please confirm that the answer is satisfactory, and otherwise come back with further clarification questions.

**Comment by sachin-j-joshi** [comment] 2019-07-11 14:30
@SomeshJoshi19 @shrids  Is this issue resolved ? If not what are the next steps ?

**Comment by shrids** [comment] 2019-07-17 10:01
Spoke to @SomeshJoshi19 in detail on this issue and talked about how reader processes can be scaled to handle all the 5000 segments and other Pravega writer related queries. Closing this issue based on this discussion.

**Closed by shrids** 2019-07-17 10:01 UTC
Labels: kind/question, priority/P1
