### ISSUE TITLE
Upgrade rocksdb

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#4053] opened 2019-07-24 13:08 UTC
**Problem description**
We need to upgrade RocksDB in the segment store to a later version.

**Problem location**
Segment store, cache, RocksDB.

**Suggestions for an improvement**
Upgrade RocksDB.

**Comment by fpj** [comment] 2019-07-24 13:16
The version we are currently using is `5.8.6`. The two options I see are that:

- We upgrade to the latest `v5` revision which is `5.8.13`
- We upgrade to `v6`, not necessarily the latest if it is not stable.

**Comment by andreipaduroiu** [comment] 2019-07-24 13:55
Another option is to investigate how we can eliminate the use of RocksDB altogether from Pravega.

**Comment by fpj** [comment] 2019-07-24 14:28
That's true, although we wouldn't be doing it in the `0.5` branch, so perhaps we should upgrade it at least there.

**Comment by RaulGracia** [comment] 2019-07-24 14:40
Just FYI, I have built an image of `0.5` + RocksDB `5.8.13`. There are no integration issues, but I haven't seen on this upgrade any specific improvement regarding the performance of our longevity workloads.

**Comment by andreipaduroiu** [comment] 2019-07-24 15:22
@fpj You want Rocks upgraded in 0.5? I am really concerned about other issues that we might not catch in time and just add more trouble.

This issue is labeled 0.5.1 and 0.6. I'm confused as to which one it really targets.

**Comment by andreipaduroiu** [comment] 2019-08-08 22:03
I'm lowering the priority of this because we determined this was not the cause of our stability problems. It still is a main contributing factor towards performance degradation, but that will be resolved with #4044.

**Closed** 2019-09-23 19:57 UTC
Labels: area/segmentstore, priority/P3, status/needs-attention
