### ISSUE TITLE
Flaky Test io.pravega.segmentstore.server.logs.ThrottlerTests > testInterruptedDecreasingDelayMetrics

### ISSUE THREAD

**Issue by abhinb** [pravega/pravega#6661] opened 2022-03-23 06:43 UTC
**Describe the bug**
The following test seems to be flaky on Git Actions:-

io.pravega.segmentstore.server.logs.ThrottlerTests > testInterruptedDecreasingDelayMetrics

>  java.lang.AssertionError: Excepted delay to be at least the smallest value. Expected: greater than or equal to 3000. Actual: 0.
2022-03-22T21:28:38.7355706Z         at org.junit.Assert.fail(Assert.java:88)
2022-03-22T21:28:38.7356133Z         at org.junit.Assert.assertTrue(Assert.java:41)
2022-03-22T21:28:38.7356706Z         at io.pravega.test.common.AssertExtensions.assertGreaterThanOrEqual(AssertExtensions.java:426)
2022-03-22T21:28:38.7357529Z         at io.pravega.segmentstore.server.logs.ThrottlerTests.testInterruptedDecreasingDelayMetrics(ThrottlerTests.java:294)

Logs here:- https://pipelines.actions.githubusercontent.com/a4u0Hc9XfNRPb6sVVBlb2T3v5ytZr7OKd0vxRenqKuBKtua6lU/_apis/pipelines/1/runs/6390/signedlogcontent/26?urlExpires=2022-03-23T06%3A36%3A29.2491797Z&urlSigningMethod=HMACV1&urlSignature=kEn0DwVewyyL3jf5cNMN99fu%2BJ91AAgJ3aVuHxtHaTo%3D

**To Reproduce**
Occurs sporadically on Git Actions.

**Additional information**
N/A

**Comment by RaulGracia** [comment] 2022-04-27 17:47
Duplicate of #6450.

**Closed by RaulGracia** 2022-04-27 17:47 UTC
Labels: area/segmentstore, priority/P2, version/0.11.0, tag/flakeyTest
