### ISSUE TITLE
Grafana shows no data in write bytes and write events for _MARK streams

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#4288] opened 2019-10-17 07:57 UTC
Deployment details:-
```
bookkeeper:0.6.0-2391.97363b3
pravega:0.6.0-2391.97363b3
openjdk:8
pravega/pravega-operator:0.4.2-rc2
pravega/zookeeper:0.2.4
pravega/zookeeper-operator:0.2.4
```
Environment details: PKS / K8 with medium cluster:
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
5 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```

Run longevity small-scale-tx-bytes . It is running in scope `longevity`
_MARKsmallScaleTxBytes is generated. It is showing data for Reads, but write data is not shown in grafana in streams dashboard.

**Comment by Raghuveera-Rao** [comment] 2019-10-17 07:58
![stream_dashboard1](https://user-images.githubusercontent.com/48913376/66989356-dd24e000-f0e1-11e9-91dd-a1fab36a2417.jpg)
![stream_dashboard2](https://user-images.githubusercontent.com/48913376/66989376-e4e48480-f0e1-11e9-8ab2-b6f0e5c11d52.jpg)
![stream_dashboard3](https://user-images.githubusercontent.com/48913376/66989395-eb72fc00-f0e1-11e9-8054-4abeb7dfe15f.jpg)
Pls find screenshot

**Comment by Raghuveera-Rao** [comment] 2019-10-17 08:00
Grafana details and log details will be provide in jira issue

**Comment by kevinhan88** [comment] 2019-11-09 00:47
<img width="804" alt="WatermarkMetrics" src="https://user-images.githubusercontent.com/24516773/68519607-f3d4d780-0246-11ea-95f6-ef0a24bc865f.PNG">

@Raghuveera-Rao Please find the attached screenshot, which proves Watermark metrics did get in and recorded.
Please re-test with the newer version of Pravega, if the problem is still there, could you please keep the scene, and ping me here and via slack channel, with access to your test env and grafana url, so I could investigate directly there?

**Comment by kevinhan88** [comment] 2019-11-11 19:07
The issue has been fixed as the side effect of https://github.com/pravega/pravega/issues/4291, close it.

**Closed by kevinhan88** 2019-11-11 19:07 UTC
Labels: kind/bug
