### ISSUE TITLE
Pravega pointer storage efficience

### ISSUE THREAD

**Issue by TonySpace** [pravega/pravega#1942] opened 2017-10-04 23:18 UTC
**Problem description**
In pravega search, we'd like to use pravega pointer to avoid copying source event into pravega search. This pointer will be stored in psearch index. 
But the problem is, after serialization, its size is 500+ bytes, while, in many cases, the document to be indexed is less than 500 bytes, for example, the logs. 

We will need a efficient way to store pravega pointer.

**Problem location**
Pravega client

**Suggestions for an improvement**
only serialize the minimal necessary fields.

**Comment by andreipaduroiu** [comment] 2017-10-05 15:27
Is this related to #1941 ?

**Comment by fpj** [comment] 2017-10-10 15:27
Marking it as duplicate of #1941

**Closed by fpj** 2017-10-10 15:27 UTC
Labels: kind/duplicate
