### ISSUE TITLE
IO Failure observed as controller re-spawned on docker swarm setup during longevity run using pravega-benchmark

### ISSUE THREAD

**Issue by vedanthh** [pravega/pravega#3077] opened 2018-11-04 15:49 UTC
**IO Failure observed as controller re-spawned on docker swarm setup during longevity run using pravega-benchmark**

In a Docker Swarm environment, started moderate IO with Pravega Benchmark tool and  IO failures had been observed (console snip below) as controller exited and re-spawned in different node after ~20-22 hrs of IO run.

**Configuration Change:**
```
Segment store memory - ~30GB
Controller Memory - 2048 MB
```
**Docker swarm setup**
```
4 Nodes - 1 Master, 3 Workers. Deployment:
1 Controller
1 Zookeeper
1 Segment Store
3 BookKeeper
1 Pravega_HDFS
```

**Console snip**
```pravega/pravega@sha256:e944e214d4bedfd3c835444b087968278c0cf0ca2fff67126a371f4b1212e778   "/opt/pravega/scri..."   27 hours ago        Exited (255) 3 hours ago                                         pravega_controller.1.na2xipv9q2dg04s6pwuqvh1u8```
```
 pravega-benchmark]# time ./pravega-benchmark/bin/pravega-benchmark  --controller tcp://<PUBLISHED IP>:9090 --stream StreamName-r3  -producers 1 --size 100  -eventspersec 1000 --runtime 86400 --randomkey true  --writeonly true
ad2a51d20234        


        at java.lang.Thread.run(Thread.java:745)
2018-11-03 09:57:25,037 85998612 [epollEventLoopGroup-2-11] WARN  i.p.c.s.i.SegmentOutputStreamImpl - Connection for segment _system/_abortStream/1.#epoch.0 on writer 4b3ec01c-9a26-42b4-99f2-b37fedeed945 failed due to: class io.pravega.shared.protocol.netty.ConnectionFailedException
2018-11-03 09:57:25,035 85998610 [ControllerServiceMain] INFO  o.apache.zookeeper.ClientCnxnSocket - jute.maxbuffer value is 4194304 Bytes
2018-11-03 09:57:25,037 85998612 [epollEventLoopGroup-2-11] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Failing connection for writer 84ece349-d806-4c62-aa59-d6b47ac051fa with exception io.pravega.shared.protocol.netty.ConnectionFailedException
2018-11-03 09:57:25,037 85998612 [epollEventLoopGroup-2-11] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Handling exception io.pravega.shared.protocol.netty.ConnectionFailedException for connection io.pravega.client.netty.impl.ClientConnectionInboundHandler@cbb8e49 on writer 84ece349-d806-4c62-aa59-d6b47ac051fa. SetupCompleted: true, Closed: false
2018-11-03 09:57:25,037 85998612 [epollEventLoopGroup-2-11] WARN  i.p.c.s.i.SegmentOutputStreamImpl - Connection for segment _system/_requeststream/1.#epoch.0 on writer 84ece349-d806-4c62-aa59-d6b47ac051fa failed due to: class io.pravega.shared.protocol.netty.ConnectionFailedException
2018-11-03 09:57:25,036 85998611 [epollEventLoopGroup-2-13] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Connection failed due to a io.pravega.shared.protocol.netty.ConnectionFailedException. Read requests will be retransmitted.
2018-11-03 09:57:25,038 85998613 [epollEventLoopGroup-2-13] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : _system/_requeststream/1.#epoch.0
io.pravega.shared.protocol.netty.ConnectionFailedException: null
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.connectionDropped(AsyncSegmentInputStreamImpl.java:60)
        at io.pravega.client.netty.impl.ClientConnectionInboundHandler.channelUnregistered(ClientConnectionInboundHandler.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1337)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:835)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:830)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:379)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor.confirmShutdown(SingleThreadEventExecutor.java:678)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:323)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:745)
2018-11-03 09:57:25,039 85998614 [ControllerServiceMain-SendThread(zookeeper:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server zookeeper/10.0.0.4:2181. Will not attempt to authenticate using SASL (unknown error)
2018-11-03 09:57:25,039 85998614 [ControllerServiceMain] INFO  o.a.c.f.imps.CuratorFrameworkImpl - Default schema
2018-11-03 09:57:25,039 85998614 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - Awaiting ZK client connection to ZK server
2018-11-03 09:57:25,040 85998615 [ControllerServiceMain-SendThread(zookeeper:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /10.0.0.13:49616, server: zookeeper/10.0.0.4:2181
2018-11-03 09:57:25,047 85998622 [ControllerServiceMain-SendThread(zookeeper:2181)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server zookeeper/10.0.0.4:2181, sessionid = 0x10000d1b9b70017, negotiated timeout = 10000
2018-11-03 09:57:25,047 85998622 [ControllerServiceMain-EventThread] INFO  o.a.c.f.s.ConnectionStateManager - State change: CONNECTED
2018-11-03 09:57:25,047 85998622 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - Awaiting ZK session expiry or termination trigger for ControllerServiceMain
2018-11-03 09:57:25,047 85998622 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - Starting controller services
2018-11-03 09:57:25,048 85998623 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - Awaiting controller services start
2018-11-03 09:57:25,049 85998624 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - Initiating controller service startUp
2018-11-03 09:57:25,049 85998624 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - Event processors enabled = true
2018-11-03 09:57:25,049 85998624 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - Cluster listener enabled = true
2018-11-03 09:57:25,049 85998624 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter -     Host monitor enabled = true
2018-11-03 09:57:25,049 85998624 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter -      gRPC server enabled = true
2018-11-03 09:57:25,049 85998624 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter -      REST server enabled = true
2018-11-03 09:57:25,049 85998624 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - Creating the stream store
2018-11-03 09:57:25,050 85998625 [ControllerServiceStarter STARTING] INFO  i.p.s.metrics.StatsProviderImpl - Configuring stats with statsD at localhost:8125
2018-11-03 09:57:25,050 85998625 [ControllerServiceMain-EventThread] INFO  o.a.c.f.imps.EnsembleTracker - New config event received: {server.1=localhost:2888:3888:participant;0.0.0.0:2181, version=0}
2018-11-03 09:57:25,051 85998626 [ControllerServiceMain] ERROR i.p.c.server.ControllerServiceMain - Controller Service Main thread exited exceptionally
java.lang.IllegalStateException: Expected the service ControllerServiceStarter [FAILED] to be RUNNING, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
        at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:266)
        at com.google.common.util.concurrent.AbstractIdleService.awaitRunning(AbstractIdleService.java:175)
        at io.pravega.controller.server.ControllerServiceMain.run(ControllerServiceMain.java:132)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Reporter already started
        at com.codahale.metrics.ScheduledReporter.start(ScheduledReporter.java:167)
        at com.codahale.metrics.ScheduledReporter.start(ScheduledReporter.java:155)
        at io.pravega.shared.metrics.StatsProviderImpl.start(StatsProviderImpl.java:128)
        at io.pravega.shared.metrics.StatsProviderProxy.start(StatsProviderProxy.java:40)
        at io.pravega.controller.store.stream.ZKStreamMetadataStore.initialize(ZKStreamMetadataStore.java:92)
        at io.pravega.controller.store.stream.ZKStreamMetadataStore.<init>(ZKStreamMetadataStore.java:81)
        at io.pravega.controller.store.stream.StreamStoreFactory.createStore(StreamStoreFactory.java:30)
        at io.pravega.controller.store.stream.StreamStoreFactory.createStore(StreamStoreFactory.java:22)
        at io.pravega.controller.server.ControllerServiceStarter.startUp(ControllerServiceStarter.java:126)
        at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
        ... 2 common frames omitted
2018-11-03 09:57:25,051 85998626 [Curator-Framework-0] INFO  o.a.c.f.imps.CuratorFrameworkImpl - backgroundOperationsLoop exiting
2018-11-03 09:57:25,058 85998633 [ControllerServiceMain-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x10000d1b9b70017
2018-11-03 09:57:25,058 85998633 [ControllerServiceMain] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x10000d1b9b70017 closed
2018-11-03 09:57:25,059 85998634 [main] ERROR io.pravega.controller.server.Main - Controller service failed
java.lang.IllegalStateException: Expected the service ControllerServiceMain [FAILED] to be TERMINATED, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
        at com.google.common.util.concurrent.AbstractService.awaitTerminated(AbstractService.java:293)
        at com.google.common.util.concurrent.AbstractExecutionThreadService.awaitTerminated(AbstractExecutionThreadService.java:239)
        at io.pravega.controller.server.Main.main(Main.java:87)
Caused by: java.lang.IllegalStateException: Expected the service ControllerServiceStarter [FAILED] to be RUNNING, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
        at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:266)
        at com.google.common.util.concurrent.AbstractIdleService.awaitRunning(AbstractIdleService.java:175)
        at io.pravega.controller.server.ControllerServiceMain.run(ControllerServiceMain.java:132)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Reporter already started
        at com.codahale.metrics.ScheduledReporter.start(ScheduledReporter.java:167)
        at com.codahale.metrics.ScheduledReporter.start(ScheduledReporter.java:155)
        at io.pravega.shared.metrics.StatsProviderImpl.start(StatsProviderImpl.java:128)
        at io.pravega.shared.metrics.StatsProviderProxy.start(StatsProviderProxy.java:40)
        at io.pravega.controller.store.stream.ZKStreamMetadataStore.initialize(ZKStreamMetadataStore.java:92)
        at io.pravega.controller.store.stream.ZKStreamMetadataStore.<init>(ZKStreamMetadataStore.java:81)
        at io.pravega.controller.store.stream.StreamStoreFactory.createStore(StreamStoreFactory.java:30)
        at io.pravega.controller.store.stream.StreamStoreFactory.createStore(StreamStoreFactory.java:22)
        at io.pravega.controller.server.ControllerServiceStarter.startUp(ControllerServiceStarter.java:126)
        at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
        ... 2 common frames omitted
```
[Logs_Longevity.zip](https://github.com/pravega/pravega/files/2545973/Logs_Longevity.zip)

**Comment by shiveshr** [comment] 2018-11-05 05:10
@vedanthh can you please share controller logs from the failed controller. 

Also, what was the cause for failure, was it oom or something else?

@RaulGracia has observed few OOM crashes in 0.3 too. I take it this is running against 0.4 build. 
We need to profile controller process to see where the memory leak is happening.

**Comment by vedanthh** [comment] 2018-11-05 05:19
@shiveshr I have already attached logs, please check `Logs_Longevity.zip` https://github.com/pravega/pravega/files/2545973/Logs_Longevity.zip it has all the logs from that cluster.

**Comment by vedanthh** [comment] 2018-11-05 05:33
No i didn't observed any failures in zookeeper, it is up and running fine after deployment ~2 days.
```
da300ae1c048        zookeeper@sha256:1cb0ea64320184ebe360692dd1a8dbd3db8394bde029558863563d625e99f46a            "/docker-entrypoin..."   2 days ago          Up 2 days           2181/tcp, 2888/tcp, 3888/tcp   pravega_zookeeper.1.sdhh7wdmryue2kq01lkmlp35v
```

**Comment by RaulGracia** [comment] 2018-11-07 16:19
Probably related to #3042.

**Comment by fpj** [comment] 2018-12-17 14:00
Controller instance shutting down due to session expiration is a correct behavior. A different issue is why it expired. But let me emphasize: **ZK session expiration is expected in production, the behavior described here is not indicating a controller issue**. At best, this is a docker swarm provisioning issue from the description.

**Comment by shiveshr** [comment] 2018-12-17 14:54
@fpj 

Upon receiving Zookeeper Session expiration, the process itself is not restarted. The modules inside the process are shutdown and after a clean shutdown, new module specific objects are instantiated. 

So to anyone looking at the cluster, a zk session expiration should ideally be a silent activity handled internally on controller. 
The issues we have encountered are: for various reasons, the shutdown of modules have been getting stalled (PR out) or after a shutdown the restart had failed (PR out and merged).

**Comment by RaulGracia** [comment] 2019-01-02 08:39
After moving the metrics reporter start logic to `Main.java` in #3117, we do not encounter the `java.lang.IllegalArgumentException: Reporter already started` error message anymore.

As a proof for that, this the log for a Controller restart in a longevity run including #3117:
```
2018-12-21 13:43:58,017 276988617 [ControllerServiceStarter STOPPING] ERROR o.a.curator.CuratorZookeeperClient - 
java.io.IOException: java.lang.IllegalArgumentException: connectString differs
	at org.apache.curator.ConnectionState.close(ConnectionState.java:127)
	at org.apache.curator.CuratorZookeeperClient.close(CuratorZookeeperClient.java:227)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.close(CuratorFrameworkImpl.java:381)
	at io.pravega.controller.store.client.ZKStoreClient.close(ZKStoreClient.java:37)
	at io.pravega.controller.server.ControllerServiceStarter.shutDown(ControllerServiceStarter.java:361)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$2.run(AbstractIdleService.java:79)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: connectString differs
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at io.pravega.controller.store.client.StoreClientFactory$ZKClientFactory.newZooKeeper(StoreClientFactory.java:118)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$2.newZooKeeper(CuratorFrameworkImpl.java:191)
	at org.apache.curator.HandleHolder$1.getZooKeeper(HandleHolder.java:101)
	at org.apache.curator.HandleHolder.internalClose(HandleHolder.java:147)
	at org.apache.curator.HandleHolder.closeAndClear(HandleHolder.java:78)
	at org.apache.curator.ConnectionState.close(ConnectionState.java:122)
	... 7 common frames omitted
2018-12-21 13:43:58,018 276988618 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - calling close on store client
2018-12-21 13:43:58,018 276988618 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - Creating store client
2018-12-21 13:43:58,023 276988623 [ControllerServiceMain] WARN  o.a.curator.CuratorZookeeperClient - session timeout [10000] is less than connection timeout [15000]
2018-12-21 13:43:58,023 276988623 [ControllerServiceMain] INFO  o.a.c.f.imps.CuratorFrameworkImpl - Starting
2018-12-21 13:43:58,025 276988625 [ControllerServiceMain] INFO  org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=nautilus-pravega-zookeeper-client:2181 sessionTimeout=10000 watcher=org.apache.curator.ConnectionState@6fc77dc7
2018-12-21 13:43:58,028 276988628 [ControllerServiceMain] INFO  o.apache.zookeeper.ClientCnxnSocket - jute.maxbuffer value is 4194304 Bytes
2018-12-21 13:43:58,031 276988631 [ControllerServiceMain] INFO  o.a.c.f.imps.CuratorFrameworkImpl - Default schema
2018-12-21 13:43:58,031 276988631 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - Awaiting ZK client connection to ZK server
2018-12-21 13:43:58,034 276988634 [ControllerServiceMain-SendThread(nautilus-pravega-zookeeper-client:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server nautilus-pravega-zookeeper-client/10.100.200.204:2181. Will not attempt to authenticate using SASL (unknown error)
2018-12-21 13:43:58,037 276988637 [ControllerServiceMain-SendThread(nautilus-pravega-zookeeper-client:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /10.200.89.12:56144, server: nautilus-pravega-zookeeper-client/10.100.200.204:2181
2018-12-21 13:43:58,042 276988642 [ControllerServiceMain-SendThread(nautilus-pravega-zookeeper-client:2181)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server nautilus-pravega-zookeeper-client/10.100.200.204:2181, sessionid = 0x30007e4b5bf3aa6, negotiated timeout = 10000
2018-12-21 13:43:58,042 276988642 [ControllerServiceMain-EventThread] INFO  o.a.c.f.s.ConnectionStateManager - State change: CONNECTED
2018-12-21 13:43:58,042 276988642 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - Awaiting ZK session expiry or termination trigger for ControllerServiceMain
2018-12-21 13:43:58,043 276988643 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - Starting controller services
2018-12-21 13:43:58,043 276988643 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - Awaiting controller services start
2018-12-21 13:43:58,061 276988661 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - Initiating controller service startUp
2018-12-21 13:43:58,062 276988662 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - Event processors enabled = true
2018-12-21 13:43:58,062 276988662 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - Cluster listener enabled = true
2018-12-21 13:43:58,063 276988663 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter -     Host monitor enabled = true
2018-12-21 13:43:58,063 276988663 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter -      gRPC server enabled = true
2018-12-21 13:43:58,063 276988663 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter -      REST server enabled = true
2018-12-21 13:43:58,063 276988663 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - Creating the stream store
2018-12-21 13:43:58,092 276988692 [ControllerServiceMain-EventThread] INFO  o.a.c.f.imps.EnsembleTracker - New config event received: {server.1=nautilus-pravega-zookeeper-0.nautilus-pravega-zookeeper-headless.nautilus-pravega.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, version=100000084, server.3=nautilus-pravega-zookeeper-2.nautilus-pravega-zookeeper-headless.nautilus-pravega.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, server.2=nautilus-pravega-zookeeper-1.nautilus-pravega-zookeeper-headless.nautilus-pravega.svc.cluster.local:2888:3888:participant;0.0.0.0:2181}
2018-12-21 13:43:58,146 276988746 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - Creating the task store
2018-12-21 13:43:58,146 276988746 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - Creating the host store
2018-12-21 13:43:58,146 276988746 [ControllerServiceStarter STARTING] INFO  i.p.c.store.host.HostStoreFactory - Creating Zookeeper based host store
2018-12-21 13:43:58,147 276988747 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - Creating the checkpoint store
2018-12-21 13:43:58,149 276988749 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - Starting segment container monitor
2018-12-21 13:43:58,161 276988761 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - starting auto retention service asynchronously
2018-12-21 13:43:58,172 276988772 [Curator-LeaderSelector-1] INFO  i.p.c.fault.SegmentMonitorLeader - Obtained leadership to monitor the Host to Segment Container Mapping
2018-12-21 13:43:58,172 276988772 [controllerpool-2] INFO  i.p.c.s.retention.StreamCutService - Taken ownership for bucket 0
2018-12-21 13:43:58,173 276988773 [retentionpool-1] INFO  i.p.c.s.r.StreamCutBucketService - Adding new stream longevity/mediumScale to bucket 0 during bootstrap
2018-12-21 13:43:58,174 276988774 [retentionpool-1] INFO  i.p.c.s.r.StreamCutBucketService - streams collected for the bucket 0, registering for change notification and starting loop for processing notifications
2018-12-21 13:43:58,174 276988774 [retentionpool-1] INFO  i.p.c.s.s.ZKStreamMetadataStore - bucket 0 change notification listener registered
2018-12-21 13:43:58,184 276988784 [retentionpool-1] INFO  i.p.c.s.s.ZKStreamMetadataStore - bucket ownership listener registered
2018-12-21 13:43:58,205 276988805 [Curator-LeaderSelector-1] INFO  i.p.c.fault.SegmentMonitorLeader - Received rebalance event
2018-12-21 13:43:58,206 276988806 [Curator-LeaderSelector-1] INFO  i.p.c.fault.SegmentMonitorLeader - Waiting for 10 seconds before attempting to rebalance
2018-12-21 13:43:58,204 276988804 [retentionpool-1] INFO  i.p.c.s.r.StreamCutBucketService - New stream longevity/mediumScale added to bucket 0 
2018-12-21 13:43:58,213 276988813 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - Starting event processors
2018-12-21 13:43:58,213 276988813 [ControllerServiceStarter STARTING] INFO  i.p.c.s.e.ControllerEventProcessors - Bootstrapping controller event processors
2018-12-21 13:43:58,215 276988815 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - Starting controller cluster listener
2018-12-21 13:43:58,221 276988821 [ControllerClusterListener STARTING] INFO  i.p.c.f.ControllerClusterListener - Registering host 10.200.89.12:9090:a525a796-185c-435f-8f6c-eb89efa38bdc with controller cluster
2018-12-21 13:43:58,221 276988821 [ControllerClusterListener STARTING] INFO  i.p.c.f.ControllerClusterListener - Adding controller cluster listener
2018-12-21 13:43:58,222 276988822 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - Awaiting start of rpc server
2018-12-21 13:43:58,224 276988824 [GRPCServer STARTING] INFO  i.p.c.server.rpc.grpc.GRPCServer - Starting gRPC server listening on port: 9090
2018-12-21 13:43:58,232 276988832 [controllerpool-2] INFO  i.p.c.s.e.ControllerEventProcessors - Created controller scope _system
2018-12-21 13:43:58,249 276988849 [controllerpool-7] WARN  i.p.c.f.ControllerClusterListener - java.lang.RuntimeException: sweeper not ready
2018-12-21 13:43:58,249 276988849 [ControllerClusterListener STARTING] INFO  i.p.c.f.ControllerClusterListener - Controller cluster listener startUp complete
2018-12-21 13:43:58,251 276988851 [controllerpool-13] WARN  i.p.c.f.ControllerClusterListener - java.lang.RuntimeException: sweeper not ready
2018-12-21 13:43:58,255 276988855 [controllerpool-12] INFO  i.p.controller.task.TaskSweeper - Hosts [10.200.89.12-a525a796-185c-435f-8f6c-eb89efa38bdc] have ongoing tasks
2018-12-21 13:43:58,256 276988856 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - Awaiting start of REST server
2018-12-21 13:43:58,269 276988869 [RESTServer STARTING] INFO  i.p.c.server.rest.RESTServer - Starting REST server listening on port: 10080
2018-12-21 13:43:58,270 276988870 [controllerpool-12] INFO  i.p.controller.task.TaskSweeper - Failed hosts [] have orphaned tasks
2018-12-21 13:43:58,358 276988958 [controllerpool-29] WARN  i.p.c.f.ControllerClusterListener - java.lang.RuntimeException: sweeper not ready
2018-12-21 13:43:58,358 276988958 [controllerpool-29] WARN  i.p.c.f.ControllerClusterListener - java.lang.RuntimeException: sweeper not ready
2018-12-21 13:43:58,558 276989158 [controllerpool-63] INFO  i.p.c.t.Stream.StreamMetadataTasks - _system/_abortStream created in metadata store
2018-12-21 13:43:58,562 276989162 [controllerpool-63] WARN  i.p.c.f.ControllerClusterListener - java.lang.RuntimeException: sweeper not ready
2018-12-21 13:43:58,562 276989162 [controllerpool-63] WARN  i.p.c.f.ControllerClusterListener - java.lang.RuntimeException: sweeper not ready
2018-12-21 13:43:58,568 276989168 [ControllerServiceStarter STARTING] INFO  i.p.c.s.ControllerServiceStarter - Awaiting start of controller event processors
```

**Closed by RaulGracia** 2019-01-02 08:39 UTC
Labels: area/controller, kind/bug, priority/P0, status/needs-attention
