### ISSUE TITLE
Not able to run I/O with benchmark after running longevity for 2 hours

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#4306] opened 2019-10-22 17:05 UTC
Environment details: PKS / K8 with medium cluster:
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
5 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Deployment details:
```
bookkeeper:0.6.0-2401.83b62b8
pravega:0.6.0-2401.83b62b8
openjdk:8
pravega/pravega-operator:0.4.2-rc2
pravega/zookeeper:0.2.4
pravega/zookeeper-operator:0.2.4
```
Started longevity `medium-scale`.
It is running fine for ~ 2 hours
```
INFO  [2019-10-22 16:57:53,011] io.pravega.longevity.utils.PerformanceUtils: Readers (8/8): events:12,879,617, events/sec:1,216, KB/sec:932.46387
INFO  [2019-10-22 16:57:53,011] io.pravega.longevity.utils.PerformanceUtils: New runtime for 211b0d86-04b0-44c5-8644-f8b19d2ca85f  Running for 2h 56m
INFO  [2019-10-22 16:57:53,011] io.pravega.longevity.utils.PerformanceUtils: Dumping stats for stream longevity/mediumScale
INFO  [2019-10-22 16:57:53,011] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:13,655,508, events/sec:1,293, KB/sec:991.4453
INFO  [2019-10-22 16:57:53,011] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
```

Now tried to run benchmark tool inside the pod:-

 $./pravega-benchmark -consumers 1 -controller tcp://10.100.200.220:9090 -events 100 -segments 10 -size 100 -producers 1 -time 180 -scope Scope3 -stream st1
```
2019-10-22 16:29:23:504 +0000 [main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.100.200.220:9090
2019-10-22 16:29:23:508 +0000 [main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.100.200.220:9090
2019-10-22 16:29:23:535 +0000 [main] INFO io.pravega.client.admin.impl.StreamManagerImpl - Creating scope: Scope3
2019-10-22 16:29:23:545 +0000 [StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=-733771830804446344] Tagging client request (createScope-Scope3).
2019-10-22 16:29:23:589 +0000 [StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[[/10.100.200.220:9090]/{}]]
2019-10-22 16:31:15:187 +0000 [grpc-default-executor-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=-733771830804446344] Scope created successfully: Scope3
2019-10-22 16:31:15:189 +0000 [main] INFO io.pravega.client.admin.impl.StreamManagerImpl - Creating scope/stream: Scope3/st1 with configuration: StreamConfiguration(scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=10), retentionPolicy=null, timestampAggregationTimeout=0)
2019-10-22 16:31:15:191 +0000 [StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=6902141888876209497] Tagging client request (createStream-Scope3-st1).
```

I/O is not happening with benchmark tool.

Tried to run one more longevity `SmallScaleTxBytes`.
It is throwing 503 error:-
```
WARN  [2019-10-22 16:31:43,659] io.pravega.client.stream.impl.ControllerImpl: [requestId=7946961853164052243] Stream already exists: _RGLongevitySmallScaleTxBytes
INFO  [2019-10-22 16:31:43,678] io.pravega.client.stream.impl.ClientFactoryImpl: Creating state synchronizer with stream: _RGLongevitySmallScaleTxBytes and configuration: SynchronizerConfig(eventWriterConfig=EventWriterConfig(initalBackoffMillis=1, maxBackoffMillis=20000, retryAttempts=10, backoffMultiple=10, enableConnectionPooling=true, transactionTimeoutTime=89999, automaticallyNoteTime=false), readBufferSize=262144)
172.28.28.5 - - [22/Oct/2019:16:31:44 +0000] "GET /v1/longevity/ready HTTP/1.1" 503 60 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 2
172.28.28.5 - - [22/Oct/2019:16:31:46 +0000] "GET /v1/longevity/ready HTTP/1.1" 503 60 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 1
172.28.28.5 - - [22/Oct/2019:16:31:48 +0000] "GET /v1/longevity/ready HTTP/1.1" 503 60 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 4
172.28.28.5 - - [22/Oct/2019:16:31:50 +0000] "GET /v1/longevity/ready HTTP/1.1" 503 60 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 2
172.28.28.5 - - [22/Oct/2019:16:31:52 +0000] "GET /v1/longevity/ready HTTP/1.1" 503 60 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 1
172.28.28.5 - - [22/Oct/2019:16:31:54 +0000] "GET /v1/longevity/ready HTTP/1.1" 503 60 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 1
172.28.28.5 - - [22/Oct/2019:16:31:56 +0000] "GET /v1/longevity/ready HTTP/1.1" 503 60 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 2
172.28.28.5 - - [22/Oct/2019:16:31:58 +0000] "GET /v1/longevity/ready HTTP/1.1" 503 60 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 2
172.28.28.5 - - [22/Oct/2019:16:32:00 +0000] "GET /v1/longevity/ready HTTP/1.1" 503 60 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 2
172.28.28.5 - - [22/Oct/2019:16:32:02 +0000] "GET /v1/longevity/ready HTTP/1.1" 503 60 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 2
172.28.28.5 - - [22/Oct/2019:16:32:04 +0000] "GET /v1/longevity/ready HTTP/1.1" 503 60 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 1
```

**Comment by Raghuveera-Rao** [comment] 2019-10-22 17:09
[pravega-k8s-logging-2019-10-22-10-39-55.zip](https://github.com/pravega/pravega/files/3757311/pravega-k8s-logging-2019-10-22-10-39-55.zip)
pls find complete k8s logs

**Comment by kevinhan88** [comment] 2019-10-23 00:09
@andreipaduroiu assign this to you as this is segmentstore related issue. I did some initial investigation, just for your convenience:

Firstly the test run longevity medium-scale for 2 hours, so far so good
scope: longevity, stream: medium-scale
(metrics shows this longevity test is still going)

Then the test run benchmark (note the above longevity is still running): no I/O observed
scope: Scope3, stream: st1
(metrics: no data shown for this stream, no tag value for the stream showing either)
Look into this log: oldlogs_pravega-pravega-segmentstore-1/segmentstore.log
2019-10-22 16:36:13,838 26340118 [core-16] WARN  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=12330851106816] Segment '_system/_tables/Scope3/st1/metadata.#.9c893364-fb4d-477d-8219-4b8e4488df3e' does not exist and cannot perform operation 'readTable'.

Finally the test tried to run one more longevity (scope:longevity, stream: SmallScaleTxBytes) - no I/O observed.
(metrics: no data shown, however, the tag value "smallScaleTxBytes" shows up)
mainly inside this log: log_pod_pravega-pravega-segmentstore-2_recent.log
2019-10-22 15:19:06,467 21700074 [core-13] WARN  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=7365868912640] Segment '_system/_tables/longevity/_RGLongevitySmallScaleTxBytes/metadata.#.d8df7599-4f73-463e-abc7-441cdfbd8a4f' does not exist and cannot perform operation 'readTable'.

**Comment by andreipaduroiu** [comment] 2019-10-23 01:26
@kevinhan88 That error is normal It's because the controller wants to use a segment before it's created. @shiveshr may be able to say more on this

**Comment by Raghuveera-Rao** [comment] 2019-10-23 06:05
medium-scale readers also failed.
`Readers (0/8)`
```
INFO  [2019-10-23 06:01:23,010] io.pravega.longevity.utils.PerformanceUtils: Readers (0/8): events:15,023,204, events/sec:260, KB/sec:199.96973
INFO  [2019-10-23 06:01:23,010] io.pravega.longevity.utils.PerformanceUtils: New runtime for 211b0d86-04b0-44c5-8644-f8b19d2ca85f  Running for 16h 0m
INFO  [2019-10-23 06:01:23,010] io.pravega.longevity.utils.PerformanceUtils: Dumping stats for stream longevity/mediumScale
INFO  [2019-10-23 06:01:23,010] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:60,428,480, events/sec:1,049, KB/sec:804.34375
INFO  [2019-10-23 06:01:23,010] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0                    
INFO  [2019-10-23 06:01:23,010] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0                                           
INFO  [2019-10-23 06:01:23,010] io.pravega.longevity.utils.PerformanceUtils: Readers (0/8): events:15,023,204, events/sec:260, KB/sec:199.96973                                              
172.28.28.2 - - [23/Oct/2019:06:01:23 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 2717 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 2                                          
INFO  [2019-10-23 06:01:53,010] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 16h 0m                                                                                
INFO  [2019-10-23 06:01:53,010] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:60,458,553, events/sec:1,049, KB/sec:804.3252                                             
INFO  [2019-10-23 06:01:53,010] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0                    
INFO  [2019-10-23 06:01:53,010] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-10-23 06:01:53,010] io.pravega.longevity.utils.PerformanceUtils: Readers (0/8): events:15,023,204, events/sec:260, KB/sec:199.86621
INFO  [2019-10-23 06:01:53,010] io.pravega.longevity.utils.PerformanceUtils: New runtime for 211b0d86-04b0-44c5-8644-f8b19d2ca85f  Running for 16h 0m
INFO  [2019-10-23 06:01:53,010] io.pravega.longevity.utils.PerformanceUtils: Dumping stats for stream longevity/mediumScale
INFO  [2019-10-23 06:01:53,010] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:60,458,553, events/sec:1,049, KB/sec:804.74414
INFO  [2019-10-23 06:01:53,010] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-10-23 06:01:53,010] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-10-23 06:01:53,010] io.pravega.longevity.utils.PerformanceUtils: Readers (0/8): events:15,023,204, events/sec:260, KB/sec:199.96973
172.28.28.2 - - [23/Oct/2019:06:01:53 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 2711 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 1
```

**Comment by shiveshr** [comment] 2019-11-08 02:27
There are couple of places where tables are created only if they do not exist. 

So we attempt to read from the table under the assumption that it exists, and if we get table not found, we create it.

For here it starts with create stream where we first check if a stream already exists (either in fully created or partially created state) by querying for its metadata (if its a new stream, we will get Table Does Not Exist and it is expected).
And we proceed with creating it. 

*So the log that @kevinhan88 has highlighted is expected and benign. It is not the root cause for IO not working. *

case in point:
```
oldlogs_pravega-pravega-segmentstore-1/segmentstore.log:2019-10-22 16:36:13,838 26340118 [core-16] WARN  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=12330851106816] Segment '_system/_tables/Scope3/st1/metadata.#.9c893364-fb4d-477d-8219-4b8e4488df3e' does not exist and cannot perform operation 'readTable'.
oldlogs_pravega-pravega-segmentstore-1/segmentstore.log:2019-10-22 16:36:13,840 26340120 [epollEventLoopGroup-11-6] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=12476879994880] Creating table segment WireCommands.CreateTableSegment(type=CREATE_TABLE_SEGMENT, requestId=12476879994880, segment=_system/_tables/Scope3/st1/metadata.#.9c893364-fb4d-477d-8219-4b8e4488df3e, delegationToken=).
```

PS: The logs are only collected till around this time while this stream in question `Scope3/st1` was being created. 
So we dont have complete logs from `controller` or `segmentstore-0` for what happened to an attempt to create this stream. But from partial evidence available, there is no reason for this to have failed. 
Stream Metadata creation had completed, and stream segments were being created when these logs were collected. 

```
oldlogs_pravega-pravega-segmentstore-1/segmentstore.log:2019-10-22 16:37:02,020 26388300 [epollEventLoopGroup-11-6] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=12734578032640] Creating stream segment WireCommands.CreateSegment(type=CREATE_SEGMENT, requestId=12734578032640, segment=Scope3/st1/1.#epoch.0, scaleType=0, targetRate=0, delegationToken=).
oldlogs_pravega-pravega-segmentstore-2/segmentstore.log:2019-10-22 16:37:02,020 26375627 [epollEventLoopGroup-11-6] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=12704513261568] Creating stream segment WireCommands.CreateSegment(type=CREATE_SEGMENT, requestId=12704513261568, segment=Scope3/st1/8.#epoch.0, scaleType=0, targetRate=0, delegationToken=).
oldlogs_pravega-pravega-segmentstore-2/segmentstore.log:2019-10-22 16:37:02,020 26375627 [epollEventLoopGroup-11-7] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=12725988098048] Creating stream segment WireCommands.CreateSegment(type=CREATE_SEGMENT, requestId=12725988098048, segment=Scope3/st1/4.#epoch.0, scaleType=0, targetRate=0, delegationToken=).
oldlogs_pravega-pravega-segmentstore-2/segmentstore.log:2019-10-22 16:37:02,021 26375628 [epollEventLoopGroup-11-6] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=12713103196160] Creating stream segment WireCommands.CreateSegment(type=CREATE_SEGMENT, requestId=12713103196160, segment=Scope3/st1/2.#epoch.0, scaleType=0, targetRate=0, delegationToken=).
```

**Comment by shiveshr** [comment] 2019-11-08 02:59
@andreipaduroiu this also seems to have the problem that we have observed elsewhere, where segment store became unresponsive to a table query for about 5-6 minutes and responded very late. 
During this time, segment stores can be found to be doing other work. 
When the response comes, subsequent steps are performed. However, the logs are only up till the point where we can see a subset of steps performed so we dont know what happened from that point onward.

**Comment by andreipaduroiu** [comment] 2019-11-13 19:05
This was due to an environment issue. Tier 2 read/writes were taking minutes to complete.

**Closed by andreipaduroiu** 2019-11-13 19:05 UTC
