### ISSUE TITLE
Sporadic build failure: `HDFSIntegrationTest::testEndToEnd` fails with `FileNotFoundException`

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2359] opened 2018-03-10 22:24 UTC
**Problem description**

The build fails with the following exception:
```
 java.util.concurrent.CompletionException: io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment 'Segment_0$offset.0'] The StreamSegment does not exist.

        Caused by:
        io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment 'Segment_0$offset.0'] The StreamSegment does not exist.

            Caused by:
            java.io.FileNotFoundException: Segment_0$offset.0
```
**Problem location**
HDFSStorage.java

**Suggestions for an improvement**

**Comment by andreipaduroiu** [comment] 2018-03-13 17:22
duplicate of #1757.

**Closed by andreipaduroiu** 2018-03-13 17:22 UTC
