### ISSUE TITLE
Enable Client Metrics

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#4241] opened 2019-10-03 09:54 UTC
**Problem description**
Enable Client Metrics. The user should be able to specify a `MetricListener` implementation as part of ClientConfig. 

**Problem location**
Client

**Suggestions for an improvement**
Ensure the client does not use EventLoop threads to update the client metrics.

**Comment by andreipaduroiu** [comment] 2019-10-04 15:38
Duplicate of #1723.

**Closed** 2019-10-07 21:11 UTC
Labels: area/client, kind/feature, priority/P2, version/0.6.0
