### ISSUE TITLE
Writer With Default EventWriterConfig Can't Use Transactions

### ISSUE THREAD

**Issue by jdmaguire** [pravega/pravega#2449] opened 2018-04-09 15:27 UTC
**Problem description**

If I create a EventWriter with the default EventWriterConfig, the writer cannot begin a transaction.

`EventStreamWriter::getTxn` will freeze and eventually throw an exception with the message `scaleGracePeriod too large, max value is 30_000`.

I try to set the value to 30_000. Get a similar message. Then I get the exception `lease value too large, max value is 30_000`

Example code:

```kotlin
val clientFactory = ClientFactory.withScope(scopeName, controllerURI)
var writerConfig = EventWriterConfig.builder().build()
var writer = clientFactory.createEventWriter(streamName, SERIALIZER, writerConfig)
var transaction = writer.beginTxn() //blocks, then throws exception
```

**Problem location**

Default inference in EventWriterConfig.

The default value for the scaleGracePeriod is the default value of transactionTimeoutTime, which is 3_600_000. Because of the error message, I set scaleGracePeriod first and saw the second message. Appears that one can "just" set transactionTimeoutTime but the error message doesn't tell me this.

**Suggestions for an improvement**

One or more of the following:
- EventWriterConfig should have better defaults for scaleGracePeriod and transactionTimeoutTime
-  The builder should fail on build() if the scaleGracePeriod is less than the transactionTimeoutTime
- Fail earlier in `EventWriterImpl::beginTxt()`. It takes quiet a while for it to fail
- Improve error messages.
   - The error messages refer to fields that were not touched by the client. If needed to set the fields, the client should be told so. (There is no indication this is a client configuration error and not, say for example, a server-side issue.)
   - It was only because I traced the code that I knew the lease time being referred to is from the transactionTimeoutTime in the EventWriterConfig

**Comment by shiveshr** [comment] 2018-04-27 03:04
duplicate of #2491

**Closed** 2018-04-27 03:04 UTC
Labels: area/autoscaling, area/client, area/controller, area/transaction, kind/bug
