### ISSUE TITLE
Odd exception thrown durring append

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1832] opened 2017-09-01 00:18 UTC
**Problem description**
Durring an append the following is logged:
```
2017-08-27 16:54:51,878 167611099 [segment-store-31] ERROR i.p.s.s.h.handler.AppendProcessor - Error (Segment = 'hulk/smallScale/2015', Operation = 'append')
java.io.EOFException: null
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at io.pravega.segmentstore.server.containers.SegmentState.deserialize(SegmentState.java:80)
	at io.pravega.segmentstore.server.containers.SegmentStateStore.deserialize(SegmentStateStore.java:139)
	at io.pravega.segmentstore.server.containers.SegmentStateStore.lambda$readSegmentState$7(SegmentStateStore.java:122)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)}|
```

**Problem location**
SegmentStateStore

**Suggestions for an improvement**
We need to create a test to repro this.

**Comment by tkaitchuck** [comment] 2017-09-01 01:23
This might actually be the root cause of #1806 . We were able to reproduce it in a loop over and over again in the system test `multireadertxnwriterwithfailovertest`. The relevent log is attached.
[segmentstore_2017-08-31.40.log.txt](https://github.com/pravega/pravega/files/1268899/segmentstore_2017-08-31.40.log.txt)
From the client side we can see that it occurs right away, as soon as AppendSetup is returned.

**Comment by arvindkandhare** [comment] 2017-09-01 13:30
This issue is a duplicate of #1829. Will close this once #1829 is cloed and #1806 is verified.

**Comment by andreipaduroiu** [comment] 2017-09-05 15:12
Duplicate of #1829.

**Closed by andreipaduroiu** 2017-09-05 15:12 UTC
Labels: area/server
