### ISSUE TITLE
Controller processing of create txn is not idempotent

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1797] opened 2017-08-27 09:33 UTC
**Problem description**
In the presence of failover, we have observed a controller receiving a segment already exists error because the segment had already been created previously by a different segment store, see the log lines:

```
logs/6ac7fa6d7b38/segmentstore.log:2017-08-26 19:10:30,811 26481 [segment-store-27] DEBUG i.p.s.s.i.hdfs.FileSystemOperation - Created '/testMultiReaderWriterTxnScope284394575/testMultiReaderWriterTxnStream/4#transaction.4bb53cc2a9a141eda0962af312bb700d_0_18'.
logs/6ac7fa6d7b38/segmentstore.log:2017-08-26 19:10:30,927 26597 [segment-store-27] DEBUG i.p.s.s.i.hdfs.FileSystemOperation - Created '/testMultiReaderWriterTxnScope284394575/testMultiReaderWriterTxnStream/4#transaction.4bb53cc2a9a141eda0962af312bb700d$state_0_18'.

logs/1660454e708b/segmentstore_2017-08-26.1.log:io.pravega.segmentstore.contracts.StreamSegmentExistsException: [Segment 'testMultiReaderWriterTxnScope284394575/testMultiReaderWriterTxnStream/4#transaction.4bb53cc2a9a141eda0962af312bb700d'] The StreamSegment exists already
logs/1660454e708b/segmentstore_2017-08-26.1.log:Caused by: org.apache.hadoop.fs.FileAlreadyExistsException: testMultiReaderWriterTxnScope284394575/testMultiReaderWriterTxnStream/4#transaction.4bb53cc2a9a141eda0962af312bb700d
```

This error is actually being propagated to the writer, which fails the `beginTxn` call:

```
2017-08-26 19:12:12,121 132110 [MultiReaderTxnWriterWithFailoverTest-4] WARN  i.p.t.s.MultiReaderTxnWriterWithFailoverTest - Exception while writing events in the transaction: {}
java.lang.RuntimeException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: INTERNAL: Segment already exists: testMultiReaderWriterTxnScope284394575/testMultiReaderWriterTxnStream/4
    at io.pravega.common.concurrent.FutureHelpers.getAndHandleExceptions(FutureHelpers.java:182)
    at io.pravega.client.stream.impl.EventStreamWriterImpl.beginTxn(EventStreamWriterImpl.java:305)
    at io.pravega.test.system.MultiReaderTxnWriterWithFailoverTest.createTransaction(MultiReaderTxnWriterWithFailoverTest.java:472)
    at io.pravega.test.system.MultiReaderTxnWriterWithFailoverTest.lambda$null$10(MultiReaderTxnWriterWithFailoverTest.java:407)
    at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:194)
    at io.pravega.test.system.MultiReaderTxnWriterWithFailoverTest.lambda$startWritingIntoTxn$14(MultiReaderTxnWriterWithFailoverTest.java:407)
    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```
**Problem location**
Controller.

**Suggestions for an improvement**
Make the processing of requests to create transaction idempotent with respect to creating txn segments.

**Comment by shiveshr** [comment] 2017-08-30 05:59
duplicate of 1802

**Closed** 2017-08-30 05:59 UTC
Labels: area/controller, kind/bug, priority/P0, status/in-progress, version/1
