### ISSUE TITLE
Forcefully deleted pods took around 13 minutes to come back in Running Status.

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#4111] opened 2019-08-16 09:13 UTC
**After forceful pods deletion while IO was running in background, it took 13 minutes of time for them to come back in Running Status. During this time, IO was stalled and by the time pods started running, Readers died(0/1) **

Following command was executed for forceful deletion:
`kubectl delete pods pravega-bookie-0 pravega-pravega-segmentstore-0 pravega-zk-2 pravega-zk-0 --grace-period=0 --force`

During this time IO stalls:
```
INFO  [2019-08-16 08:43:59,150] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:19, KB/sec:15.571289
INFO  [2019-08-16 08:43:59,150] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:19, KB/sec:15.571289
INFO  [2019-08-16 08:43:59,151] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:19, KB/sec:15.625
INFO  [2019-08-16 08:43:59,151] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:19, KB/sec:15.625
INFO  [2019-08-16 08:44:29,151] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:19, KB/sec:15.518555
INFO  [2019-08-16 08:44:29,152] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:19, KB/sec:15.518555
INFO  [2019-08-16 08:44:29,152] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:19, KB/sec:15.518555
INFO  [2019-08-16 08:44:29,152] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:19, KB/sec:15.518555
INFO  [2019-08-16 08:44:59,156] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:19, KB/sec:15.464844
INFO  [2019-08-16 08:44:59,156] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:19, KB/sec:15.464844
INFO  [2019-08-16 08:44:59,156] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:19, KB/sec:15.518555
INFO  [2019-08-16 08:44:59,156] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:19, KB/sec:15.518555
INFO  [2019-08-16 08:45:29,152] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:19, KB/sec:15.412109
INFO  [2019-08-16 08:45:29,152] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:19, KB/sec:15.412109
INFO  [2019-08-16 08:45:29,152] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:19, KB/sec:15.412109
INFO  [2019-08-16 08:45:29,152] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:19, KB/sec:15.412109
INFO  [2019-08-16 08:45:59,152] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:19, KB/sec:15.360352
INFO  [2019-08-16 08:45:59,152] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:19, KB/sec:15.360352
INFO  [2019-08-16 08:45:59,152] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:19, KB/sec:15.412109
INFO  [2019-08-16 08:45:59,152] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:19, KB/sec:15.412109
....
INFO  [2019-08-16 08:46:59,154] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:19, KB/sec:15.308594
INFO  [2019-08-16 08:46:59,154] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:19, KB/sec:15.308594
INFO  [2019-08-16 08:47:29,153] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:19, KB/sec:15.206055
INFO  [2019-08-16 08:47:29,153] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:19, KB/sec:15.206055
INFO  [2019-08-16 08:47:29,153] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:19, KB/sec:15.206055
INFO  [2019-08-16 08:47:29,153] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:19, KB/sec:15.206055
INFO  [2019-08-16 08:47:59,152] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:19, KB/sec:15.155273
INFO  [2019-08-16 08:47:59,152] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:19, KB/sec:15.155273
INFO  [2019-08-16 08:47:59,152] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:19, KB/sec:15.206055
INFO  [2019-08-16 08:47:59,152] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:19, KB/sec:15.206055
INFO  [2019-08-16 08:48:29,152] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:19, KB/sec:15.104492
INFO  [2019-08-16 08:48:29,152] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:19, KB/sec:15.104492
INFO  [2019-08-16 08:48:29,152] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:19, KB/sec:15.104492
INFO  [2019-08-16 08:48:29,152] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:19, KB/sec:15.104492
INFO  [2019-08-16 08:48:59,151] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:18, KB/sec:15.053711
INFO  [2019-08-16 08:48:59,151] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:18, KB/sec:15.053711
INFO  [2019-08-16 08:48:59,152] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:19, KB/sec:15.104492
INFO  [2019-08-16 08:48:59,152] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:19, KB/sec:15.104492
INFO  [2019-08-16 08:49:29,153] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:18, KB/sec:15.003906
INFO  [2019-08-16 08:49:29,153] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:18, KB/sec:15.003906
INFO  [2019-08-16 08:49:29,153] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:18, KB/sec:15.003906
INFO  [2019-08-16 08:49:29,153] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:18, KB/sec:15.003906
INFO  [2019-08-16 08:49:59,151] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:18, KB/sec:14.955078
INFO  [2019-08-16 08:49:59,151] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:18, KB/sec:14.955078
...
INFO  [2019-08-16 08:51:29,151] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:18, KB/sec:14.808594
INFO  [2019-08-16 08:51:29,151] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:18, KB/sec:14.808594
INFO  [2019-08-16 08:51:29,151] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:18, KB/sec:14.808594
INFO  [2019-08-16 08:51:29,151] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:171,191, events/sec:18, KB/sec:14.808594
INFO  [2019-08-16 08:51:59,152] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:18, KB/sec:14.759766
INFO  [2019-08-16 08:51:59,152] io.pravega.longevity.utils.PerformanceUtils: Readers (0/1): events:171,191, events/sec:18, KB/sec:14.759766
INFO  [2019-08-16 08:51:59,152] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:18, KB/sec:14.808594
INFO  [2019-08-16 08:51:59,152] io.pravega.longevity.utils.PerformanceUtils: Readers (0/1): events:171,191, events/sec:18, KB/sec:14.808594
INFO  [2019-08-16 08:52:29,152] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:171,191, events/sec:18, KB/sec:14.711914
```
After `13 minutes` Pods recovered:
```
root@osboxes:/usr/local/go/bin/src/github.com/pravega-longevity# k get po
NAME                                                 READY     STATUS    RESTARTS   AGE
pravega-bookie-0                                     1/1       Running   5          13m
pravega-bookie-1                                     1/1       Running   0          2h
pravega-bookie-2                                     1/1       Running   0          2h
pravega-bookie-3                                     1/1       Running   0          2h
pravega-operator-5fb689474d-j4v27                    1/1       Running   0          2h
pravega-pravega-controller-64cfd5ccfc-pb6gd          1/1       Running   6          2h
pravega-pravega-controller-64cfd5ccfc-sbld4          1/1       Running   6          2h
pravega-pravega-segmentstore-0                       1/1       Running   1          13m
pravega-pravega-segmentstore-1                       1/1       Running   0          2h
pravega-pravega-segmentstore-2                       1/1       Running   0          2h
pravega-zk-0                                         1/1       Running   7          13m
pravega-zk-1                                         1/1       Running   0          3h
pravega-zk-2                                         1/1       Running   7          13m
pravega-zk-3                                         1/1       Running   0          3h
pravega-zk-4                                         1/1       Running   0          3h
shaka-zulu-nfs-client-provisioner-65dcd599b6-cjkzt   1/1       Running   0          2h
zookeeper-operator-7b96d9d548-vzzzs                  1/1       Running   0          3h
```
Following is the Configuration:
```
root@osboxes:/usr/local/go/bin/src/github.com/pravega-longevity# kubectl get po -o jsonpath={...image}|tr -s [[:space:]] "\n"|sort|uniq
devops-repo.isus.emc.com:8116/nautilus/bookkeeper:0.6.0-2333.fed6fd5
devops-repo.isus.emc.com:8116/nautilus/pravega:0.6.0-2333.fed6fd5
pravega/pravega-operator:0.4.2-rc0
pravega/zookeeper:0.2.2
pravega/zookeeper-operator:latest
quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
```
**During this forceful restart, both the `controllers` also restarted**
Uploading pods for the same:
[pravega-k8s-logging-2019-08-16-14-38-28.zip](https://github.com/pravega/pravega/files/3508880/pravega-k8s-logging-2019-08-16-14-38-28.zip)

**Comment by fpj** [comment] 2019-08-20 08:47
Related to #3942

**Comment by fpj** [comment] 2019-08-20 17:21
This is not a Pravega issue unless it requires a change to the Pravega code or confiuguration. Like in the other issue #3942, it was superseded by an operator issue and the same should happen here.

**Comment by sachin-j-joshi** [comment] 2019-08-20 17:51
This is related with  https://github.com/pravega/zookeeper-operator/issues/72 and there is already a PR out for fixing it.

**Comment by fpj** [comment] 2019-08-20 18:50
Good catch, @sachin-j-joshi . One thing I'm wondering is what the expectation is here, how long is acceptable?

**Comment by Tristan1900** [comment] 2019-08-20 19:57
@fpj Raul and I have tested it before using that PR, the zk recovers basically less than 4 minutes. 
@Richa-Srivastava Could you please use the zk image of that PR and test it again? See if there is any improvement. Thank you!

**Comment by Richa-Srivastava** [comment] 2019-08-21 09:21
sure @Tristan1900 I can retest it but I could not find `zk image` details on issue: https://github.com/pravega/zookeeper-operator/issues/72. Can you please share those details.

**Comment by Tristan1900** [comment] 2019-08-21 20:51
@Richa-Srivastava You can either navigate to the PR in that issue and build the zookeeper image or you can use this `tristan1900/zookeeper:reduce-timeout` that I just built and pushed. Thanks

**Comment by fpj** [comment] 2019-08-22 09:05
I'm still confused about this issue, who is setting the expectation on how long is long enough? I don't mean to stop the test with @Tristan1900 's issue, it makes sense to test it, but I don't understand what the target is here.

**Comment by Richa-Srivastava** [comment] 2019-08-22 11:29
@Tristan1900 Thanks for providing details, I'll test this and will update.
@fpj the issue here is not only zk restart is taking long time, but during this much long time in restarting zk, IO is also getting stopped. 
As per expected behavior if redundant pods are there to effectively sustain Pravega operation, IO stall / IO failure should not be observed, If IO stalls it needs to be defined how much time should it be.

**Comment by Richa-Srivastava** [comment] 2019-08-27 08:59
@Tristan1900  following is my pravega-config:
```
root@osboxes:/usr/local/go/bin/src/github.com/raghu/latest/PravegaSanity# kubectl get po -o jsonpath={...image}|tr -s [[:space:]] "\n"|sort|uniq
devops-repo.isus.emc.com:8116/nautilus/bookkeeper:0.6.0-2345.298015f
devops-repo.isus.emc.com:8116/nautilus/pravega:0.6.0-2345.298015f
grafana/grafana
grafana/grafana:latest
influxdb:latest
openjdk:8
pravega/pravega-operator:0.4.2-rc0
pravega/zookeeper-operator:0.2.2
quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
tristan1900/zookeeper:reduce-timeout
```
@sachin-j-joshi @Tristan1900 @fpj here is my observation:
**It took  around 9 minutes this time for pods to come up, both the controllers restarted again and by the time pods came up, we lost readers:**
```
INFO  [2019-08-27 08:33:19,486] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:77,701, events/sec:24, KB/sec:18.557617
INFO  [2019-08-27 08:33:19,486] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:77,701, events/sec:24, KB/sec:18.557617
INFO  [2019-08-27 08:33:19,486] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:77,701, events/sec:24, KB/sec:18.732422
...
INFO  [2019-08-27 08:34:49,486] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:77,701, events/sec:23, KB/sec:18.051758
INFO  [2019-08-27 08:34:49,486] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:77,701, events/sec:23, KB/sec:18.051758
INFO  [2019-08-27 08:34:49,487] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:77,701, events/sec:23, KB/sec:18.051758
INFO  [2019-08-27 08:35:19,485] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:77,701, events/sec:23, KB/sec:17.888672
INFO  [2019-08-27 08:35:19,485] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:77,701, events/sec:23, KB/sec:17.888672
INFO  [2019-08-27 08:35:19,485] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:77,701, events/sec:23, KB/sec:18.051758
INFO  [2019-08-27 08:35:19,485] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:77,701, events/sec:23, KB/sec:18.051758
INFO  [2019-08-27 08:35:49,488] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:77,701, events/sec:23, KB/sec:17.729492
...
...
INFO  [2019-08-27 08:41:19,486] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:77,701, events/sec:21, KB/sec:16.27539
INFO  [2019-08-27 08:41:49,486] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:77,701, events/sec:20, KB/sec:16.013672
INFO  [2019-08-27 08:41:49,486] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:77,701, events/sec:20, KB/sec:16.013672
INFO  [2019-08-27 08:41:49,486] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:77,701, events/sec:20, KB/sec:16.013672
INFO  [2019-08-27 08:41:49,486] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:77,701, events/sec:20, KB/sec:16.013672
INFO  [2019-08-27 08:42:19,486] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:77,702, events/sec:20, KB/sec:15.885742
INFO  [2019-08-27 08:42:19,486] io.pravega.longevity.utils.PerformanceUtils: Readers (0/1): events:77,701, events/sec:20, KB/sec:15.884766
INFO  [2019-08-27 08:42:19,486] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:77,702, events/sec:20, KB/sec:16.013672
INFO  [2019-08-27 08:42:19,486] io.pravega.longevity.utils.PerformanceUtils: Readers (0/1): events:77,701, events/sec:20, KB/sec:16.013672
```

**Comment by Richa-Srivastava** [comment] 2019-08-27 09:03
Uploading k8 logs for the above verification:
[pravega-k8s-logging-2019-08-27-14-30-56.zip](https://github.com/pravega/pravega/files/3545201/pravega-k8s-logging-2019-08-27-14-30-56.zip)

**Comment by RaulGracia** [comment] 2019-09-02 09:37
As @fpj noted, this issue is just one case of the general issue described in https://github.com/pravega/zookeeper-operator/issues/72. Also, as @sachin-j-joshi pointed out, @Tristan1900 created some time back a partial mitigation for this problem in PR https://github.com/pravega/zookeeper-operator/pull/73. But note that this does not seem to be a complete solution to the problem.

According to prior experiments, this looks as an environment problem that only manifests in PKS. In GKE, executing the same failure scenario, Pravega recovers within 1-2 minutes. This may answer the previous question of @fpj regarding the expectation for recovery time: 1-2 minutes seems a reasonable time frame for a Zookeeper pod to recover, and it is fast enough to prevent most Controller restarts and reader timeouts, so IO can continue as normal.

**Comment by Tristan1900** [comment] 2019-09-20 20:36
@Raghuveera-Rao Did you try with PKS 1.4 or PKS 1.5? I just did this experiment on AWS PKS 1.5 and the issue is gone. I have forcefully deleted `zk-0`(leader) and `zk-2` out of 5 zk nodes, those 2 comes back up with 90 seconds while the workload runs smoothly. 
If you are using PKS 1.4, there are two variables here which are AWS and PKS 1.5, so it would be great if you could try PKS 1.5(if available) on any of our internal clusters(not on AWS). Thanks!

**Comment by Richa-Srivastava** [comment] 2019-09-24 06:08
@Tristan1900 I tried with PKS 1.4. Now I've upgraded PKS to 1.5 :
```
root@osboxes:/home/osboxes# pks --version

PKS CLI version: 1.5.0-build.291

```
I can verify this with PKS 1.5 now. Please let me know the `zk image` to be used.

**Comment by Tristan1900** [comment] 2019-09-25 23:12
@Richa-Srivastava Thanks a lot. Any zk image should be fine. Perhaps just try with the image that you used when you found this issue.

**Comment by Ranjan-Padhi** [comment] 2019-11-11 10:40
verified with given new zookeeper release `zookeeper:0.2.2-92.fb0a2c4` and `zookeeper:0.2.2-92.fb0a2c4` and here is the observation

Issue is still reproduce with new zookeeper release,

verified multiple time and every time all the pods are restarted successfully within 1-2 mins but all reader and writer moved to inactive state ( 0 records Reading and  0 records writing)

After verify multiple scenario, we observed issue is not for zookeeper restart, its issue for segmentstore restart because same issue observed while deleting forcefully only segmentstore

kubectl delete pods pravega-pravega-segmentstore-0 --grace-period=0 --force

**Comment by RaulGracia** [comment] 2020-04-14 09:58
@Richa-Srivastava @Ranjan-Padhi is this still an issue or we can close it?

**Comment by RaulGracia** [comment] 2020-04-28 10:22
Closing, please @Richa-Srivastava reopen the issue if it resurfaces.

**Closed by RaulGracia** 2020-04-28 10:22 UTC
Labels: kind/bug, priority/P1, version/0.6.0
