### ISSUE TITLE
Bookies restart and pravega controller dies

### ISSUE THREAD

**Issue by fonfrygin** [pravega/pravega#5404] opened 2020-12-06 17:18 UTC
**Problem description**
Using Mongoose a performance test for Pravega is run. After a few operations Bookies start to restart and then the pravega controller dies. 

```
[root@node1 ~]# kubectl get pods -A
NAMESPACE      NAME                                              READY   STATUS      RESTARTS   AGE
cert-manager   cert-manager-86548b886-wl97d                      1/1     Running     0          51m
cert-manager   cert-manager-cainjector-6d59c8d4f7-2n462          1/1     Running     0          51m
cert-manager   cert-manager-webhook-578954cdd-7827t              1/1     Running     0          51m
default        bookkeeper-bookie-0                               1/1     Running     0          49m
default        bookkeeper-bookie-1                               1/1     Running     0          49m
default        bookkeeper-bookie-2                               1/1     Running     0          49m
default        bookkeeper-operator-6765984998-55m6x              1/1     Running     0          50m
default        pravega-operator-68fdd99544-7rtvm                 1/1     Running     0          46m
default        pravega-pravega-controller-844f596b5d-g46g9       0/1     Running     0          44m
default        pravega-pravega-segment-store-0                   1/1     Running     0          44m
default        zoo-0                                             1/1     Running     0          53m
default        zoo-1                                             1/1     Running     0          52m
default        zoo-2                                             1/1     Running     0          51m
default        zookeeper-operator-7f8b747bcd-87r57               1/1     Running     0          53m
```

```
[root@node1 ~]# kubectl describe pod bookkeeper-bookie-1
Name:         bookkeeper-bookie-1
Namespace:    default
Priority:     0
Node:         node2/10.228.0.16
Start Time:   Sat, 05 Dec 2020 14:16:27 -0500
Labels:       app=bookkeeper-cluster
              bookkeeper_cluster=bookkeeper
              component=bookie
              controller-revision-hash=bookkeeper-bookie-7bc66cb4c9
              statefulset.kubernetes.io/pod-name=bookkeeper-bookie-1
Annotations:  bookkeeper.version: 0.7.0
              cni.projectcalico.org/podIP: 10.233.96.27/32
              cni.projectcalico.org/podIPs: 10.233.96.27/32
Status:       Running
IP:           10.233.96.27
IPs:
  IP:           10.233.96.27
Controlled By:  StatefulSet/bookkeeper-bookie
Containers:
  bookie:
    Container ID:   docker://743444438fb2dffcf98b4f1a14679653d0028336e4b2253bf3b4fb6727fe0977
    Image:          pravega/bookkeeper:0.7.0
    Image ID:       docker-pullable://pravega/bookkeeper@sha256:fb90d52473e5f070a93de83a3a021b53fbcdb002e2e29ce2fdf594f6d0f550b5
    Port:           3181/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Sat, 05 Dec 2020 14:17:17 -0500
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  4Gi
    Requests:
      cpu:      1
      memory:   4Gi
    Liveness:   exec [/bin/sh -c netstat -ltn 2> /dev/null | grep 3181 || ss -ltn 2> /dev/null | grep 3181] delay=60s timeout=5s period=15s #success=1 #failure=4
    Readiness:  exec [/bin/sh -c /opt/bookkeeper/bin/bookkeeper shell bookiesanity] delay=20s timeout=5s period=10s #success=1 #failure=9
    Environment Variables from:
      bookkeeper-bookie  ConfigMap  Optional: false
      bk-config-map      ConfigMap  Optional: false
    Environment:         <none>
    Mounts:
      /bk/index from index (rw)
      /bk/journal from journal (rw)
      /bk/ledgers from ledger (rw)
      /tmp/dumpfile/heap from heap-dump (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-n9rdw (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  journal:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  journal-bookkeeper-bookie-1
    ReadOnly:   false
  ledger:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  ledger-bookkeeper-bookie-1
    ReadOnly:   false
  index:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  index-bookkeeper-bookie-1
    ReadOnly:   false
  heap-dump:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-token-n9rdw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-n9rdw
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age   From                     Message
  ----     ------                  ----  ----                     -------
  Warning  FailedScheduling        44m   default-scheduler        0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling        44m   default-scheduler        0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled               44m   default-scheduler        Successfully assigned default/bookkeeper-bookie-1 to node2
  Normal   SuccessfulAttachVolume  44m   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-5db2d6cb-6add-458c-a177-9277663ade95"
  Normal   SuccessfulAttachVolume  44m   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-63845216-122d-41ea-9944-613a5ad35673"
  Normal   SuccessfulAttachVolume  44m   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-f38d5551-80ed-44c1-a055-c9c38bde9f56"
  Normal   Pulling                 44m   kubelet                  Pulling image "pravega/bookkeeper:0.7.0"
  Normal   Pulled                  43m   kubelet                  Successfully pulled image "pravega/bookkeeper:0.7.0" in 29.041102956s
  Normal   Created                 43m   kubelet                  Created container bookie
  Normal   Started                 43m   kubelet                  Started container bookie
  Warning  Unhealthy               29m   kubelet                  Readiness probe failed: 19:31:55,066 INFO  Created ledger 228
19:31:56,632 ERROR UpdateLoop(ledgerId=228,loopId=07c8a234) Exception updating
org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: Not enough non-faulty bookies available
  at org.apache.bookkeeper.bookie.LocalBookieEnsemblePlacementPolicy.replaceBookie(LocalBookieEnsemblePlacementPolicy.java:87)
  at org.apache.bookkeeper.client.BookieWatcherImpl.replaceBookie(BookieWatcherImpl.java:295)
  at org.apache.bookkeeper.client.EnsembleUtils.replaceBookiesInEnsemble(EnsembleUtils.java:71)
  at org.apache.bookkeeper.client.LedgerHandle.lambda$ensembleChangeLoop$2(LedgerHandle.java:1908)
  at org.apache.bookkeeper.client.MetadataUpdateLoop.writeLoop(MetadataUpdateLoop.java:122)
  at org.apache.bookkeeper.client.MetadataUpdateLoop.run(MetadataUpdateLoop.java:111)
  at org.apache.bookkeeper.client.LedgerHandle.ensembleChangeLoop(LedgerHandle.java:1927)
  at org.apache.bookkeeper.client.LedgerHandle.handleBookieFailure(LedgerHandle.java:1876)
  at org.apache.bookkeeper.client.PendingAddOp.writeComplete(PendingAddOp.java:360)
  at org.apache.bookkeeper.proto.PerChannelBookieClient$AddCompletion.writeComplete(PerChannelBookieClient.java:2028)
  at org.apache.bookkeeper.proto.PerChannelBookieClient$AddCompletion.lambda$errorOut$0(PerChannelBookieClient.java:2051)
  at org.apache.bookkeeper.proto.PerChannelBookieClient$CompletionValue$1.safeRun(PerChannelBookieClient.java:1606)
  at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.lang.Thread.run(Thread.java:748)
19:31:56,636 ERROR Closing ledger 228 due to NotEnoughBookiesException: Not enough non-faulty bookies available
19:31:56,639 ERROR Write of ledger entry to quorum failed: L228 E0
19:31:56,640 WARN  Error in bookie sanity test
org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: Not enough non-faulty bookies available
  at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:83)
  at org.apache.bookkeeper.client.SyncCallbackUtils$SyncAddCallback.addComplete(SyncCallbackUtils.java:251)
  at org.apache.bookkeeper.client.AsyncCallback$AddCallback.addCompleteWithLatency(AsyncCallback.java:91)
  at org.apache.bookkeeper.client.PendingAddOp.submitCallback(PendingAddOp.java:390)
  at org.apache.bookkeeper.client.LedgerHandle.errorOutPendingAdds(LedgerHandle.java:1772)
  at org.apache.bookkeeper.client.LedgerHandle$5.safeRun(LedgerHandle.java:572)
  at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.lang.Thread.run(Thread.java:748)
19:31:56,811 ERROR UpdateLoop(ledgerId=228,loopId=3cb0aa13) Error writing metadata to store
org.apache.bookkeeper.client.BKException$BKNoSuchLedgerExistsException: No such ledger exists
  at org.apache.bookkeeper.meta.AbstractZkLedgerManager$4.processResult(AbstractZkLedgerManager.java:453)
  at org.apache.bookkeeper.zookeeper.ZooKeeperClient$22$1.processResult(ZooKeeperClient.java:1091)
  at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:566)
  at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:508)
19:31:57,032 INFO  Deleted ledger 228
```

Bookie logs: [bookie-1.log](https://github.com/pravega/pravega/files/5647825/bookie-1.log)
Pravega controller logs: [pravega-controller.log](https://github.com/pravega/pravega/files/5647830/pravega-controller.log)

For Pravega these limits were used: https://github.com/pravega/pravega-operator/blob/f48e3e6f15296e44f152686ba7703ea7d80f21c6/charts/pravega/values/small.yaml
For Bookkeeper these limits were used: https://github.com/pravega/bookkeeper-operator/blob/674a50779e4cdde87624aeb095b701db119d5c06/charts/bookkeeper/values/small.yaml
Also for Bookkeeper these limits were tried, but the result was the same: https://github.com/pravega/bookkeeper-operator/blob/674a50779e4cdde87624aeb095b701db119d5c06/charts/bookkeeper/values/medium.yaml

```
1 master node (8 CPU, 16 GB Ram)
2 worker nodes (8 CPU, 16 GB Ram)
```
What limits should be set for stable operation?

**Comment by RaulGracia** [comment] 2020-12-06 19:15
@fonfrygin the Bookie crashed because of this problem:
```
2020-12-05 19:39:02,093 - ERROR - [bookie-io-1-1:BookieRequestHandler@70] - Unhandled exception occurred in I/O thread or handler
java.lang.IllegalStateException: Received unknown request op code = 82
	at org.apache.bookkeeper.proto.BookieProtoEncoding$RequestEnDeCoderPreV3.decode(BookieProtoEncoding.java:194)
...
2020-12-05 19:39:02,095 - ERROR - [bookie-io-1-1:BookieRequestHandler@70] - Unhandled exception occurred in I/O thread or handler
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 5242880: 1289119803 - discarded
```
This may leave Bookies in a bad state. This seems to be a Bookkeeper client problem that we have been investigating: https://github.com/apache/bookkeeper/issues/2497
Currently, one promising approach to solve this problem is to upgrade Bookkeeper to a newer version, which appears to have a fix for that: https://github.com/pravega/pravega/pull/5386
As it seems that the problem reproduces rapidly in your setup, could you please try the same experiment with the PR above? If we do not see the `TooLongFrameException` again, it may help to validate the current fix for this problem.

In addition to that, it looks like the Controller lost connectivity with Zookeeper for a while, which would induce its internal restart. But this seems to be a different issue altogether.

**Comment by fonfrygin** [comment] 2020-12-07 11:33
So, to deploy Pravega on Kubernetes, I use the bookkeeper-operator from here: https://github.com/pravega/bookkeeper-operator/tree/master/deploy. 
How can I use the newer version of Bookkeeper to fix this problem? Or are there other ways to deploy Pravega on Kubernetes?

**Comment by RaulGracia** [comment] 2020-12-07 14:27
@fonfrygin instead of using `master` branch, you need to use the branch on the above PR: https://github.com/RaulGracia/pravega/tree/issue-5385-upgrade-bk-version
Also, when using Bookkeeper Operator (v0.1.3), add `-XX:+IgnoreUnrecognizedVMOptions`in the Bookkeeper JVM Options section of the manifest, to avoid problem with JDK11 and the default JVM options of the operator.
Please, let us know if the problem reproduces when using that branch.

**Closed** 2021-11-01 23:44 UTC
