### ISSUE TITLE
System test failures since the readers were not able to read all events.

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#3638] opened 2019-04-16 16:15 UTC
**Problem description**

Observing that a we can recieve empty `SEGMENT_READ`. (my understanding was that SSS responds only when there is data)
```2019-04-11 02:47:31,330 1349655 [epollEventLoopGroup-4-2] TRACE i.p.s.protocol.netty.CommandDecoder - Decode a message on connection: 10.200.90.219/10.200.90.219:12345. Message was WireCommands.SegmentRead(type=SEGMENT_READ, segment=testReadWriteAndScaleScope1144952233/testReadWriteAndScaleStream/2.#epoch.1, offset=223630, atTail=true, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=0 cap=0], requestId=304942678016)```

**Problem location**
Client / Test file.

**Suggestions for an improvement**
Needs to be investigated.

**Comment by shrids** [comment] 2019-04-25 07:09
Closing this issue since this has been fixed as part of PR: https://github.com/pravega/pravega/pull/3639

**Comment by shrids** [comment] 2019-04-30 03:16
reopening the issue as it was observed again.

**Comment by shrids** [comment] 2019-04-30 03:21
The system test failure was root caused to repeated connection failures. 
Details:
- The reader were not able to read all the events since the connection to Segmentstore is failing
```2019-04-25 13:35:26,569 797688 [clientInternal-1] ERROR i.p.c.s.i.AsyncSegmentInputStreamImpl - Error while sending request WireCommands.ReadSegment(type=READ_SEGMENT, segment=testReadWriteAndScaleScope1839109582/_RGtestReadWriteAndScaleReaderGroup1345371180/0.#epoch.0, offset=2115, suggestedLength=1048576, delegationToken=, requestId=111669149696)
io.pravega.shared.protocol.netty.ConnectionFailedException: Connection to 10.200.90.138 is not established.
        at io.pravega.client.netty.impl.FlowHandler.getChannel(FlowHandler.java:122)
        at io.pravega.client.netty.impl.ClientConnectionImpl.sendAsync(ClientConnectionImpl.java:69)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.sendRequestOverConnection(AsyncSegmentInputStreamImpl.java:202)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.lambda$null$2(AsyncSegmentInputStreamImpl.java:188)```

Detailed logs: 
[readwriteandscalewithfailovertest-e2nsg-1.zip](https://github.com/pravega/pravega/files/3129855/readwriteandscalewithfailovertest-e2nsg-1.zip)

**Comment by shrids** [comment] 2019-05-22 16:02
Closing the issue due to the following reasons: 
* PR 3654 ensures we close the connection in case of a ConnectionFailedException and try to re-establish the connection. (This will ensure we avoid a scenario where AsyncSegmentInputStream needs to retry until the `replyProcessor.connectionDropped()` is invoked by the FlowHandler)
* Without the SegmentStore/PRP logs it is not possible to root cause why the repeated connection attempts are failing for the reader. 
* We are not observing this issue in the system test runs for the last 15 days

We should reopen this issue if we observe it again.

**Closed by shrids** 2019-05-22 16:02 UTC
