### ISSUE TITLE
Segment store or bookkeeper being restarted under load

### ISSUE THREAD

**Issue by kevinhan88** [pravega/pravega#4009] opened 2019-07-08 22:49 UTC
**Problem description**
Nautilus test based on Pravega Benchmark observed SS or BK restarted under load, with pravega version 0.5.0-2284.8c6c176.

Quotation from nautilus testing report:
"Our test suite is based on Pravega Benchmark. I've attached the shell script that starts the test. 
We are executing the script a few time to get the consistent performance measurement. However, either the cluster's bookkeepers or segment stores died and being restarted consistently.
The cluster is dand7 on Enki. It's running weekly build 499. "

**Problem location**
Segmentstore or Bookkeeper.
To reproduce:
1. Install weekly build 499 
2. Create 10 pravega benchmak pods (see attached yaml) 
3. Execute the attached shell script (see attached shell script) 
4. Observed segment stores or bookkeepers being restarted

Supporting materials for troubleshooting:
1. The test env is dand7 on Enki. pravega.yaml and testcase-3.sh are attached. 
2. Logs files will be posted here once they are available.
3. System dumps are also being requested (but may not eventually available)

**Suggestions for an improvement**
Not available for now.

**Comment by kevinhan88** [comment] 2019-07-08 23:23
Yaml and script attached here:
[bmrk-pravega-yaml.txt](https://github.com/pravega/pravega/files/3370527/bmrk-pravega-yaml.txt)
[testcase-3-sh.txt](https://github.com/pravega/pravega/files/3370528/testcase-3-sh.txt)

**Comment by andreipaduroiu** [comment] 2019-07-08 23:28
Do you have logs?

**Comment by kevinhan88** [comment] 2019-07-08 23:30
Logs (and even head dumps) are being requested from the reporter.

**Comment by RaulGracia** [comment] 2019-07-09 06:22
@kevinhan88 @andreipaduroiu Issue #4008 may be related to this issue, as it is already reporting problems for Bookkeeper storage reclamation (garbage collection) to keep up with a moderate workload executed from 4 pods. I imagine that 10 benchmark processes will induce an even higher load that will lead to at least the same issue even faster. We are experimenting with more aggressive Bookkeeper GC parameters to avoid problems under high IO loads.

**Comment by sumit-bm** [comment] 2019-07-09 07:33
@kevinhan88 @andreipaduroiu @RaulGracia @fpj I think this is dup of #3987

**Comment by RaulGracia** [comment] 2019-07-09 07:47
@sumit-bm do you have the logs? #3987 is a direct memory error that is handled by Bookkeeper and does not block IO. This issue seems to be different, but it will be better to have the logs to check.

**Comment by fpj** [comment] 2019-07-09 09:59
This is a duplicate of #3987 .

**Closed by fpj** 2019-07-09 09:59 UTC
Labels: area/bookkeeper, area/segmentstore, kind/bug, priority/P1, status/more-info-needed, version/0.5.0
