### ISSUE TITLE
Scaling stopped on dynamic stream

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#2657] opened 2018-06-04 20:02 UTC
**Problem description**
On a stream with dynamic scaling, the scaling stopped after some time:
![namor smallscaleyoung no_scaling](https://user-images.githubusercontent.com/25368596/40938550-8c3c3452-6818-11e8-9a2b-9ad7c47c609a.png)

[controller.stdout.namor.stopped_scaling.log](https://github.com/pravega/pravega/files/2069792/controller.stdout.namor.stopped_scaling.log)

The controller logs have repeating errors  of the following kind:
```
2018-06-04 18:33:12,893 21334802 [controllerpool-55] WARN  i.p.c.s.e.r.ScaleOperationTask - processing scale request for hulk/smallScaleYoung segments [117] failed {}
io.pravega.controller.store.stream.StoreException$OperationNotAllowedException: Stream: smallScaleYoung State: SCALING
	at io.pravega.controller.store.stream.StoreException.create(StoreException.java:102)
	at io.pravega.controller.store.stream.StoreException.create(StoreException.java:70)
	at io.pravega.controller.store.stream.PersistentStreamBase.lambda$updateState$30(PersistentStreamBase.java:269)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.pravega.controller.store.stream.ZKStoreHelper.lambda$null$8(ZKStoreHelper.java:156)
	at io.pravega.controller.store.stream.ZKStoreHelper.lambda$callback$24(ZKStoreHelper.java:326)
	at org.apache.curator.framework.imps.Backgrounding$1$1.run(Backgrounding.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2018-06-04 18:33:12,903 21334812 [epollEventLoopGroup-2-12] INFO  i.p.c.t.Stream.StreamMetadataTasks - event posted successfully
2018-06-04 18:33:12,903 21334812 [controllerpool-45] WARN  i.p.c.e.i.ConcurrentEventProcessor - ConcurrentEventProcessor Processing failed java.util.concurrent.CompletionException
2018-06-04 18:33:12,903 21334812 [controllerpool-45] ERROR i.p.c.e.i.ConcurrentEventProcessor - ConcurrentEventProcessor Processing failed, exiting {}
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$OperationNotAllowedException: Stream: smallScaleYoung State: SCALING
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:899)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.pravega.controller.eventProcessor.impl.SerializedRequestHandler.lambda$run$1(SerializedRequestHandler.java:94)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.pravega.controller.server.eventProcessor.requesthandlers.StreamRequestHandler.lambda$null$4(StreamRequestHandler.java:129)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.pravega.controller.task.Stream.StreamMetadataTasks.lambda$writeEvent$51(StreamMetadataTasks.java:545)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl$ResponseProcessor.ackUpTo(SegmentOutputStreamImpl.java:385)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl$ResponseProcessor.dataAppended(SegmentOutputStreamImpl.java:345)
	at io.pravega.shared.protocol.netty.WireCommands$DataAppended.process(WireCommands.java:631)
	at io.pravega.shared.protocol.netty.ReplyProcessor.process(ReplyProcessor.java:20)
	at io.pravega.client.netty.impl.ClientConnectionInboundHandler.channelRead(ClientConnectionInboundHandler.java:98)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:797)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.controller.store.stream.StoreException$OperationNotAllowedException: Stream: smallScaleYoung State: SCALING
	at io.pravega.controller.store.stream.StoreException.create(StoreException.java:102)
	at io.pravega.controller.store.stream.StoreException.create(StoreException.java:70)
	at io.pravega.controller.store.stream.PersistentStreamBase.lambda$updateState$30(PersistentStreamBase.java:269)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.pravega.controller.store.stream.ZKStoreHelper.lambda$null$8(ZKStoreHelper.java:156)
	at io.pravega.controller.store.stream.ZKStoreHelper.lambda$callback$24(ZKStoreHelper.java:326)
	at org.apache.curator.framework.imps.Backgrounding$1$1.run(Backgrounding.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 common frames omitted
```

**Problem location**
Controller

**Suggestions for an improvement**
Dynamic scaling should work

**Comment by jkhalack** [comment] 2018-06-04 20:06
Seen on the following commit of the code: https://github.com/pravega/pravega/commit/6de4965871fd6b1767e0114b1a4768a9896f01cf

**Comment by shiveshr** [comment] 2018-06-06 14:57
Can you please share controller logs. 
The snippet posted is "harmless" and not the cause. 
The way scale works is, if a scale is ongoing, other attempts to scale get ScaleConflict. 
So the reason other scales are stalled is because there is some ongoing scale which hasnt completed in a while. 
We need to look at the entire logs to see which scale is ongoing and why it is not completing. 
A common cause could be some error on segment store while attempting to either create new segments or seal old segments. 
So please share controller and segment store logs.

**Comment by shiveshr** [comment] 2018-06-06 15:56
One thing i can see in controller logs is that trying to scale segment 117 is constantly failing as it is not able to change the state of the stream to `SCALING`.
This can happen if there is a background operation going on. The only background processing that can happen is truncation and one explanation is that it failed without resetting the state from `TRUNCATING` back to `ACTIVE`. 
I would like to see more controller logs so that i can figure out what happened. The logs shared are not complete.

**Comment by shiveshr** [comment] 2018-06-06 16:03
The cause could be following #2670. This is an issue in the code and I will send out a fix for this soon. To be sure this is what must have caused the problem i will need all of controller logs.

**Comment by jkhalack** [comment] 2018-06-06 16:06
The only part of the controller logs that I have saved is attached above.
Unfortunately, I don't have any parts of the segment store logs saved (only a part of the client logs).
The cluster was destroyed two days ago.

**Comment by jkhalack** [comment] 2018-06-06 16:07
[namor.smallScaleYoung.controller_server_2018-06-04.14.log](https://github.com/pravega/pravega/files/2077104/namor.smallScaleYoung.controller_server_2018-06-04.14.log)

**Comment by jkhalack** [comment] 2018-06-06 17:50
These are the logs from another failure.
The scaling stopped on stream `smallScaleSlow` (the last one happened at about 15:50 log time, so there should be next one at 16:00 or so).
This was a two-controller setup.
One controller:
[pravega-pravega_controller--917328ec-94e0-459a-bd7d-41204bbc427c.txt](https://github.com/pravega/pravega/files/2077411/pravega-pravega_controller--917328ec-94e0-459a-bd7d-41204bbc427c.txt)
Another controller:
[pravega-pravega_controller-p1-fa51f0e4-8510-4dc4-8abe-d41563f0c703.txt](https://github.com/pravega/pravega/files/2077491/pravega-pravega_controller-p1-fa51f0e4-8510-4dc4-8abe-d41563f0c703.txt)
[pravega-pravega_controller-p2-fa51f0e4-8510-4dc4-8abe-d41563f0c703.txt](https://github.com/pravega/pravega/files/2077495/pravega-pravega_controller-p2-fa51f0e4-8510-4dc4-8abe-d41563f0c703.txt)
[pravega-pravega_controller-p3-fa51f0e4-8510-4dc4-8abe-d41563f0c703.txt](https://github.com/pravega/pravega/files/2077510/pravega-pravega_controller-p3-fa51f0e4-8510-4dc4-8abe-d41563f0c703.txt)
[pravega-pravega_controller-p4-fa51f0e4-8510-4dc4-8abe-d41563f0c703.txt](https://github.com/pravega/pravega/files/2077511/pravega-pravega_controller-p4-fa51f0e4-8510-4dc4-8abe-d41563f0c703.txt)

And there were three segment stores:
[pravega-pravega_segmentstore--861f7c34-f887-4aac-b12f-e3e576db9b02.txt](https://github.com/pravega/pravega/files/2077512/pravega-pravega_segmentstore--861f7c34-f887-4aac-b12f-e3e576db9b02.txt)
[pravega-pravega_segmentstore--ba07b3ff-b20f-43f7-b6da-f6edca9e3402.txt](https://github.com/pravega/pravega/files/2077514/pravega-pravega_segmentstore--ba07b3ff-b20f-43f7-b6da-f6edca9e3402.txt)
[pravega-pravega_segmentstore--e9ceb1fd-969f-42f8-8a3f-2588e6b6def9.txt](https://github.com/pravega/pravega/files/2077515/pravega-pravega_segmentstore--e9ceb1fd-969f-42f8-8a3f-2588e6b6def9.txt)

**Comment by shiveshr** [comment] 2018-06-07 01:58
here is what i can see from the logs:
1. at 15:54 truncate stream runs and it truncates some segments and then deletes some segments. Some failure occurs here and this processing fails leaving the state truncating. 
It is a retryable failure and event is posted back in the `requeststream` successfully. Unfortunately we have not logged the complete exception for failure and all we see is the wrapper exception CompletionException. I will improve the logging here. 
2. next event for this stream is picked up soon after at 15:54 which happens to be a "scale" request. 
(this scale request is for segment 62). 
This attempts to start the scale operation and successfully creates a metadata barrier so that no other scale can run. 
Post this it attempts to set the state to SCALING. This obviously fails because a truncation is ongoing and not completed. This fails with "OperationNotAllowed" and the event is duly posted back in the `requeststream`. 
3. Other scale events (for segments other than 62) are picked and they fail in attempting to create scale metadata barrier and fail with `ScaleConflict`.
4. event for scale 62 is picked up again and continues to fail with OperationNotAllowed exception. 

The mystery to be solved is why hasnt the transaction event that was reposted being picked up again.
I am still trying to work that part out. But it seems unrelated to #2670 at the moment.

**Comment by shiveshr** [comment] 2018-06-07 02:42
@andreipaduroiu 
delete stream segment keeps failing on segment store with NPE.

```pravega/pravega_segmentstore  STDOUT 2018-06-06 15:46:51,914 5378620 [epollEventLoopGroup-3-16] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection:
pravega/pravega_segmentstore  STDOUT java.lang.NullPointerException: null
pravega/pravega_segmentstore  STDOUT    at io.pravega.segmentstore.server.containers.StreamSegmentContainer.deleteStreamSegment(StreamSegmentContainer.java:404)
pravega/pravega_segmentstore  STDOUT    at io.pravega.segmentstore.server.store.StreamSegmentService.lambda$deleteStreamSegment$9(StreamSegmentService.java:136)
pravega/pravega_segmentstore  STDOUT    at io.pravega.segmentstore.server.store.StreamSegmentService.invoke(StreamSegmentService.java:174)
pravega/pravega_segmentstore  STDOUT    at io.pravega.segmentstore.server.store.StreamSegmentService.deleteStreamSegment(StreamSegmentService.java:134)
pravega/pravega_segmentstore  STDOUT    at io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor.deleteSegment(PravegaRequestProcessor.java:602)
pravega/pravega_segmentstore  STDOUT    at io.pravega.shared.protocol.netty.DelegatingRequestProcessor.deleteSegment(DelegatingRequestProcessor.java:109)
pravega/pravega_segmentstore  STDOUT    at io.pravega.shared.protocol.netty.WireCommands$DeleteSegment.process(WireCommands.java:1446)
pravega/pravega_segmentstore  STDOUT    at io.pravega.segmentstore.server.host.handler.ServerConnectionInboundHandler.channelRead(ServerConnectionInboundHandler.java:46)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
pravega/pravega_segmentstore  STDOUT    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
pravega/pravega_segmentstore  STDOUT    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
pravega/pravega_segmentstore  STDOUT    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
pravega/pravega_segmentstore  STDOUT    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
pravega/pravega_segmentstore  STDOUT    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
pravega/pravega_segmentstore  STDOUT    at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
pravega/pravega_segmentstore  STDOUT    at io.netty.channe
pravega/pravega_segmentstore  STDOUT l.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
pravega/pravega_segmentstore  STDOUT    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:797)
```

**Comment by andreipaduroiu** [comment] 2018-06-07 03:18
I fixed that 2 days ago. Please update to latest master.

**Closed** 2018-06-15 03:47 UTC
