### ISSUE TITLE
IO Read operation failed after deleting 2 segment store pods simultaneously

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#3663] opened 2019-04-22 09:06 UTC
**Problem description**
I started long term IO operation with following configurations:

`IO workload (Total - 4 readers, 3 writers, 120 events/sec, ~ 100 KB/sec IO)`
While Read and Write operations were in-progress, deleted 2 Segment store pods out of 3. The pods restarted immediately but IO Read operation failed.

After Segment store  restart, following are the exceptions in IO client:

```
INFO  [2019-04-18 10:42:06,225] io.pravega.longevity.testmanager.manager.TestPerformanceCollector: Received Error From task taskID : io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: Connection to 172.24.2.15 is not established.
java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: Connection to 172.24.2.15 is not established.
        at java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
        at java.util.concurrent.CompletableFuture.join(Unknown Source)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.handleRequest(SegmentInputStreamImpl.java:137)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.read(SegmentInputStreamImpl.java:122)
        at io.pravega.client.segment.impl.EventSegmentReaderImpl.readEvent(EventSegmentReaderImpl.java:75)
        at io.pravega.client.segment.impl.EventSegmentReaderImpl.read(EventSegmentReaderImpl.java:62)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:115)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:88)
        at io.pravega.longevity.testworker.workers.readers.PravegaReader.start(PravegaReader.java:99)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: Connection to 172.24.2.15 is not established.
        at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$6(Retry.java:245)
        at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.util.concurrent.CompletableFuture.complete(Unknown Source)
        at io.pravega.common.concurrent.Futures.lambda$delayedFuture$19(Futures.java:516)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        ... 3 more
Caused by: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: Connection to 172.24.2.15 is not established.
        at java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniComposeStage(Unknown Source)
        at java.util.concurrent.CompletableFuture.thenCompose(Unknown Source)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.lambda$read$3(AsyncSegmentInputStreamImpl.java:188)
        at io.pravega.common.concurrent.Futures.lambda$delayedFuture$21(Futures.java:536)
        at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
        ... 9 more
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: Connection to 172.24.2.15 is not established.
        at io.pravega.client.netty.impl.FlowHandler.getChannel(FlowHandler.java:121)
        at io.pravega.client.netty.impl.ClientConnectionImpl.sendAsync(ClientConnectionImpl.java:69)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.sendRequestOverConnection(AsyncSegmentInputStreamImpl.java:202)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.lambda$null$2(AsyncSegmentInputStreamImpl.java:188)
        ... 15 more

172.24.93.3 - - [18/Apr/2019:10:42:06 +0000] "POST /v1/longevity/error HTTP/1.1" 200 3791 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 5
INFO  [2019-04-18 10:42:06,835] io.pravega.longevity.testmanager.manager.TestPerformanceCollector: Received Error From task taskID : io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: Connection to 172.24.2.15 is not established.
java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: Connection to 172.24.2.15 is not established.
        at java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
        at java.util.concurrent.CompletableFuture.join(Unknown Source)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.handleRequest(SegmentInputStreamImpl.java:137)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.read(SegmentInputStreamImpl.java:122)
        at io.pravega.client.segment.impl.EventSegmentReaderImpl.readEvent(EventSegmentReaderImpl.java:75)
        at io.pravega.client.segment.impl.EventSegmentReaderImpl.read(EventSegmentReaderImpl.java:62)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:115)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:88)
        at io.pravega.longevity.testworker.workers.readers.PravegaReader.start(PravegaReader.java:99)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: Connection to 172.24.2.15 is not established.
        at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$6(Retry.java:245)
        at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.util.concurrent.CompletableFuture.complete(Unknown Source)
        at io.pravega.common.concurrent.Futures.lambda$delayedFuture$19(Futures.java:516)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        ... 3 more
Caused by: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: Connection to 172.24.2.15 is not established.
        at java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniComposeStage(Unknown Source)
        at java.util.concurrent.CompletableFuture.thenCompose(Unknown Source)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.lambda$read$3(AsyncSegmentInputStreamImpl.java:188)
        at io.pravega.common.concurrent.Futures.lambda$delayedFuture$21(Futures.java:536)
        at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
        ... 9 more
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: Connection to 172.24.2.15 is not established.
        at io.pravega.client.netty.impl.FlowHandler.getChannel(FlowHandler.java:121)
        at io.pravega.client.netty.impl.ClientConnectionImpl.sendAsync(ClientConnectionImpl.java:69)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.sendRequestOverConnection(AsyncSegmentInputStreamImpl.java:202)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.lambda$null$2(AsyncSegmentInputStreamImpl.java:188)
        ... 15 more

172.24.93.3 - - [18/Apr/2019:10:42:06 +0000] "POST /v1/longevity/error HTTP/1.1" 200 3791 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 3
INFO  [2019-04-18 10:42:32,674] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 1h 20m
INFO  [2019-04-18 10:42:32,674] io.pravega.longevity.utils.PerformanceUtils: Writers (3/3): events:203,417, events/sec:42, KB/sec:32.490234
INFO  [2019-04-18 10:42:32,674] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 0, perSec:0.0, committed:0, failed:0, aborted:0, aborted but read: 0
INFO  [2019-04-18 10:42:32,674] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-04-18 10:42:32,674] io.pravega.longevity.utils.PerformanceUtils: Readers (2/4): events:405,210, events/sec:84, KB/sec:64.72168
```
IO Client exceptions:

```
2019-04-18 11:02:35,992 6010995 [epollEventLoopGroup-2-5] WARN  i.p.c.s.i.SegmentOutputStreamImpl - 7da43963-5855-4b18-a9ee-d69dc39cc490 Failed to connect: 
java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl$State.failConnection(SegmentOutputStreamImpl.java:202)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl$State.access$700(SegmentOutputStreamImpl.java:94)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl.failConnection(SegmentOutputStreamImpl.java:516)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl.access$500(SegmentOutputStreamImpl.java:68)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl$ResponseProcessor.lambda$appendSetup$1(SegmentOutputStreamImpl.java:366)
        at io.pravega.client.netty.impl.ClientConnectionImpl.lambda$sendAsync$1(ClientConnectionImpl.java:105)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
        at io.netty.util.concurrent.PromiseCombiner.tryPromise(PromiseCombiner.java:126)
        at io.netty.util.concurrent.PromiseCombiner.finish(PromiseCombiner.java:121)
        at io.pravega.client.netty.impl.ClientConnectionImpl.sendAsync(ClientConnectionImpl.java:107)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl$ResponseProcessor.appendSetup(SegmentOutputStreamImpl.java:362)
        at io.pravega.shared.protocol.netty.WireCommands$AppendSetup.process(WireCommands.java:666)
        at io.pravega.shared.protocol.netty.ReplyProcessor.process(ReplyProcessor.java:20)
        at io.pravega.client.netty.impl.FlowHandler.lambda$channelRead$2(FlowHandler.java:195)
        at java.util.Optional.ifPresent(Unknown Source)
        at io.pravega.client.netty.impl.FlowHandler.channelRead(FlowHandler.java:193)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0
        ... 42 common frames omitted
Caused by: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:704)
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1056)
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:290)
        at io.pravega.client.netty.impl.ClientConnectionImpl.sendAsync(ClientConnectionImpl.java:99)
        ... 34 common frames omitted
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
        at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1446)
        at io.netty.buffer.AbstractByteBuf.slice(AbstractByteBuf.java:1216)
        at io.netty.buffer.AbstractByteBuf.slice(AbstractByteBuf.java:1206)
        at io.pravega.shared.protocol.netty.CommandEncoder.encode(CommandEncoder.java:108)
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
        ... 42 common frames omitted
2019-04-18 11:02:35,992 6010995 [epollEventLoopGroup-2-5] DEBUG io.pravega.common.util.Retry - Retrying command. Retry #186, timestamp=2019-04-18T11:02:35.992Z
```
Environment details: PKS / K8 with medium cluster:

```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
5 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Deployment Details:
```
Pravega-Operator image: pravega/pravega-operator:0.3.2
Pravega build used : 0.5.0-2222.8ba5431
Zookeeper-operator image: pravega/zookeeper-operator:0.2.1
```

Following are the Cluster details:
```
root@osboxes:/home/osboxes# kubectl get po
NAME                                                 READY     STATUS    RESTARTS   AGE
pravega-bookie-0                                     1/1       Running   0          2d
pravega-bookie-1                                     1/1       Running   0          4d
pravega-bookie-2                                     1/1       Running   0          4d
pravega-bookie-3                                     1/1       Running   0          4d
pravega-operator-779879b48-6j28t                     1/1       Running   0          4d
pravega-pravega-controller-84948d8895-k6mrm          1/1       Running   1          2d
pravega-pravega-controller-84948d8895-krxpq          1/1       Running   2          4d
pravega-pravega-segmentstore-0                       1/1       Running   0          2d
pravega-pravega-segmentstore-1                       1/1       Running   0          2d
pravega-pravega-segmentstore-2                       1/1       Running   0          2d
pravega-zk-0                                         1/1       Running   0          2d
pravega-zk-1                                         0/1       Running   0          4d
pravega-zk-2                                         0/1       Running   0          4d
pravega-zk-3                                         0/1       Running   0          4d
shaka-zulu-nfs-client-provisioner-59d7f8f84c-942d2   1/1       Running   0          4d
zookeeper-operator-685bfcbbc5-wzchs                  1/1       Running   0          4d

```
Detailed logs from Pravega all pods are available in `CompelteLogs.zip`
Attaching complete 
[CompleteLogs.zip](https://github.com/pravega/pravega/files/3102392/CompleteLogs.zip)
Logs for all the components

**Comment by shrids** [comment] 2019-04-23 09:57
Could you are please share the logs of the test logs?
Also, observing that segment store logs are only upto time stamp `2019-04-18 07:59:27,082` while the error occurs @ ` [2019-04-18 10:42:06,225] `.

**Comment by Richa-Srivastava** [comment] 2019-04-23 10:42
Yes, the timings are not matching, I don't have that time issue's logs with me currently. Might be I took IO logs at later time. I am trying reproducing this issue and once I get those issues, I'll upload.

**Comment by Richa-Srivastava** [comment] 2019-04-23 12:16
Attaching the logs for all the pods after reproducing the issue. This happened on a freshly installed cluster. As soon as I deleted 2 segment stores, read operation crashed.
[pravega-k8s-logging-2019-04-23-08-09-56.zip](https://github.com/pravega/pravega/files/3107428/pravega-k8s-logging-2019-04-23-08-09-56.zip)

**Comment by sumit-bm** [comment] 2019-04-23 12:19
@shrids hope complete logs are now available including IO client logs

**Comment by shrids** [comment] 2019-04-24 06:31
@Richa-Srivastava @sumit-bm thanks for sharing the logs. 
My current analysis is as follows.

1) Error from test
```
INFO  [2019-04-23 12:04:25,526] io.pravega.longevity.testmanager.manager.TestPerformanceCollector: Received Error From task taskID : io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: Connection to 172.24.75.11 is not established.
java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: Connection to 172.24.75.11 is not established.
        at java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
        at java.util.concurrent.CompletableFuture.join(Unknown Source)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.handleRequest(SegmentInputStreamImpl.java:137)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.read(SegmentInputStreamImpl.java:122)
        at io.pravega.client.segment.impl.EventSegmentReaderImpl.readEvent(EventSegmentReaderImpl.java:75)
        at io.pravega.client.segment.impl.EventSegmentReaderImpl.read(EventSegmentReaderImpl.java:62)
        at io.pravega.client.segment.impl.EventSegmentReader.read(EventSegmentReader.java:53)
        at io.pravega.client.state.impl.RevisionedStreamClientImpl$StreamIterator.next(RevisionedStreamClientImpl.java:150)
        at io.pravega.client.state.impl.RevisionedStreamClientImpl$StreamIterator.next(RevisionedStreamClientImpl.java:125)
        at io.pravega.client.state.impl.StateSynchronizerImpl.fetchUpdates(StateSynchronizerImpl.java:80)
        at io.pravega.client.stream.impl.ReaderGroupStateManager.fetchUpdatesIfNeeded(ReaderGroupStateManager.java:284)
        at io.pravega.client.stream.impl.ReaderGroupStateManager.getCheckpoint(ReaderGroupStateManager.java:377)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.updateGroupStateIfNeeded(EventStreamReaderImpl.java:171)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:103)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:88)
        at io.pravega.longevity.testworker.workers.readers.PravegaReader.start(PravegaReader.java:99)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: Connection to 172.24.75.11 is not established.
        at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$6(Retry.java:245)
        at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.util.concurrent.CompletableFuture.complete(Unknown Source)
        at io.pravega.common.concurrent.Futures.lambda$delayedFuture$19(Futures.java:516)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        ... 3 more
Caused by: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: Connection to 172.24.75.11 is not established.
        at java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniComposeStage(Unknown Source)
        at java.util.concurrent.CompletableFuture.thenCompose(Unknown Source)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.lambda$read$3(AsyncSegmentInputStreamImpl.java:188)
        at io.pravega.common.concurrent.Futures.lambda$delayedFuture$21(Futures.java:536)
        at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
        ... 9 more
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: Connection to 172.24.75.11 is not established.
        at io.pravega.client.netty.impl.FlowHandler.getChannel(FlowHandler.java:121)
        at io.pravega.client.netty.impl.ClientConnectionImpl.sendAsync(ClientConnectionImpl.java:69)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.sendRequestOverConnection(AsyncSegmentInputStreamImpl.java:202)
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.lambda$null$2(AsyncSegmentInputStreamImpl.java:188)
        ... 15 more
```

2) From the logs it can been seen that `172.24.75.11` also corresponds to segmentStore-2 (ref : describe_pod_pravega-pravega-segmentstore-2_output) 
Since this instance of segment store starts @ ``12:04:40,585`` I am assuming that this IP is getting reused.
Also, `pravega-segmentstore-1` starts @ `12:04:12,619 ` I am assuming that segment stores (1 and 2) were  stopped at a time stamp before this.
3) The stack trace of the issue seems similar to the issue fixed by PR: #3639.

**Comment by shrids** [comment] 2019-04-25 07:17
@Richa-Srivastava this issue is already solved with PR #3639 . Could you check if you are observing the same issue on the `master`

**Comment by sumit-bm** [comment] 2019-04-25 12:19
@shrids would it be possible to cherry pick the fix in 0.5.0, we would not be taking master soon and looks like this would be good to fix in current branch?

**Comment by shrids** [comment] 2019-04-26 09:42
Raise a PR to cherry pick it ref: https://github.com/pravega/pravega/pull/3706

**Comment by shrids** [comment] 2019-05-21 07:37
`io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0`
The root cause of this issue is same https://github.com/pravega/pravega/issues/3754

**Closed by shrids** 2019-05-21 07:37 UTC
Labels: kind/bug, status/more-info-needed, version/0.5.0
