### ISSUE TITLE
Sporadic unit test failure: DataFrameBuilder-ObjectClosedException

### ISSUE THREAD

**Issue by Abhijeet-Jadhav** [pravega/pravega#1461] opened 2017-06-21 08:29 UTC
**Problem description**
Observed unit test failure due to ObjectClosedException in segment store.

Observed in travis build:
```
io.pravega.segmentstore.server.mocks.SynchronousStreamSegmentStoreTests > testEndToEnd FAILED
    java.util.concurrent.CompletionException: io.pravega.common.ObjectClosedException: Object 'DataFrameBuilder' has been closed and cannot be accessed anymore.
        Caused by:
        io.pravega.common.ObjectClosedException: Object 'DataFrameBuilder' has been closed and cannot be accessed anymore.
```

Observed in Jenkins and local build:
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testTransactionOperations FAILED
    java.util.concurrent.ExecutionException: io.pravega.common.ObjectClosedException: Object 'DataFrameBuilder' has been closed and cannot be accessed anymore.
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testTransactionOperations(StreamSegmentContainerTests.java:659)

        Caused by:
        io.pravega.common.ObjectClosedException: Object 'DataFrameBuilder' has been closed and cannot be accessed anymore.
```

**Problem location**
Segment store

**Suggestions for an improvement**
Fix sporadic failures of these unit tests.

**Comment by andreipaduroiu** [comment] 2017-06-21 21:11
https://travis-ci.org/pravega/pravega/builds/244442191

**Comment by andreipaduroiu** [comment] 2017-06-21 21:16
I am unable to reproduce this at all on my dev machine or on my mac, even after running for thousands of times. I shall keep an eye on the builds to see if this happens again in Travis, otherwise I will close this on 7/21/2017 if I don't see it again.

**Comment by arvindkandhare** [comment] 2017-06-21 22:07
You can use this https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image to try Travis locally. (I am not able to get it work though :) )

**Comment by derekm** [comment] 2021-01-10 07:55
@andreipaduroiu -- We may be seeing a modern version of this again in tests. See #5485, #5480 and also:
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testMetadataCleanupRecovery FAILED
    java.util.concurrent.ExecutionException: io.pravega.common.ObjectClosedException: Object 'PriorityBlockingDrainingQueue' has been closed and cannot be accessed anymore.
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testMetadataCleanupRecovery(StreamSegmentContainerTests.java:1496)

        Caused by:
        io.pravega.common.ObjectClosedException: Object 'PriorityBlockingDrainingQueue' has been closed and cannot be accessed anymore.
            at io.pravega.common.Exceptions.checkNotClosed(Exceptions.java:255)
            at io.pravega.common.util.AbstractDrainingQueue.poll(AbstractDrainingQueue.java:124)
            at io.pravega.segmentstore.server.logs.OperationProcessor.processOperations(OperationProcessor.java:334)
            at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
            at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by derekm** [comment] 2021-01-10 08:06
wrong already-closed object

**Closed by derekm** 2021-01-10 08:06 UTC
