### ISSUE TITLE
writes going to zero while executing segment auto scaling and segment split activity 

### ISSUE THREAD

**Issue by ipsDocker** [pravega/pravega#4278] opened 2019-10-13 09:01 UTC
**Problem description**
```
executed the following configuration using puncher tool for segment auto scale :
streams.streamname=puncherStr4
streams.scope=puncherSco4
streams.controlleruri=tcp://10.100.200.86:9090 <-- Controller IP
streams.numberofwriters=2
streams.numberofreaders=2
streams.readersgroupname=scalingRead4

scaling.policy=fixed <-- Fixed Scale policy
scaling.fixed.numberofSegments=5
scaling.runtime=60 <-- Runtime
```

K8 log location will be mentioned in the related jira and updated here 
**Problem location**
```
the  io ran for almost 55 mins and segment scaling by the factor of 2 happened starting from min segments of 5
But observed that around 13:53:30 (auto scale of segments happened from 40 to 80  ) and total writes bytes /sec  dipped to zero . 
again when auto scaling happened at 14:03:30 , writes dipped to zero for some more time .
(attached metrics screenshots )
```
cmd output
```
root@pravega-test:/pravega-puncher/scripts# ./runFatFixedScaler | grep ===
07:43:06.739 [pool-2-thread-1] INFO io.pravega.puncher.streams.scaling.ScalingCase - ============ segments: 5
07:55:06.699 [pool-2-thread-1] INFO io.pravega.puncher.streams.scaling.ScalingCase - ============ segments: 10
08:05:06.942 [pool-2-thread-1] INFO io.pravega.puncher.streams.scaling.ScalingCase - ============ segments: 20
08:15:06.701 [pool-2-thread-1] INFO io.pravega.puncher.streams.scaling.ScalingCase - ============ segments: 40
08:25:06.722 [pool-2-thread-1] INFO io.pravega.puncher.streams.scaling.ScalingCase - ============ segments: 80
08:35:06.892 [pool-2-thread-1] INFO io.pravega.puncher.streams.scaling.ScalingCase - ============ segments: 159
```

External IP for this metrics is: 10.240.119.78:3030
Following is the Pravega config detail:
```
root@osboxes:/usr/local/go/bin/src/github.com# kubectl get po -o jsonpath={...image}|tr -s [[:space:]] "\n"|sort|uniq
devops-repo.isus.emc.com:8116/nautilus/bookkeeper:0.6.0-2378.3ae8db3
devops-repo.isus.emc.com:8116/nautilus/pravega:0.6.0-2378.3ae8db3
pravega/pravega-operator:0.4.2-rc2
pravega/zookeeper:0.2.3
pravega/zookeeper-operator:0.2.2
quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
raulgracia/pravega-grafana:latest
raulgracia/pravega-influxdb:latest
```

<img width="958" alt="punch4" src="https://user-images.githubusercontent.com/54833751/66713187-0c2b1100-edc5-11e9-83fc-74d47355592c.PNG">
<img width="950" alt="punch5" src="https://user-images.githubusercontent.com/54833751/66713188-0cc3a780-edc5-11e9-8c2b-b934a223b528.PNG">
<img width="959" alt="punch6" src="https://user-images.githubusercontent.com/54833751/66713189-0cc3a780-edc5-11e9-8da8-33da769b535b.PNG">
<img width="955" alt="punch7" src="https://user-images.githubusercontent.com/54833751/66713191-0d5c3e00-edc5-11e9-8de2-b0b314d0010c.PNG">
<img width="945" alt="punch8" src="https://user-images.githubusercontent.com/54833751/66713192-0d5c3e00-edc5-11e9-86d3-9cb358557447.PNG">
<img width="960" alt="punch9" src="https://user-images.githubusercontent.com/54833751/66713193-0d5c3e00-edc5-11e9-9b2c-7820663f2e07.PNG">
<img width="948" alt="punch10" src="https://user-images.githubusercontent.com/54833751/66713194-0df4d480-edc5-11e9-9ae1-4e9a55a0d220.PNG">

root@osboxes:~# kubectl get pods --all-namespaces          

```                                                                                                                                                           
NAMESPACE     NAME                                                            READY   STATUS      RESTARTS   AGE                                                                                                      
default       grafana-5c4689f447-msdrv                                        1/1     Running     0          3d                                                                                                       
default       influxdb-84bcfc9789-tknkp                                       1/1     Running     0          3d1h                                                                                                     
default       pravega-benchmark                                               1/1     Running     0          2d23h                                                                                                    
default       pravega-bookie-0                                                1/1     Running     0          2d23h                                                                                                    
default       pravega-bookie-1                                                1/1     Running     0          2d23h
default       pravega-bookie-2                                                1/1     Running     0          2d23h
default       pravega-bookie-3                                                1/1     Running     0          2d23h
default       pravega-operator-5f45c98857-cbtpp                               1/1     Running     0          2d23h
default       pravega-pravega-controller-9dbc95bb-72z5l                       1/1     Running     1          2d23h
default       pravega-pravega-controller-9dbc95bb-gtvr7                       1/1     Running     0          2d23h
default       pravega-pravega-segmentstore-0                                  1/1     Running     0          2d23h
default       pravega-pravega-segmentstore-1                                  1/1     Running     0          2d23h
default       pravega-pravega-segmentstore-2                                  1/1     Running     0          2d23h
default       pravega-test                                                    1/1     Running     0          2d23h
default       pravega-wm                                                      1/1     Running     0          15h
default       pravega-zk-0                                                    1/1     Running     0          2d23h
default       pravega-zk-1                                                    1/1     Running     0          2d23h
default       pravega-zk-2                                                    1/1     Running     0          2d23h
default       shaka-zulu-nfs-client-provisioner-755996548f-9jwfd              1/1     Running     0          2d23h
default       zookeeper-operator-b7c699ffb-4qhnk                              1/1     Running     0          2d23h
kube-system   coredns-95489c5c9-hlsjj                                         1/1     Running     0          3d22h
kube-system   coredns-95489c5c9-nfbk8                                         1/1     Running     0          3d22h
kube-system   coredns-95489c5c9-vbkdp                                         1/1     Running     0          3d22h
kube-system   kubernetes-dashboard-558689fc66-4f22n                           1/1     Running     0          3d22h
kube-system   metrics-server-867b8fdb7d-qdp7z                                 1/1     Running     0          3d22h
kube-system   tiller-deploy-59cff884b4-bbwjf                                  1/1     Running     0          2d23h
pks-system    cert-generator-dea87263fc8e6d3a2a122f5f5e31b36afbeef369-nsh2m   0/1     Completed   0          3d22h
pks-system    event-controller-646d78b9b8-7869j                               2/2     Running     0          3d22h
pks-system    fluent-bit-6xrt2                                                2/2     Running     0          3d22h
pks-system    fluent-bit-6zww9                                                2/2     Running     0          3d22h
pks-system    fluent-bit-7x4qr                                                2/2     Running     0          3d22h
pks-system    fluent-bit-c9857                                                2/2     Running     0          3d22h
pks-system    fluent-bit-dxgbr                                                2/2     Running     0          3d22h
pks-system    metric-controller-c998cb5bf-pmc8c                               1/1     Running     0          3d22h
pks-system    observability-manager-64f749cd4c-6qs7q                          1/1     Running     0          3d22h
pks-system    sink-controller-6774fd95f7-8fbf9                                1/1     Running     0          3d22h
pks-system    telegraf-7pgrw                                                  1/1     Running     0          3d22h
pks-system    telegraf-kflqn                                                  1/1     Running     0          3d22h
pks-system    telegraf-lshnp                                                  1/1     Running     0          3d22h
pks-system    telegraf-pgrnb                                                  1/1     Running     0          3d22h
pks-system    telegraf-zm4fc                                                  1/1     Running     0          3d22h
pks-system    telemetry-agent-858446f4ff-9prvq                                2/2     Running     0          3d22h
pks-system    validator-6b677f49d4-n6gxp                                      1/1     Running     0          3d22h
```
cluster pod status

**Comment by kevinhan88** [comment] 2019-11-05 02:05
The corresponding jira issue (329) has been resolved and returned for re-test. Hence close this issue for now.

**Comment by ipsDocker** [comment] 2019-11-14 10:33
executed the following configuration using puncher tool for segment auto scale :
```
streams.streamname=puncherS1
streams.scope=puncScope1
streams.controlleruri=tcp://10.100.200.126:9090 <-- Controller IP
streams.numberofwriters=2
streams.numberofreaders=2
streams.readersgroupname=scalingReaders

scaling.policy=fixed <-- Fixed Scale policy
scaling.fixed.numberofSegments=5
scaling.runtime=60 <-- Runtime

```

cmd output:
```
oot@pravega-benchmark2:/pravega-puncher/scripts# ./runFatFixedScaler | grep ===
09:11:32.116 [pool-2-thread-1] INFO io.pravega.puncher.streams.scaling.ScalingCase - ============ segments: 10
09:23:32.082 [pool-2-thread-1] INFO io.pravega.puncher.streams.scaling.ScalingCase - ============ segments: 20
09:33:32.098 [pool-2-thread-1] INFO io.pravega.puncher.streams.scaling.ScalingCase - ============ segments: 40                                       
09:43:32.097 [pool-2-thread-1] INFO io.pravega.puncher.streams.scaling.ScalingCase - ============ segments: 80
09:53:32.109 [pool-2-thread-1] INFO io.pravega.puncher.streams.scaling.ScalingCase - ============ segments: 160
10:03:32.135 [pool-2-thread-1] INFO io.pravega.puncher.streams.scaling.ScalingCase - ============ segments: 320
```

screen shots of metrics 
<img width="949" alt="1" src="https://user-images.githubusercontent.com/54833751/68849494-33dd0400-06f8-11ea-8748-fc03dd136f79.PNG">
<img width="953" alt="2" src="https://user-images.githubusercontent.com/54833751/68849495-34759a80-06f8-11ea-84a0-9235f7f623c6.PNG">
<img width="955" alt="3" src="https://user-images.githubusercontent.com/54833751/68849497-34759a80-06f8-11ea-943d-57e4712be859.PNG">

**Comment by ipsDocker** [comment] 2019-11-14 10:34
reopening this issue and logs are mentioned in the concerned jira

**Comment by kevinhan88** [comment] 2019-11-18 19:00
The issue is reopened per the request of Ipsita Panda, in order to access logs stored here, and also the load more logs when needed.

**Comment by ipsDocker** [comment] 2019-11-19 09:56
logs are mentioned at the concerned jira related to this issue

**Closed** 2020-01-24 22:57 UTC
Labels: kind/bug
