### ISSUE TITLE
Cherry pick PR 3645 to r0.5

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#4041] opened 2019-07-19 10:33 UTC
**Problem description**
We need to port #3645 to `0.5` to be able to configure direct reads in RocksDB. However, we need to keep the default value to true, so the configuration for `0.5` remains the same.

**Problem location**
RocksDB config.

**Suggestions for an improvement**
Cherry pick the PR and set default value `rocksdb.directReads=true`.

**Comment by fpj** [comment] 2019-07-19 12:33
Duplicate of #3645 .

**Closed by fpj** 2019-07-19 12:33 UTC
Labels: area/segmentstore, kind/release, priority/P0, version/0.5.0
