### ISSUE TITLE
During segment container ownership transfer readers get NoSuchSegment 

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#2678] opened 2018-06-09 06:39 UTC
**Problem description**
Readers were reading from a segment on a particular segment container. Then segmentContainer failover happened and post ownership transfer readers failed with NoSuchSegment. 
This lead to readers rereading data from offset 0 in the segment `0#epoch.10` again. 
It repeated 3 times before they were successfully able to read it. 

```
segmentstore_2018-06-08.1.log:2018-06-08 14:24:26,941 103854 [core-10] WARN  i.p.s.s.h.h.PravegaRequestProcessor - Segment 'testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10' does not exist and cannot perform operation 'Read segment'.
segmentstore_2018-06-08.1.log:2018-06-08 14:24:27,974 104887 [core-24] WARN  i.p.s.s.h.h.PravegaRequestProcessor - Segment 'testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10' does not exist and cannot perform operation 'Read segment'.
segmentstore_2018-06-08.1.log:2018-06-08 14:24:29,016 105929 [core-28] WARN  i.p.s.s.h.h.PravegaRequestProcessor - Segment 'testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10' does not exist and cannot perform operation 'Read segment'.
```

**Problem location**
SegmentStore

**Suggestions for an improvement**
Fix the issue

**Comment by shiveshr** [comment] 2018-06-09 06:41
[logs.zip](https://github.com/pravega/pravega/files/2086714/logs.zip)

**Comment by shiveshr** [comment] 2018-06-09 06:43
client logs
[server.zip](https://github.com/pravega/pravega/files/2086716/server.zip)

**Comment by shiveshr** [comment] 2018-06-11 05:05
There are possibly two issues here:
@tkaitchuck @shrids 
1. client is rereading data from predecessor upon getting NoSuchSegment. 

@andreipaduroiu @arvindkandhare @fpj 
2. NoSuchSegment should only be returned by segmentstore when the segment actually doesnt exist. 
During transition/transfer of container ownership, it should not send "NoSuchSegment" intermittently because semantics of handling noSuchSegment in controller and clients are different and there is no way for controllers or clients to disambiguate between an expected NoSuchSegment and one coming because of failover. 
As an example, controller calling mergeSegment or DeleteSegment have legitimate "NoSuchSegment" responses. If a transient NoSuchSegment is sent because of failover, controller may assume the work to be done when it may not actually be completed. 
Similarly, client treats noSuchSegment as an indication of "truncation" and its handling of this response is completely different. Client has no way of knowing if this is because segment container is being transferred of it the segment is indeed truncated. 

So noSuchSegment should only be used when segment "actually" doesnt exist. The correct response during failover/transfer of container ownership should be `WrongHost` which informs the client and controller of a correct transient state and they can continue to "retry" until the failover completes and they send requests to the correct host.

**Comment by shrids** [comment] 2018-06-11 05:39
@shiveshr @tkaitchuck 
As per my understanding there are not changes required on the client end; the only change is that SSS should not respond with NoSuchSegment here.

The current behavior of Readers(EventStreamReaderImpl + AsyncSegmentInputStream + SegmentInputStreamImpl) is that on receiving a `NoSuchSegmentException` [1] it does the following

a. 
- Try fetching the start offset of the segment `getSegmentInfo()` to handle a segment truncation scenario; [2]
- Store the offset for the next read and throw `TruncatedDataException` to the reader.(Incase the user invokes read again read from the new start offset.)

b. In case step (a) failed i.e. `getSegmentInfo()` fails with NoSuchSegment then update group state to remove this segment, fetch successors and throw TruncatedDataException to inform the application about Truncation.

From the logs it can be seen that: 

a. NoSuchSegment for received for `testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10`
b. getSegmentInfo() for this segment succeeded.

The test code
- Does not handle SegmentTruncation since no truncation policy is set. i.e. on receiving Truncation the test-reader stop reading.
- Since the test spawns multiple readers the other readers try reading this segment after they acquire this segment and try reading from the last know offset, which causes duplicate events.

**Comment by shrids** [comment] 2018-06-11 05:39
Relevant log snippets
```
[1]
2018-06-08 14:24:26,941 321557 [epollEventLoopGroup-4-2] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Received noSuchSegment No such segment: testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10
2018-06-08 14:24:26,942 321558 [epollEventLoopGroup-4-2] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10
io.pravega.client.segment.impl.SegmentTruncatedException: Segment no longer exists

[2]
2018-06-08 14:24:26,944 321560 [clientInternal-3] DEBUG i.p.c.s.i.SegmentMetadataClientImpl - Getting segment info for segment: testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10
2018-06-08 14:24:26,944 321560 [clientInternal-3] TRACE i.p.c.stream.impl.ControllerImpl - ENTER getEndpointForSegment@8381349513007 [testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10].
...
2018-06-08 14:24:26,963 321579 [epollEventLoopGroup-4-8] DEBUG i.p.client.netty.impl.RawClient - Received reply WireCommands.StreamSegmentInfo(type=STREAM_SEGMENT_INFO, requestId=1, segmentName=testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10, exists=true, isSealed=false, isDeleted=false, lastModified=1528467863209, writeOffset=85590, startOffset=0)


[3]
2018-06-08 14:24:26,964 321580 [ReadTxnWriteAutoScaleWithFailoverTest-main-5] ERROR i.p.t.system.AbstractFailoverTests - Test exception in reading events: 
io.pravega.client.stream.TruncatedDataException: null
```

**Comment by shrids** [comment] 2018-06-11 06:41
There are 5 readers in the test and each reader stops reading if it encounters a TruncationException.
The below log snippets explain why duplicate events were read (4 instances of the same event were found)

==> First test reader got SegmentTruncationException from SSS after reading upto offset `59220+1170` = `60390` 
```
2018-06-08 14:24:25,645 320261 [epollEventLoopGroup-4-2] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Received read result WireCommands.SegmentRead(type=SEGMENT_READ, segment=testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10, offset=0, atTail=false, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=58320 cap=58320])
2018-06-08 14:24:25,746 320362 [epollEventLoopGroup-4-2] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Received read result WireCommands.SegmentRead(type=SEGMENT_READ, segment=testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10, offset=58320, atTail=false, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=900 cap=900])
2018-06-08 14:24:25,755 320371 [epollEventLoopGroup-4-2] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Received read result WireCommands.SegmentRead(type=SEGMENT_READ, segment=testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10, offset=59220, atTail=false, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=1170 cap=1170])
2018-06-08 14:24:26,941 321557 [epollEventLoopGroup-4-2] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Received noSuchSegment No such segment: testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10
```

==> The second reader acquired this segment and successfully read upto offset `60390` before throwing an exception.
```
2018-06-08 14:24:26,970 321586 [epollEventLoopGroup-4-2] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Received read result WireCommands.SegmentRead(type=SEGMENT_READ, segment=testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10, offset=0, atTail=false, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=60390 cap=60390])
2018-06-08 14:24:27,979 322595 [epollEventLoopGroup-4-2] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Received noSuchSegment No such segment: testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10
```

===> The third reader acquired this segment and successfully read upto offset `60390` before throwing an exception:
```
2018-06-08 14:24:28,002 322618 [epollEventLoopGroup-4-3] DEBUG i.p.client.netty.impl.RawClient - Received reply WireCommands.StreamSegmentInfo(type=STREAM_SEGMENT_INFO, requestId=1, segmentName=testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10, exists=true, isSealed=false, isDeleted=false, lastModified=1528467863209, writeOffset=85590, startOffset=0)
2018-06-08 14:24:28,012 322628 [epollEventLoopGroup-4-2] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Received read result WireCommands.SegmentRead(type=SEGMENT_READ, segment=testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10, offset=0, atTail=false, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=60390 cap=60390])
2018-06-08 14:24:29,023 323639 [epollEventLoopGroup-4-2] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Received noSuchSegment No such segment: testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10
2018-06-08 14:24:29,049 323665 [epollEventLoopGroup-4-5] DEBUG i.p.client.netty.impl.RawClient - Received reply WireCommands.StreamSegmentInfo(type=STREAM_SEGMENT_INFO, requestId=1, segmentName=testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10, exists=true, isSealed=false, isDeleted=false, lastModified=1528467863209, writeOffset=85590, startOffset=0)
```

===> The fourth reader successfully read this segment until it received a Segment sealed.
``` 
2018-06-08 14:24:29,052 323668 [epollEventLoopGroup-4-2] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Received read result WireCommands.SegmentRead(type=SEGMENT_READ, segment=testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10, offset=0, atTail=false, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=60390 cap=60390])
2018-06-08 14:24:30,122 324738 [epollEventLoopGroup-4-2] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Received read result WireCommands.SegmentRead(type=SEGMENT_READ, segment=testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10, offset=60390, atTail=false, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=180 cap=180])
2018-06-08 14:24:30,129 324745 [epollEventLoopGroup-4-2] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Received read result WireCommands.SegmentRead(type=SEGMENT_READ, segment=testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10, offset=60570, atTail=false, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=2340 cap=2340])
...
Last read is at offset `169830`
2018-06-08 14:25:42,191 396807 [epollEventLoopGroup-4-2] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Received segmentSealed WireCommands.SegmentIsSealed(type=SEGMENT_IS_SEALED, requestId=169830, segment=testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10)
```

**Comment by shiveshr** [comment] 2018-06-11 06:45
what is special about offset `60390`? 
is it possible that offset `60390` on `0#epoch.10` could relate to the amount of data during recovery while remainder data continues to be in tier-1?

Also, i think this rules out client/state-synchronizer rereading data from predecessor about receiving NoSuchSegment. Which means reader is behaving as expected and the problem is possibly elsewhere (segmentstore?)

**Comment by arvindkandhare** [comment] 2018-06-11 17:58
> Here are my two cents on the matter:
> NoSuchSegment should only be returned by segmentstore when the segment actually doesnt exist.
> During transition/transfer of container ownership, it should not send "NoSuchSegment" intermittently because semantics of handling noSuchSegment in controller and clients are different and there is no way for controllers or clients to disambiguate between an expected NoSuchSegment and one coming because of failover.

IMO this situation occurs when the controller and segmentstore are in in sync. In case of a segment container ownership change that is triggered by controller but not yet accepted by the segmentstore the given container is orphan/zombie.  Please correct me if this is not the case here.

I remember there were some discussions about having a hot secondary owner(s) of a container. This way a container is never orphan and no existing segment gets `NoSuchSegment`.

As per the suggestion by @shiveshr , a segmentstore can not decide validity of a segment. Only container has this info. There can be another (non optimal) solution where controller decides whether a container is actually live and owned by a segmentstore before returning the successors. In this case the controller returns `ContainerNotReady` to the client and the client waits till the time container is ready as suggested.

**Comment by andreipaduroiu** [comment] 2018-06-11 19:01
Here is what I found so far. Whatever is reported in this issue is not the cause for failure in this test, as the logs clearly indicate that readers made progress after about 5 seconds of retrying.

Here's the repro.
1. We have segments A and B, and want to merge B into A at offset N.
2. We get the request, write it to Tier1, and update the read index for A to redirect to B until this B is merged into A in Tier2.
3. StorageWriter executes the merge in Tier2, hence B does not exist anymore.
    - In a normal scenario (no failover), upon this step happening, the read index for A would be updated so that it knows B doesn't exist anymore and the corresponding offsets exist in Segment A in Tier2.
4. We failover, so we never have a chance to record this in Tier1.
5. Immediately after failover we want to read from A at offset N. Since the metadata does not know yet know the state of affairs in Tier2, it tries to redirect the read to B in Tier2. Since this does not exist, it throws `StreamSegmentNotExistsException`.
6. Eventually the StorageWriter reconciles the Tier2 state and completes everything there is to complete, and the situation comes back to normal.

This is one problem that isn't so easy to fix, that is, if there's anything to fix at all. The only way to make it "100% correct" would be to execute the Tier2 reconciliation during recovery, but that will significantly delay the recovery process itself, which means more delays for all the operations that the container executes. Tier2 reconciliation is kicked off as soon as recovery is done, and will complete soon thereafter, including tying any loose ends that were aborted during the failover process.

Here is what I used to determine this is not the blocker:
1. This shows that the `completeMerge` happened both before and after failover (62746 is target segment, 63200 is our source segment. The offset of the merger was `60390`
`grep -r "TargetId \= 62746, SourceId \= 63200" .`

2. This shows that the MergeOperation was processed twice by the StorageWriter. Once on the old instance and once on the new. First one executed in Tier2, second one reconciled
`grep -r "MergeSegmentOperation\: SequenceNumber \= 63254" .`

2. This shows that this issue is transient and self-resolved after 5 seconds
`grep -r "does not exist and cannot perform operation" .`

3. This is the full log for this segment. It shows that it got stuck at an offset for 5 seconds, immediately after failover, then eventually made progress.
`grep -r "\(62746\|testReadTxnWriteAutoScaleScope2092305162\/testReadTxnWriteAutoScaleStream\/0\#epoch\.1\)" .`

**Comment by arvindkandhare** [comment] 2018-06-12 00:54
> Whatever is reported in this issue is not the cause for failure in this test,

@andreipaduroiu I think this is subset of the condition I laid out. In this particular case, the segmentstore has taken over the ownership but has not yet created the complete state for the container. There is still a window of time where controller thinks that a segmentstore owns a container but the segmentstore has not yet received the assignment. @shiveshr is this scenario possible? If yes, I think we should fix that too.

**Comment by shiveshr** [comment] 2018-06-12 02:04
> Whatever is reported in this issue is not the cause for failure in this test, as the logs clearly indicate that readers made progress after about 5 seconds of retrying
@andreipaduroiu 
what is reported in the issue is the symptom. The readers got NoSuchSegment while reading in the middle of the segment and that led to a chain of events that caused re-reads of data till offset `60390` thrice. 
The root cause for that chain of events is that there should not have been a `NoSuchSegment` response but there was. 

> This is one problem that isn't so easy to fix, that is, if there's anything to fix at all.
I disagree with second part of this statement. Based on the sequence of steps that you described, either there should be some synchronization that does not pass the request to read from tier-2 in such situations, Or at least a NoSuchSegment is translated differently and sent back to the caller in a meaningful way (like a WrongHostException would also suffice). 


> There is still a window of time where controller thinks that a segmentstore owns a container but the segmentstore has not yet received the assignment. @shiveshr is this scenario possible? If yes, I think we should fix that too.

As long as there is a mutually exclusive ownership of segment container it is not a problem. Controller changes the assignment and pushes the information to different hosts. One host has to stop the container while the other has to start. 
Controller cannot monitor the exact state of segmentstore. And even if it did, it can be transiently wrong about ownership change because "new" host may not have started the container yet. But that should result in `WrongHostException` and not `NoSuchSegment`. 

Here is the expectation:
1. If the controller directs clients to old host transiently as container ownership transfer is taking place, the clients should get WrongHostException. 
2. Similarly, if controller directed clients to new host while container had not started yet, we should get WrongHostException.  

What has happened in this reproduction, though, is clients are directed to new host. The recovery is ongoing and new host has become aware of the said segment and is serving reads from this segment. So the clients start reading some data from the said segment from the new host. And (my understanding from comments above is) mid-way into reading this data, the state machine on segmentstore realizes that further data has to be read from tier-2 and tier-2 has no awareness of the segment, hence in the middle of the read there is NoSuchSegment. 
This happens transiently, until tier-2 becomes aware of existence of segment (as recovery process goes ahead and creates segment in tier-2??). So about 5-10 seconds later, readers are able to continue reading from the said segment.

**Comment by andreipaduroiu** [comment] 2018-06-13 16:56
Thanks for all the help in debugging this. After further digging in the logs (which are really, really stuffy), I realized that this was indeed the test failure cause. The test itself could be improved to make it more clear what failed (and when), but that is an issue for another time (#2688).

I have a PR out that hopefully fixes this corner case bug. This needs fixing, despite the fact that we had a good number of master build test successes recently.

**Closed** 2018-06-14 18:05 UTC
Labels: area/server, kind/bug, priority/P0
