### ISSUE TITLE
Users should know how to access remote standalone

### ISSUE THREAD

**Issue by CharlieLChen** [pravega/pravega#6511] opened 2022-01-10 08:13 UTC
**Background**

In the Flink-Pravega hackathon, some participants want to access the remote standalone, they unzip the distribution then start the standalone, but they find they can't write data to stream successfully. After troubleshooting I find the segment store will register itself in ZK using the value of the `publishedIPAddress` after segment containers start-up: https://github.com/pravega/pravega/blob/a5aa4a29e5dbebc7fec6c080d4aca1c23ac9c5e4/segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ServiceStarter.java#L292. The default value for it is `0.0.0.0`, this value will be returned to the client when the user write data, so the user will write data to `0.0.0.0`. Apparently, it can't be successful as the  `0.0.0.0` means local address. 

The workaround for this issue is to specify the  `publishedIPAddress` by `JAVA_OPTS` like the below, that is the way the docker version is currently doing. 
```shell
 export JAVA_OPTS="-Dpravegaservice.service.published.host.nameOrIp=10.247.101.103"
```
The user should know that so that they can configure standalone properly and access it from remote, the solution should be added in `run-local.md` and `quick-started.md`

**Comment by CharlieLChen** [comment] 2022-01-10 08:49
I will create a PR for this one tomorow.

**Comment by CharlieLChen** [comment] 2022-01-11 07:00
The PR will be created after 0.10.2 release

**Comment by RaulGracia** [comment] 2022-10-27 16:12
@derekm can you close this one in case the issue is not relevant anymore?

**Closed** 2022-10-28 02:16 UTC
