### ISSUE TITLE
Test case failure testWriteAfterHeaderMerge

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#3850] opened 2019-05-29 13:54 UTC
**Problem description**
The test case timed out in one of our Jenkins runs. The logs are here:

[testWriteAfterHeaderMerge.txt](https://github.com/pravega/pravega/files/3232814/testWriteAfterHeaderMerge.txt)

**Problem location**
Junit tests

**Suggestions for an improvement**
Debug it.

**Comment by sachin-j-joshi** [comment] 2019-05-30 19:17
![image](https://user-images.githubusercontent.com/44757683/58658169-bef64900-82d4-11e9-978e-8aafb34bcff0.png)

I am not yet able to repro this failure locally. (it's been running fine for >45 minutes).  I'll fiddle with memory/cpu settings to see if I can repro.

**Comment by sachin-j-joshi** [comment] 2019-05-30 19:26
Looking at the attached log the cause seems to be that MiniCluster is shut down. 

> 2019-05-24 11:30:38,202 INFO  [Time-limited test] hdfs.MiniDFSCluster (MiniDFSCluster.java:shutdown(1789)) - Shutting down the Mini HDFS Cluster
2019-05-24 11:30:38,202 INFO  [Time-limited test] hdfs.MiniDFSCluster (MiniDFSCluster.java:shutdownDataNode(1838)) - Shutting down DataNode 0
2019-05-24 11:30:38,203 64469 [org.apache.hadoop.hdfs.server.datanode.DataXceiverServer@5896c974] INFO  o.a.h.hdfs.server.datanode.DataNode - Closing all peers.

The root cause seems to be that it is interrupted.

> 2019-05-24 11:30:38,194 WARN  [Time-limited test] ipc.Client (Client.java:call(1392)) - interrupted waiting to send rpc request to server
java.lang.InterruptedException
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:404)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ipc.Client$Connection.sendRpcRequest(Client.java:1138)
	at org.apache.hadoop.ipc.Client.call(Client.java:1387)
	at org.apache.hadoop.ipc.Client.call(Client.java:1345)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:227)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
	at com.sun.proxy.$Proxy84.getDatanodeReport(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getDatanodeReport(ClientNamenodeProtocolTranslatorPB.java:649)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:409)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:163)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:155)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:346)
	at com.sun.proxy.$Proxy87.getDatanodeReport(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.datanodeReport(DFSClient.java:2108)
	at org.apache.hadoop.hdfs.MiniDFSCluster.waitActive(MiniDFSCluster.java:2463)
	at org.apache.hadoop.hdfs.MiniDFSCluster.waitActive(MiniDFSCluster.java:2507)
	at org.apache.hadoop.hdfs.MiniDFSCluster.startDataNodes(MiniDFSCluster.java:1541)
	at org.apache.hadoop.hdfs.MiniDFSCluster.initMiniDFSCluster(MiniDFSCluster.java:851)
	at org.apache.hadoop.hdfs.MiniDFSCluster.<init>(MiniDFSCluster.java:485)
	at org.apache.hadoop.hdfs.MiniDFSCluster$Builder.build(MiniDFSCluster.java:444)
	at io.pravega.storage.hdfs.HDFSClusterHelpers.createMiniDFSCluster(HDFSClusterHelpers.java:32)
	at io.pravega.storage.hdfs.HDFSStorageTest$RollingStorageTests.setUp(HDFSStorageTest.java:382)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
2019-05-24 11:30:38,201 WARN  [Time-limited test] hdfs.MiniDFSCluster (MiniDFSCluster.java:waitActive(2513)) - Tried waitActive() 2 time(s) and failed, giving up.  java.io.IOException: java.lang.InterruptedException
	at org.apache.hadoop.ipc.Client.call(Client.java:1393)
	at org.apache.hadoop.ipc.Client.call(Client.java:1345)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:227)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
	at com.sun.proxy.$Proxy84.getDatanodeReport(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getDatanodeReport(ClientNamenodeProtocolTranslatorPB.java:649)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:409)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:163)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:155)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:346)
	at com.sun.proxy.$Proxy87.getDatanodeReport(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.datanodeReport(DFSClient.java:2108)
	at org.apache.hadoop.hdfs.MiniDFSCluster.waitActive(MiniDFSCluster.java:2463)
	at org.apache.hadoop.hdfs.MiniDFSCluster.waitActive(MiniDFSCluster.java:2507)
	at org.apache.hadoop.hdfs.MiniDFSCluster.startDataNodes(MiniDFSCluster.java:1541)
	at org.apache.hadoop.hdfs.MiniDFSCluster.initMiniDFSCluster(MiniDFSCluster.java:851)
	at org.apache.hadoop.hdfs.MiniDFSCluster.<init>(MiniDFSCluster.java:485)
	at org.apache.hadoop.hdfs.MiniDFSCluster$Builder.build(MiniDFSCluster.java:444)
	at io.pravega.storage.hdfs.HDFSClusterHelpers.createMiniDFSCluster(HDFSClusterHelpers.java:32)
	at io.pravega.storage.hdfs.HDFSStorageTest$RollingStorageTests.setUp(HDFSStorageTest.java:382)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:404)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ipc.Client$Connection.sendRpcRequest(Client.java:1138)
	at org.apache.hadoop.ipc.Client.call(Client.java:1387)
	... 37 more

> 2019-05-24 11:30:38,202 INFO  [Time-limited test] hdfs.MiniDFSCluster (MiniDFSCluster.java:shutdown(1789)) - Shutting down the Mini HDFS Cluster
2019-05-24 11:30:38,202 INFO  [Time-limited test] hdfs.MiniDFSCluster (MiniDFSCluster.java:shutdownDataNode(1838)) - Shutting down DataNode 0
2019-05-24 11:30:38,203 64469 [org.apache.hadoop.hdfs.server.datanode.DataXceiverServer@5896c974] INFO  o.a.h.hdfs.server.datanode.DataNode - Closing all peers.



> 2019-05-24 11:30:38,289 64555 [BP-1364555856-192.168.250.250-1558697409496 heartbeating to localhost/127.0.0.1:34844] WARN  o.a.h.h.s.d.IncrementalBlockReportManager - IncrementalBlockReportManager interrupted



> 2019-05-24 11:30:38,304 64570 [refreshUsed-/tmp/test_hdfs3136661126642910963/data/data1/current/BP-1364555856-192.168.250.250-1558697409496] WARN  o.a.hadoop.fs.CachingGetSpaceUsed - Thread Interrupted waiting to refresh disk information: sleep interrupted
2019-05-24 11:30:38,304 64570 [refreshUsed-/tmp/test_hdfs3136661126642910963/data/data2/current/BP-1364555856-192.168.250.250-1558697409496] WARN  o.a.hadoop.fs.CachingGetSpaceUsed - Thread Interrupted waiting to refresh disk information: sleep interrupted






> 2019-05-24 11:31:02,773 89039 [IPC Server handler 8 on 45854] INFO  org.apache.hadoop.hdfs.StateChange - DIR* completeFile: /Concat_3$offset.150_1 is closed by DFSClient_NONMAPREDUCE_1586215185_1978
2019-05-24 11:31:02,773 89039 [DataStreamer for file /Concat_3$offset.150_1] WARN  org.apache.hadoop.hdfs.DataStreamer - Caught exception
java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1252)
	at java.lang.Thread.join(Thread.java:1326)
	at org.apache.hadoop.hdfs.DataStreamer.closeResponder(DataStreamer.java:973)
	at org.apache.hadoop.hdfs.DataStreamer.endBlock(DataStreamer.java:624)
2

**Closed** 2020-01-24 23:01 UTC
Labels: area/segmentstore, area/tier2, kind/bug, status/accepted, version/0.6.0
