### ISSUE TITLE
"Unexpected exception causing shutdown while sock still open java.io.EOFException" error observed in Zookeeper logs while running longevity test

### ISSUE THREAD

**Issue by vedanthh** [pravega/pravega#3218] opened 2018-12-19 13:00 UTC
**"Unexpected exception causing shutdown while sock still open java.io.EOFException" error observed in Zookeeper logs while running longevity test**

[Zookeeper and Controller Logs.zip](https://github.com/pravega/pravega/files/2694840/Zookeeper.and.Controller.Logs.zip)

**Snip of Error:**

```
2018-12-18 09:47:15,953 [myid:1] - WARN  [RecvWorker:3:QuorumCnxManager$RecvWorker@1148] - Connection broken for id 3, my id = 1, error =
java.net.SocketException: Socket closed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at java.io.DataInputStream.readInt(DataInputStream.java:387)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$RecvWorker.run(QuorumCnxManager.java:1133)
2018-12-18 09:47:15,957 [myid:1] - WARN  [RecvWorker:3:QuorumCnxManager$RecvWorker@1151] - Interrupting SendWorker
2018-12-18 09:47:15,957 [myid:1] - WARN  [SendWorker:3:QuorumCnxManager$SendWorker@1074] - Send worker leaving thread  id 3 my id = 1
2018-12-18 09:47:15,959 [myid:1] - ERROR [LearnerHandler-/172.24.21.14:43810:LearnerHandler@624] - Unexpected exception causing shutdown while sock still open
java.io.EOFException
        at java.io.DataInputStream.readInt(DataInputStream.java:392)
        at org.apache.jute.BinaryInputArchive.readInt(BinaryInputArchive.java:63)
        at org.apache.zookeeper.server.quorum.QuorumPacket.deserialize(QuorumPacket.java:85)
        at org.apache.jute.BinaryInputArchive.readRecord(BinaryInputArchive.java:99)
        at org.apache.zookeeper.server.quorum.LearnerHandler.run(LearnerHandler.java:534)
2018-12-18 09:47:15,959 [myid:1] - WARN  [LearnerHandler-/172.24.21.14:43810:LearnerHandler@639] - ******* GOODBYE /172.24.21.14:43810 ********
2018-12-18 09:47:15,966 [myid:1] - INFO  [LearnerHandler-/172.24.21.14:43830:LearnerHandler@404] - Follower sid: 3 not in the current config 1000000fa
2018-12-18 09:47:15,967 [myid:1] - INFO  [LearnerHandler-/172.24.21.14:43830:ZKDatabase@295] - On disk txn sync enabled with snapshotSizeFactor 0.33
2018-12-18 09:47:15,967 [myid:1] - INFO  [LearnerHandler-/172.24.21.14:43830:LearnerHandler@703] - Synchronizing with Follower sid: 3 maxCommittedLog=0x1000000fa minCommittedLog=0x100000001 lastProcessedZxid=0x1000000fa peerLastZxid=0x1000000fa
2018-12-18 09:47:15,967 [myid:1] - INFO  [LearnerHandler-/172.24.21.14:43830:LearnerHandler@747] - Sending DIFF zxid=0x1000000fa for peer sid: 3
2018-12-18 09:47:17,006 [myid:1] - INFO  [SessionTracker:ZooKeeperServer@392] - Expiring session 0x2001118ace90004, timeout of 4000ms exceeded```

**Comment by RaulGracia** [comment] 2019-02-01 18:34
Observed the same problems as root cause in #3227.

**Comment by RaulGracia** [comment] 2019-03-18 09:43
@vedanthh We normally observe this kind of `EOFException` in Zookeeper logs. This normally means that a ZK server closed a connection with another ZK server (e.g., change in leadership), and such stracktraces are the manifestation of this. I see that the Controller continued working properly before and after this stacktrace in ZK logs, so I infer that this event did not represent a problem for the Pravega cluster. Unless there are evidences that this kind of errors in the logs manifest a problem that prevents Pravega to operate properly, I'm inclined to close this issue.

**Closed by RaulGracia** 2019-03-18 09:43 UTC
Labels: area/controller, priority/P2, status/more-info-needed
