### ISSUE TITLE
API to check if stream exists.

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#796] opened 2017-03-17 19:42 UTC
**Problem description**
Right now there is no good way to check for the existence of a stream. This makes for awkward exceptions when you create a writer on a stream that does not exist.

**Problem location**
The client and controller.

**Suggestions for an improvement**
Add an API in the controller to check if a stream exists and call it on the client both internally, and via an explicit operation.

**Comment by shiveshr** [comment] 2019-10-03 03:08
Duplicate of #417

**Closed by shiveshr** 2019-10-03 03:08 UTC
Labels: area/client, area/controller, kind/feature, priority/P2
