### ISSUE TITLE
Committed Transaction Somehow Becomes Aborted 

### ISSUE THREAD

**Issue by jadnhm** [pravega/pravega#2650] opened 2018-06-01 19:37 UTC
**Problem Description**
The Nautilus platform team has a longevity test which tries to validate certain situations with transactions. 

It was discovered during a longevity run using the `smallTx` version of the test on May 24th that revealed a writer error had occurred:
```2018-05-24 07:58:15,231 64910292 [pool-4-thread-1] ERROR c.e.n.h.t.w.writers.PravegaWriter - Writer finished with Error
java.lang.IllegalStateException: Got an aborted transaction, didn't expect that
 at com.emc.nautilus.hulk.taskexecutor.workers.writers.PravegaWriterState$forkWatchProcess$watchProcess$1.run(PravegaWriterState.kt:148)
 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
 at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 at java.lang.Thread.run(Unknown Source)
```

The thread dump on the task executer shows some locked threads, though this was taken a few hours after the failure actually occurred. (see attached stdout log)

Some discussion occurred on slack, in which it was determined that if the `txn.commit()` call returned successfully (no exception, and thus the commit was acknowledged) then it /shouldn't be possible/ for that transaction to end up in an aborted state.  

Pravega Controller log is attached
[controller_server_2018-05-24.188.ben-urich.log](https://github.com/pravega/pravega/files/2063814/controller_server_2018-05-24.188.ben-urich.log)

stdout.log with threadump is attached:
[stdout.ben-urich.smallTx.tread_dump.log.txt](https://github.com/pravega/pravega/files/2063920/stdout.ben-urich.smallTx.tread_dump.log.txt)

There seems to be some confusion about what's happened here, and the platform team will not be able to sort out the problem on our own.

**Comment by shiveshr** [comment] 2018-06-06 14:46
There is nothing in the log to say a "committed" transaction became aborted. 

What we can see in the logs is that writer was attempting to write the event to a transaction and found it to be aborted. This would typically precede writer attempting to commit the transaction (as it is still writing events to it). 

So i dont see evidence of "transaction aborting" after acknowledging a commit. Could you please point me to the exact stack which made you conclude as such. 

The client periodically keeps sending keep-alive pings for transactions to controller so they dont get aborted so the reason it may be aborted is because there was some intermittent connectivity problem between client and controller which could lead to this happening.

**Comment by jadnhm** [comment] 2018-06-11 19:08
Thanks for looking into this. We are currently unable to collect evidence for this as we need a longer test run then we're currently able to achieve due to other failure modes. When we get another failure like this we'll try to get more log data for you.

**Comment by shiveshr** [comment] 2018-06-15 03:49
Closing the issue because logs dont have evidence of any anomalous behaviour.

**Closed by shiveshr** 2018-06-15 03:49 UTC
Labels: area/controller, kind/bug, priority/P0, status/needs-attention

**Comment by jadnhm** [comment] 2018-06-18 15:50
I don't mean to be too presumptuous but was the IllegalStateException not anomalous?

**Comment by shiveshr** [comment] 2018-06-18 15:53
No, that just says a transaction was aborted automatically (because it timed out). The client attempted to perform some operation on it after the abort had happened and received corresponding Exception and logged that message. 

Ideally transaction will not be aborted if there is stable connection between client and controller and it is able to keep renewing the transaction lease. However, if controller does not receive the lease renewal request, it aborts the transactions.

**Comment by shiveshr** [comment] 2018-06-18 15:57
The reason i have closed the issue is because the issue says transaction was acknowledged to be committed and then was aborted. Which is not what has happened. 

At the time when this issue was opened, the lease period had a ceiling of 30 seconds. So any intermittent connection glitch between client and controller for 30 seconds would result in transaction being aborted.

After a recent change, the lease duration can be larger and is not limited by 30 seconds.
