### ISSUE TITLE
Time window stops progressing InProcPravegaCluster

### ISSUE THREAD

**Issue by crazyzhou** [pravega/pravega#4228] opened 2019-09-30 04:44 UTC
**Problem description**
In Flink connector, we have a unit test case to check if the `TimeWindow` can progress when we read events. Logs show that the `TimeWindow` from the reader always returns `(null, null)` while reading events. Change `ZKClient` into `PravegaTables` can solve this issue.

**Problem location**
`io.pravega.local.InProcPravegaCluster`

**Suggestions for an improvement**

**Comment by shiveshr** [comment] 2019-09-30 11:24
The problem is that writer id used by the test has "/" in it. 
```
Source: Custom Source -> Timestamps/Watermarks -> Sink: Unnamed (1/1) (edited) 
```
in zookeeper based metadata store, we store writer's time at a zk path that contains writerId in the znode as the leaf node.
But if a writer id has "/" in its name then the writer-mark is stored under a different znode than expected. 
hence when we attempt to fetch the mark, we encounter deserialization error.

I can fix this by using base64 encoding of writer id for zk based metadata store.

**Comment by shiveshr** [comment] 2019-10-11 05:58
@tkaitchuck we need to add a sanity check on writerId to disallow "/". thanks

**Comment by tkaitchuck** [comment] 2020-01-24 18:39
Fixed in https://github.com/pravega/pravega/pull/4387

**Closed by tkaitchuck** 2020-01-24 18:39 UTC
Labels: area/controller, kind/bug, priority/P1, version/0.7.0
