### ISSUE TITLE
Unable to perform IO  after controller service restart in PKS / K8 environment

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#3604] opened 2019-04-10 10:52 UTC
svc output for Pravega gave following output:

```
root@osboxes:/usr/local/go/bin/src/github.com/pravega-longevity# kubectl get svc
NAME                                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)              AGE
kubernetes                              ClusterIP   10.100.200.1     <none>        443/TCP              8d
pravega-bookie-headless                 ClusterIP   None             <none>        3181/TCP             1h
pravega-pravega-controller              ClusterIP   **10.100.200.184**   <none>        10080/TCP,9090/TCP   1h
pravega-pravega-segmentstore-headless   ClusterIP   None             <none>        12345/TCP            1h
pravega-zk-client                       ClusterIP   10.100.200.206   <none>        2181/TCP             1h
pravega-zk-headless                     ClusterIP   None             <none>        2888/TCP,3888/TCP    1
```
After doing  service restart for pravega controller using following command:

`kubectl delete svc pravega-pravega-controller
`

The new IP address for controller got changed and it gave following details:

```
root@osboxes:/usr/local/go/bin/src/github.com/pravega-longevity# kubectl get svc
NAME                                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)              AGE
kubernetes                              ClusterIP   10.100.200.1     <none>        443/TCP              8d
pravega-bookie-headless                 ClusterIP   None             <none>        3181/TCP             1h
pravega-pravega-controller              ClusterIP   **10.100.200.166**   <none>        10080/TCP,9090/TCP   5m
pravega-pravega-segmentstore-headless   ClusterIP   None             <none>        12345/TCP            1h
pravega-zk-client                       ClusterIP   10.100.200.206   <none>        2181/TCP             1h
pravega-zk-headless                     ClusterIP   None             <none>        2888/TCP,3888/TCP    1h

```
**Problem description**
After the service restart, when I tried doing a small load IO operation with following config:
`./bin/IO --controller tcp://10.100.200.166:9090 --stream testSvcFault -size 100 -events 1000 -producers 3 -consumers 4 - time 600 -randomkey true -segments 10
`
 It could not be performed and gave following error in logs when ran with new controller IP:

```
[grpc-default-executor-1] WARN io.pravega.client.stream.impl.ControllerImpl - gRPC call for getSegmentsAtTime with trace id 0 failed with server error.
io.grpc.StatusRuntimeException: INTERNAL: /store/Scope/teSvcFault/truncation
        at io.grpc.Status.asRuntimeException(Status.java:530)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[epollEventLoopGroup-5-2] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Received AppendSetup WireCommands.AppendSetup(type=APPEND_SETUP, requestId=8589934592, segment=Scope/_RGteSvcFault/0.#epoch.0, writerId=6a8da3d4-2f84-4364-bac7-b6bb7e63665a, lastEventNumber=-9223372036854775808)
[epollEventLoopGroup-5-2] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection setup complete for writer 6a8da3d4-2f84-4364-bac7-b6bb7e63665a
[grpc-default-executor-1] WARN io.pravega.client.stream.impl.ControllerImpl - gRPC call for getSegmentsAtTime with trace id 0 failed with server error.
io.grpc.StatusRuntimeException: INTERNAL: /store/Scope/teSvcFault/truncation
        at io.grpc.Status.asRuntimeException(Status.java:530)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
As per my undersatnding, IO should work with new IP address of controller after restarting the service.

Deployment Details:
```
Pravega-Operator image: pravega/pravega-operator:0.3.2
Pravega build used : 0.5.0-2189.cabe11b
Zookeeper-operator image: pravega/zookeeper-operator:0.2.1
```
Environment details: PKS / K8 with medium cluster:

```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
10 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend 
```
Attaching complete logs for the reference.
[SVC Restart K8 Logs.zip](https://github.com/pravega/pravega/files/3063367/SVC.Restart.K8.Logs.zip)

**Comment by shiveshr** [comment] 2019-04-10 11:44
Could you please tell me the steps that you are performing in the test. 

In the controller logs, i see createScope being attempted, followed by create readerGroup. 
Both of these succeed. 
However, i do not see the actual stream being created. 
And when it is attempted to be accessed, we get DataNotFoundException. 
So i want to know if you created the stream before crashing the controller service?
Did you delete it too?

```
2019-04-10 09:53:55,131 9121711 [grpc-default-executor-61] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=2164924504978387199] createScope called for scope Scope.
2019-04-10 09:53:55,185 9121765 [grpc-default-executor-61] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - [requestId=-3952051722952495982] createStream called for stream Scope/_RGtestSvcFault.
2019-04-10 09:53:55,383 9121963 [controllerpool-3] INFO  i.p.c.t.Stream.StreamMetadataTasks - [requestId=-3952051722952495982] Scope/_RGtestSvcFault created in metadata store
2019-04-10 09:53:55,384 9121964 [epollEventLoopGroup-2-3] INFO  i.p.c.n.i.ClientConnectionInboundHandler - Connection established ChannelHandlerContext(ClientConnectionInboundHandler#0, [id: 0x8265a0db]) 
2019-04-10 09:53:55,385 9121965 [epollEventLoopGroup-2-3] INFO  i.p.s.p.netty.FailingReplyProcessor - Received hello: WireCommands.Hello(type=HELLO, highVersion=8, lowVersion=5)
2019-04-10 09:53:55,430 9122010 [epollEventLoopGroup-2-3] INFO  i.p.controller.server.SegmentHelper - [requestId=-3952051722952495982] CreateSegment Scope/_RGtestSvcFault/0.#epoch.0 SegmentCreated
2019-04-10 09:53:55,430 9122010 [epollEventLoopGroup-2-3] WARN  i.p.controller.server.SegmentHelper - [requestId=-3952051722952495982] CreateSegment Scope/_RGtestSvcFault/0.#epoch.0 Connection dropped
2019-04-10 09:53:55,474 9122054 [grpc-default-executor-61] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - isSegmentValid called for segment Scope/_RGtestSvcFault/0.
2019-04-10 09:53:55,482 9122062 [grpc-default-executor-61] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getDelegationToken called for stream Scope/_RGtestSvcFault.
2019-04-10 09:53:55,492 9122072 [grpc-default-executor-61] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getURI called for segment Scope/_RGtestSvcFault/0.
2019-04-10 09:53:55,531 9122111 [grpc-default-executor-61] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getDelegationToken called for stream Scope/_RGtestSvcFault.
2019-04-10 09:53:55,540 9122120 [grpc-default-executor-61] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - getURI called for segment Scope/_RGtestSvcFault/0.
2019-04-10 09:53:55,555 9122135 [controllerpool-2] ERROR i.p.c.s.r.g.v.ControllerServiceImpl - Controller api failed with error: 
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$DataNotFoundException: /store/Scope/testSvcFault/truncation
```

**Comment by Richa-Srivastava** [comment] 2019-04-10 11:57
[IO_manager.log](https://github.com/pravega/pravega/files/3063612/IO_manager.log)
[IO_worker.log](https://github.com/pravega/pravega/files/3063613/IO_worker.log)

**Comment by shiveshr** [comment] 2019-04-10 12:16
These logs do not have any reference to the stream `testSvcFault`
I do not see anywhere in controller logs or in IO worker or IO manager logs where it says this stream's creation is attempted/succeeded. 

Lets first establish what you are trying to test here.. 
Please let me know if these steps make sense:

1. run IO manager to create new stream 
2. perform some IO on the stream and verify that its working
3. stop controller service and start again
4. configure your IO tools to point to correct controller. 
5. run IO worker to perform IO on the stream

Please let me know if this is what you are testing. And if so, please share the logs from step 1 onwards for both client (IO tool logs) and controller logs from before and after restart.

**Comment by RaulGracia** [comment] 2019-04-30 21:55
@Richa-Srivastava please, could you verify if this issue is still present after #3682? This fix has been already cherry-picked for `r0.5`.

**Comment by Richa-Srivastava** [comment] 2019-05-02 04:38
@RaulGracia I will test this with new build and will update.

**Comment by sachin-j-joshi** [comment] 2019-07-08 19:03
@Richa-Srivastava is this still an issue ?

**Comment by Richa-Srivastava** [comment] 2019-07-10 05:49
@sachin-j-joshi & @RaulGracia in earlier build I didn't find any such issue but need to verify with `2299`, I'll verify with that and will update.

**Comment by Richa-Srivastava** [comment] 2019-07-15 07:01
I tried reproducing with controllers service restart and no issues found in `2299`.

**Comment by RaulGracia** [comment] 2019-07-15 07:02
Closing the issue due to no reproduction.

**Closed by RaulGracia** 2019-07-15 07:02 UTC
Labels: kind/bug, version/0.5.0
