### ISSUE TITLE
Scaling-Events REST API response is truncated

### ISSUE THREAD

**Issue by vroy** [pravega/pravega#1517] opened 2017-06-30 18:12 UTC
**Problem description**
The controller Scaling-Events REST API (`/v1/scopes/hulk/streams/smallScale/scaling-events?from=1498758856064&to=1498845256064`) is truncated at ~64000 bytes, before it is complete. The JSON is in turn invalid.

This is similar to #926. The resolution in that case was to limit the number of streams return in the list endpoint.

**Problem location**
The REST server implementation.

**Suggestions for an improvement**
Increase response size.

**Comment by fpj** [comment] 2017-07-07 08:28
Independent of how we resolve this, this is sounding like a pretty expensive call.

**Comment by Abhijeet-Jadhav** [comment] 2017-07-07 10:19
@vroy Is it okay to paginate the rest api by having `offset` and `limit` as query parameter?

**Comment by glounder** [comment] 2017-07-07 11:42
Paging isn't going to help here because we need all the data.  It just means we have to make x calls to get all the data.  Also, if the object grows in size over a couple of releases, we have the potential to see this problem again even with paging.

There should be a configuration option in your server that is truncating the size of the payload.  This can be fixed by just upping that value to something large or disabling it.

**Comment by fpj** [comment] 2017-07-07 11:47
I'm worried about increasing the response size. 64k is already a fairly large response, and I'm concerned about the effects of pulling so much data out of the controller in individual responses.

Could we step back and try to project how much data we need to transfer and how often we need to do it?

**Comment by glounder** [comment] 2017-07-07 12:04
The plan was to pull back scaling event information for the past 24 hours to show how the segments were splitting and merging within a stream.  In our tests, we had 20 active segments at any one time.  

Talking to Julia, I think the large source of the data is that every 10 minutes when scaling events are calculated, every segment is sealed and new ones are created for the same key ranges (correct me if I'm wrong here).  I think this is generating a large portion of the data.  Originally, I was expecting to see only split and merge scaling events.  Because all the segments are getting sealed and recreated, we still need those scaling events so we can get the metrics associated with that segment as well, so I don't think we can filter them out.

One option is to reduce time range of the chart to make sure we return less data.  

Besides trying to make sure we don't return too much data, I still think we should increase or remove the payload limit.  All these changes around limiting the amount of data coming back doesn't guarantee that we won't hit this issue again.

Thoughts?

**Comment by glounder** [comment] 2017-07-07 12:27
Another suggestion about the scaling events api.  From my understanding, for each scaling interval, we get the full list of segments and their key ranges.  What we really need is the initial state of the segments and then all the changes after that (which segments were sealed and which ones were created).  This would further reduce the data coming back as well.

**Comment by jkhalack** [comment] 2017-07-07 12:48
Even with the change from reporting the full list of segments for each scaling event to just the segment changes, the JSON truncation problem still remains (we currently observe more than 1000 segments being created during 24-hour period in our scaling test).

**Comment by skrishnappa** [comment] 2017-07-08 16:23
The truncation issue is due to Jersey's Netty Connector and is reported here (https://github.com/jersey/jersey/issues/3500).
The issue is observed when the server unsent buffer is greater than 8*8000 bytes.
Currently there is no fix proposed for this and suggestion is to use jersey-container-grizzly2-http instead of the netty container.

**Closed** 2017-07-19 13:32 UTC
