### ISSUE TITLE
Controller metadata cleanup

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#2186] opened 2017-12-14 12:54 UTC
**Problem description**
We have observed a couple of instances in the controller of metadata that we are not cleaning up:

- *Transaction status*: we currently do not delete zookeeper metadata for a transaction once the transaction completes. It makes sense to keep fit around at least for some time in the case the application tries to commit or abort it again, but it really depends on the semantics we want to provide.  The problem with keeping this metadata around, however, is that it uses one znode, so under high txn traffic, we will be accumulating a lot of znodes over time, which is highly undesirable.
- *Deleted segments*:  As part of the truncation work, we are now able to delete entire segments. We do keep, however, the metadata of the segment so that we know the history of segments of a stream. It is desirable to keep this metadata, for example, to avoid having a client confused about its successors.

We need a plan for addressing this issue, which consists of:

- Defining the expected semantics in each case
- Implementing the necessary cleanup mechanisms

**Problem location**
Controller.

**Suggestions for an improvement**
We need to define what kind of semantics for the points presented above and implement the corresponding mechanisms. It is highly undesirable to keep accumulating data in zookeeper, so even if we decide to keep some of this metadata permanently, we should at least move old data to Pravega segments.

**Comment by shiveshr** [comment] 2017-12-14 13:08
1. Transaction status: The original plan was to have a garbage collection logic on completed Txn (Note: we move completed txn under a separate node which can be periodically GC'd). 
A new rolling node for completed txn could be created at a fixed frequency and all txn-completed root nodes before a certain period could be purged. 

2. Deleted segments: The deleted segment's metadata will also be relevant once we have "rolling-txn" feature where a txn could exist against a truncated/deleted parent segment. 
So we may need to keep the segment information around.

**Comment by shiveshr** [comment] 2018-07-04 06:28
duplicate of #1164

**Comment by shiveshr** [comment] 2018-07-09 13:31
![](https://github.trello.services/images/mini-trello-icon.png) [1164: Clean up metadata of completed transactions](https://trello.com/c/9IMpoeYT/37-1164-clean-up-metadata-of-completed-transactions)

**Closed** 2019-02-16 07:46 UTC
Labels: area/controller, kind/enhancement, priority/P1, status/needs-attention, version/0.3.0
