### ISSUE TITLE
fix failing System test BookieFailoverTest.bookieFailoverTest

### ISSUE THREAD

**Issue by shshashwat** [pravega/pravega#6463] opened 2021-12-08 10:50 UTC
**Describe the bug**
System test BookieFailoverTest.bookieFailoverTest failing with following exception

```
java.lang.AssertionError: bookieFailoverTest test failed due to Error with message null
	at io.pravega.test.system.framework.services.kubernetes.K8SequentialExecutor.lambda$startTestExecution$4(K8SequentialExecutor.java:93)
```

**Comment by SrishT** [comment] 2022-02-16 18:16
Duplicate of https://github.com/pravega/pravega/issues/6271

**Closed by SrishT** 2022-02-16 18:16 UTC
