### ISSUE TITLE
Test failure testAppendTransientZooKeeperFailure

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1904] opened 2017-09-19 20:10 UTC
**Problem description**
We have observed a couple of failures of this test case:

```
io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogTests.testAppendTransientZooKeeperFailure
```

I´m attaching the corresponding logs.

[testAppendTransientZooKeeperFailure.txt](https://github.com/pravega/pravega/files/1315697/testAppendTransientZooKeeperFailure.txt)

**Problem location**
BookKeeperLog failure tests.

**Suggestions for an improvement**
Debug.

**Comment by andreipaduroiu** [comment] 2017-09-19 23:05
Duplicate of #1900.

**Closed by andreipaduroiu** 2017-09-19 23:05 UTC
Labels: area/server, area/testing, kind/bug, priority/P0, version/0.2
