### ISSUE TITLE
Tag ledgers created by Pravega with common metadata

### ISSUE THREAD

**Issue by eolivelli** [pravega/pravega#4442] opened 2019-12-11 23:44 UTC
**Problem description**
It would be very useful to write custom metadata on ledgers created by Pravega in order to describe the contents of the ledgers.
While creating a ledger you can set a list of key-value pairs that are stored on Zookeeper and can be read together with other standard ledgers metadata.

Several projects based on Bookkeeper (like Apache Pulsar or HerdDB) started to tag every ledger with a set of well known metadata, this is very helpful in case you are sharing a BK cluster with other applications.

It is also useful for Bookkeeper monitoring and management tools to have a description of the contents of each ledger.

The most common entries are:
- application: the general name of the application
- component: the component that created the ledger

In the case of Pravega we could have something like:
- application: pravega
- component: durablelog
- streamname: name of the stream

Having such metadata can help system recovery or custom tools for system management.

**Problem location**
Creation of ledgers

**Suggestions for an improvement**
Add 'application', 'component' and 'streamname' metadata to every ledger created from Pravega

**Comment by andreipaduroiu** [comment] 2019-12-13 23:50
Hi @eolivelli .

This is a great idea. #4431 already tags the Segment Container Id into each ledger. Perhaps we could either extend that PR with `application` and `component` or just make a new one.

**Comment by eolivelli** [comment] 2019-12-16 16:51
Adding to #4431 is fine to me.
Otherwise I can send a patch.
I left a suggestion there, to encode values as utf8 strings in order to ease tools that allow manual inspection of bk metadata.

**Comment by RaulGracia** [comment] 2020-08-05 15:38
Closing that at the moment as it looks like the issue is addressed by #4431.

**Closed by RaulGracia** 2020-08-05 15:38 UTC
