### ISSUE TITLE
Include Controller REST API as part of Standalone

### ISSUE THREAD

**Issue by chrisdail** [pravega/pravega#1322] opened 2017-05-12 14:07 UTC
**Problem description**

Standalone is a convenient way to get started with pravega. For simple non-production tests it is useful. Currently, this mode does not start the controller REST API. This means it is not possible to do basic REST API operations using standalone.

**Problem location**

Standalone startup

**Suggestions for an improvement**

Start the controller REST API as part of standalone.

**Comment by skrishnappa** [comment] 2017-05-12 15:31
Duplicate of #832

**Closed by skrishnappa** 2017-05-12 15:31 UTC
Labels: area/controller, kind/enhancement
