### ISSUE TITLE
Event based scaling stalls with RetriesExhaustedException

### ISSUE THREAD

**Issue by sumit-bm** [pravega/pravega#3833] opened 2019-05-24 18:47 UTC
While trying Event based scaling with samples, scaling stalls with `RetriesExhaustedException` after first 10 mins of segment scale.  Scale configurations are tried with 50 writter, 5 reader, min segement 30 and scale factor 4.

Pravega details:
```
Pravega version : 0.5.0-2252.c180711
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```
```
root@pravega-benchmark:/pravega-puncher/scripts# ./runFatEventScaler | grep ===
18:05:07.193 [pool-2-thread-1] INFO io.pravega.puncher.streams.scaling.ScalingCase - ============ segments: 30
18:17:07.166 [pool-2-thread-1] INFO io.pravega.puncher.streams.scaling.ScalingCase - ============ segments: 53
Exception in thread "Thread-51" java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
        at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
        at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.handleRequest(SegmentInputStreamImpl.java:137)
        at io.pravega.client.segment.impl.SegmentInputStreamImpl.read(SegmentInputStreamImpl.java:122)
        at io.pravega.client.segment.impl.EventSegmentReaderImpl.readEvent(EventSegmentReaderImpl.java:75)
        at io.pravega.client.segment.impl.EventSegmentReaderImpl.read(EventSegmentReaderImpl.java:62)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:117)
        at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:90)
        at io.pravega.puncher.streams.scaling.ScaledEventReader.run(ScaledEventReader.java:41)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
```
Segment stores are showing following exceptions on these streams repeatedly: 
```
2019-05-24 18:39:46,006 253008127 [core-9] INFO  i.p.s.s.h.handler.AppendProcessor - Segment 'puncherScope3/puncherStream3/6.#epoch.0' is sealed and cddc038c-7921-4ba5-a853-3e73340edb33 cannot perform operation 'appending data'.
2019-05-24 18:39:46,105 253008226 [epollEventLoopGroup-11-3] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection:
io.netty.handler.codec.DecoderException: io.pravega.shared.protocol.netty.InvalidMessageException: AppendBlockEnd without AppendBlock.
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.shared.protocol.netty.InvalidMessageException: AppendBlockEnd without AppendBlock.
        at io.pravega.shared.protocol.netty.AppendDecoder.processCommand(AppendDecoder.java:102)
        at io.pravega.shared.protocol.netty.AppendDecoder.decode(AppendDecoder.java:55)
        at io.pravega.shared.protocol.netty.AppendDecoder.decode(AppendDecoder.java:36)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
        ... 28 common frames omitted
```

**Comment by RaulGracia** [comment] 2019-05-25 11:05
@sumit-bm note that the `AppendBlockEnd without AppendBlock` issue has been fixed in #3820 and cherry-picked to `r0.5`. Please, reproduce the experiment with the last version of `0.5` or `master` to verify if the issue is still present.

**Comment by sumit-bm** [comment] 2019-05-25 12:33
@RaulGracia @fpj I have tested with latest build `0.5.0-2260.b477eec` and event based scaling exercise and received following exception.

[pravega-k8s-logging-2019-05-24-16-45-39.zip](https://github.com/pravega/pravega/files/3219381/pravega-k8s-logging-2019-05-24-16-45-39.zip)


```
2019-05-24 20:27:37,473 3375911 [epollEventLoopGroup-10-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x919fd725, L:/172.24.111.16:12345] READ: [id: 0x5f81f98f, L:/172.24.111.16:12345 - R:/172.24.111.17:48392]
2019-05-24 20:27:37,476 3375914 [epollEventLoopGroup-10-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x919fd725, L:/172.24.111.16:12345] READ COMPLETE
2019-05-24 20:27:37,476 3375914 [epollEventLoopGroup-11-6] INFO  i.p.s.s.h.handler.AppendProcessor - Received hello from connection: [id: 0x5f81f98f, L:/172.24.111.16:12345 - R:/172.24.111.17:48392]
2019-05-24 20:27:37,477 3375915 [epollEventLoopGroup-11-6] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: 9095a759-d8e4-4f22-b0e2-660c985edab8 on segment: puncherScope3/puncherStream3/1.#epoch.0
2019-05-24 20:27:37,578 3376016 [epollEventLoopGroup-11-6] WARN  i.p.s.protocol.netty.AppendDecoder - Received AppendBlockEnd WireCommands.AppendBlockEnd(type=APPEND_BLOCK_END, writerId=9095a759-d8e4-4f22-b0e2-660c985edab8, sizeOfWholeEvents=0, data=EmptyByteBufBE, numEvents=444, lastEventNumber=3066242, requestId=85899345920) without AppendBlock
2019-05-24 20:27:37,579 3376017 [epollEventLoopGroup-11-6] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection:
io.netty.handler.codec.DecoderException: io.pravega.shared.protocol.netty.InvalidMessageException: AppendBlockEnd without AppendBlock.
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.shared.protocol.netty.InvalidMessageException: AppendBlockEnd without AppendBlock.
        at io.pravega.shared.protocol.netty.AppendDecoder.processCommand(AppendDecoder.java:106)
        at io.pravega.shared.protocol.netty.AppendDecoder.decode(AppendDecoder.java:57)
        at io.pravega.shared.protocol.netty.AppendDecoder.decode(AppendDecoder.java:37)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
        ... 28 common frames omitted
```

**Comment by fpj** [comment] 2019-05-25 15:44
What’s the version of the Pravega client in the test harness you used?

**Comment by sumit-bm** [comment] 2019-05-25 17:22
Event scale samples were built on `0.5.0-2252.c180711-SNAPSHOT` as it was giving build failure with `0.5.0-2260.b477eec-SNAPSHOT` while creating fat jar. 
```
Could not resolve all files for configuration ':scaling:compileClasspath'.
```

**Comment by RaulGracia** [comment] 2019-05-25 17:31
If you want to do a quick test with the right version of Pravega that includes PR 3820 you have two options:
i) Use a `0.6.0` artifact (`master`) that includes it (e.g., `0.6.0-50.8583d93-SNAPSHOT/`).
ii) Clone (`git clone -b r0.5 https://github.com/pravega/pravega`) and install locally (`./gradlew install`) the last version of `0.5` and then build the samples pointing to your local version (check the artifact name at the local maven cache `./m2/.../io/pravega/`).
The issue is that our build are not publishing artifacts from branches, and this is something that may need to be revisited.

**Comment by sumit-bm** [comment] 2019-05-25 17:37
@RaulGracia Those builds are not a problem. 
I have local repo under `.m2/../io/pravege/pravega-client
/0.5.0-2260.b477eec-SNAPSHOT`. But we have to understand here PKS is also involved and event scaling samples used is not getting build using `0.5.0-2260.b477eec-SNAPSHOT`. It is giving following issue: 
```
> Could not find io.pravega:pravega-client:0.5.0-2260.b477eec-SNAPSHOTT.
  Searched in the following locations:
      file:/root/.m2/repository/io/pravega/pravega-client/0.5.0-2260.b477eec-SNAPSHOTT/pravega-client-0.5.0-2260.b477eec-SNAPSHOTT.pom
      file:/root/.m2/repository/io/pravega/pravega-client/0.5.0-2260.b477eec-SNAPSHOTT/pravega-client-0.5.0-2260.b477eec-SNAPSHOTT.jar
      https://jcenter.bintray.com/io/pravega/pravega-client/0.5.0-2260.b477eec-SNAPSHOTT/pravega-client-0.5.0-2260.b477eec-SNAPSHOTT.pom
      https://jcenter.bintray.com/io/pravega/pravega-client/0.5.0-2260.b477eec-SNAPSHOTT/pravega-client-0.5.0-2260.b477eec-SNAPSHOTT.jar
      https://repo.maven.apache.org/maven2/io/pravega/pravega-client/0.5.0-2260.b477eec-SNAPSHOTT/pravega-client-0.5.0-2260.b477eec-SNAPSHOTT.pom
      https://repo.maven.apache.org/maven2/io/pravega/pravega-client/0.5.0-2260.b477eec-SNAPSHOTT/pravega-client-0.5.0-2260.b477eec-SNAPSHOTT.jar
      https://repository.apache.org/snapshots/io/pravega/pravega-client/0.5.0-2260.b477eec-SNAPSHOTT/pravega-client-0.5.0-2260.b477eec-SNAPSHOTT.pom
      https://repository.apache.org/snapshots/io/pravega/pravega-client/0.5.0-2260.b477eec-SNAPSHOTT/pravega-client-0.5.0-2260.b477eec-SNAPSHOTT.jar
  Required by:
      project :scaling
> Could not find io.pravega:pravega-common:0.5.0-2260.b477eec-SNAPSHOTT.
  Searched in the following locations:
      file:/root/.m2/repository/io/pravega/pravega-common/0.5.0-2260.b477eec-SNAPSHOTT/pravega-common-0.5.0-2260.b477eec-SNAPSHOTT.pom
      file:/root/.m2/repository/io/pravega/pravega-common/0.5.0-2260.b477eec-SNAPSHOTT/pravega-common-0.5.0-2260.b477eec-SNAPSHOTT.jar
      https://jcenter.bintray.com/io/pravega/pravega-common/0.5.0-2260.b477eec-SNAPSHOTT/pravega-common-0.5.0-2260.b477eec-SNAPSHOTT.pom
      https://jcenter.bintray.com/io/pravega/pravega-common/0.5.0-2260.b477eec-SNAPSHOTT/pravega-common-0.5.0-2260.b477eec-SNAPSHOTT.jar
      https://repo.maven.apache.org/maven2/io/pravega/pravega-common/0.5.0-2260.b477eec-SNAPSHOTT/pravega-common-0.5.0-2260.b477eec-SNAPSHOTT.pom
      https://repo.maven.apache.org/maven2/io/pravega/pravega-common/0.5.0-2260.b477eec-SNAPSHOTT/pravega-common-0.5.0-2260.b477eec-SNAPSHOTT.jar
      https://repository.apache.org/snapshots/io/pravega/pravega-common/0.5.0-2260.b477eec-SNAPSHOTT/pravega-common-0.5.0-2260.b477eec-SNAPSHOTT.pom
      https://repository.apache.org/snapshots/io/pravega/pravega-common/0.5.0-2260.b477eec-SNAPSHOTT/pravega-common-0.5.0-2260.b477eec-SNAPSHOTT.jar
  Required by:
      project :scaling
```
Also one question, does  pravega-client same version absolute necessity here? Pravega client are backward compatible so this should work as well.

**Comment by sumit-bm** [comment] 2019-05-25 17:45
@RaulGracia Let me re-check again.

**Comment by RaulGracia** [comment] 2019-05-25 18:26
@sumit-bm the fix of PR #3820 is for the client (i.e., `client/src/main/java/io/pravega/client/...`), so if you are not making use of the client version of Pravega everywhere, means that you are not using this PR.

**Comment by sumit-bm** [comment] 2019-05-25 19:14
@RaulGracia @fpj I could rebuilt event scaler with latest client `0.5.0-2260.b477eec-SNAPSHOT` and I am so far not received `AppendBlockEnd without AppendBlock`

I have got following 2 exceptions frequently while segment scaling now: 

```
2019-05-25 19:09:06,291 4890372 [core-6] WARN  i.p.s.s.h.handler.AppendProcessor - Bad attribute update by af53e409-cfba-4b21-84b2-6b38fbf33b84 on segment puncherScope2/puncherStream2/70.#epoch.0.
io.pravega.segmentstore.contracts.BadAttributeUpdateException: [Segment 'puncherScope2/puncherStream2/70.#epoch.0'] Bad Attribute Update (AttributeId = af53e409-cfba-4b21-84b2-6b38fbf33b84, Value = 32, UpdateType = ReplaceIfEquals): Expected existing value to be '31', actual '32'..
        at io.pravega.segmentstore.server.logs.SegmentMetadataUpdateTransaction.preProcessAttributes(SegmentMetadataUpdateTransaction.java:463)
        at io.pravega.segmentstore.server.logs.SegmentMetadataUpdateTransaction.preProcessOperation(SegmentMetadataUpdateTransaction.java:270)
        at io.pravega.segmentstore.server.logs.ContainerMetadataUpdateTransaction.preProcessOperation(ContainerMetadataUpdateTransaction.java:312)
        at io.pravega.segmentstore.server.logs.OperationMetadataUpdater.preProcessOperation(OperationMetadataUpdater.java:224)
        at io.pravega.segmentstore.server.logs.OperationProcessor.processOperation(OperationProcessor.java:358)
        at io.pravega.segmentstore.server.logs.OperationProcessor.processOperations(OperationProcessor.java:282)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-05-25 19:09:06,291 4890372 [epollEventLoopGroup-11-3] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.nio.channels.ClosedChannelException: null
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
```
And 
```
2019-05-25 18:14:18,242 1602323 [epollEventLoopGroup-11-4] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: b31fad64-d6c9-4c20-b2b4-db7ee61f5a3c on segment: puncherScope/puncherStream/8.#epoch.3
2019-05-25 18:14:18,248 1602329 [storage-io-76] INFO  i.p.s.s.a.SegmentAttributeBTreeIndex - AttributeIndex[71]: Sealed.
2019-05-25 18:14:18,248 1602329 [epollEventLoopGroup-11-7] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=493] Reading from table WireCommands.ReadTable(type=READ_TABLE, requestId=493, segment=_system/_tables/puncherScope/puncherStream/metadata.#.84356a0d-ae3d-4cf7-b656-c4efea9c7478, delegationToken=, keys=[WireCommands.TableKey(data=UnpooledHeapByteBuf(ridx: 0, widx: 28, cap: 28/28), keyVersion=-9223372036854775808)]).
2019-05-25 18:14:18,251 1602332 [epollEventLoopGroup-11-1] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=494] Updating table segment WireCommands.UpdateTableEntries(type=UPDATE_TABLE_ENTRIES, requestId=494, segment=_system/_tables/puncherScope/puncherStream/metadata.#.84356a0d-ae3d-4cf7-b656-c4efea9c7478, delegationToken=, tableEntries=WireCommands.TableEntries(entries=[WireCommands.TableKey(data=UnpooledHeapByteBuf(ridx: 0, widx: 28, cap: 28/28), keyVersion=2769)=WireCommands.TableValue(data=UnpooledHeapByteBuf(ridx: 0, widx: 57, cap: 57/57))])).
2019-05-25 18:14:18,258 1602339 [core-28] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[14]: MapStreamSegment SegmentId = 31, Name = 'puncherScope/puncherStream/8.#epoch.3', Active = 3
2019-05-25 18:14:18,259 1602340 [epollEventLoopGroup-11-1] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: b31fad64-d6c9-4c20-b2b4-db7ee61f5a3c on segment: puncherScope/puncherStream/8.#epoch.3
2019-05-25 18:14:18,260 1602341 [epollEventLoopGroup-10-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xb914c2dc, L:/172.24.111.15:12345] READ: [id: 0x2d03e357, L:/172.24.111.15:12345 - R:/172.24.111.17:42654]
2019-05-25 18:14:18,260 1602341 [epollEventLoopGroup-10-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xb914c2dc, L:/172.24.111.15:12345] READ COMPLETE
2019-05-25 18:14:18,264 1602345 [epollEventLoopGroup-11-2] INFO  i.p.s.s.h.handler.AppendProcessor - Received hello from connection: [id: 0x2d03e357, L:/172.24.111.15:12345 - R:/172.24.111.17:42654]
2019-05-25 18:14:18,264 1602345 [epollEventLoopGroup-11-2] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: 85f85026-f517-4cb6-a513-aafa853ebbf2 on segment: puncherScope/_RGscalingReaders/0.#epoch.0
2019-05-25 18:14:18,286 1602367 [epollEventLoopGroup-11-6] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=495] Reading from table WireCommands.ReadTable(type=READ_TABLE, requestId=495, segment=_system/_tables/puncherScope/puncherStream/metadata.#.84356a0d-ae3d-4cf7-b656-c4efea9c7478, delegationToken=, keys=[WireCommands.TableKey(data=UnpooledHeapByteBuf(ridx: 0, widx: 18, cap: 18/18), keyVersion=-9223372036854775808)]).
2019-05-25 18:14:18,287 1602368 [epollEventLoopGroup-11-8] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=496] Updating table segment WireCommands.UpdateTableEntries(type=UPDATE_TABLE_ENTRIES, requestId=496, segment=_system/_tables/puncherScope/puncherStream/metadata.#.84356a0d-ae3d-4cf7-b656-c4efea9c7478, delegationToken=, tableEntries=WireCommands.TableEntries(entries=[WireCommands.TableKey(data=UnpooledHeapByteBuf(ridx: 0, widx: 18, cap: 18/18), keyVersion=2855)=WireCommands.TableValue(data=UnpooledHeapByteBuf(ridx: 0, widx: 4, cap: 4/4))])).
2019-05-25 18:14:18,298 1602379 [storage-io-38] INFO  i.p.s.server.CacheManager - CacheManager Registered AttributeIndex[31].
2019-05-25 18:14:18,310 1602391 [epollEventLoopGroup-11-5] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection:
java.lang.IllegalStateException: Data from unexpected connection: aaa0ef64-6992-4355-b695-23f7dbadcbeb.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:588)
```

**Comment by fpj** [comment] 2019-05-26 07:35
The first exception is indicating that the expected even number is different and the second that the connection is no longer valid, the writer has moved to a different connection. The timestamps do not match, so I can't really tell the whole story. But, this behavior is overall expected, can you confirm that there is progress despite these exceptions?

These exceptions shouldn't be happening too frequently. If they are, then we need to see why there is so much connection flapping, but otherwise, again, it should be harmless.

**Comment by fpj** [comment] 2019-06-04 10:17
The bad attribute exception might have been fixed in #3775, please validate.

**Comment by andreipaduroiu** [comment] 2019-06-04 13:43
#3775 had nothing to do with `BadAttributeException`; it just cleaned up all the data when deleting a segment.

**Comment by sumit-bm** [comment] 2019-06-10 13:10
Retested with build# 0.5.0-2269.6f8a820 and couldn't reproduce the issue

**Comment by andreipaduroiu** [comment] 2019-06-10 16:44
I'm closing this due to not being able to reproduce. Please create a new issue and attach new logs if this happens again.

**Closed by andreipaduroiu** 2019-06-10 16:44 UTC
Labels: kind/bug, priority/P1, version/0.5.0
