### ISSUE TITLE
IO stalled post successful  cluster Upgrade between Minor versions

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#4353] opened 2019-11-12 06:50 UTC
**There were several Upgrade done on the cluster as mentioned in Version History. Also did Operator upgrade twice. All the operations were successful with IO running in background on `0.6.0-2408.7312399` version.**
```
Version History:
    0.6.0-2408.7312399
    0.6.0-2401.83b62b8
    0.6.0-2408.7312399
    0.6.0-2395.c87f623
    0.6.0-2408.7312399
```
After last Upgrade which was done from 0.6.0-2395.c87f623 to 0.6.0-2408.7312399, where Longevity IO was running on `0.6.0-2408.7312399` version, It got stalled and it never resumed :
```
INFO  [2019-11-11 11:52:12,548] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:353,548, events/sec:37, KB/sec:28.410156
INFO  [2019-11-11 11:52:12,548] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:353,548, events/sec:37, KB/sec:28.410156
INFO  [2019-11-11 11:52:12,548] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:353,548, events/sec:37, KB/sec:28.410156
INFO  [2019-11-11 11:52:42,551] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:354,643, events/sec:37, KB/sec:28.40918
INFO  [2019-11-11 11:52:42,551] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:354,643, events/sec:37, KB/sec:28.40918
INFO  [2019-11-11 11:52:42,551] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:354,643, events/sec:37, KB/sec:28.498047
INFO  [2019-11-11 11:52:42,551] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:354,643, events/sec:37, KB/sec:28.498047
INFO  [2019-11-11 11:53:12,551] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:354,968, events/sec:36, KB/sec:28.345703
INFO  [2019-11-11 11:53:12,551] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:354,968, events/sec:36, KB/sec:28.345703
INFO  [2019-11-11 11:53:12,551] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:354,968, events/sec:36, KB/sec:28.345703
INFO  [2019-11-11 11:53:12,551] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:354,968, events/sec:36, KB/sec:28.345703
INFO  [2019-11-11 11:53:42,549] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:354,968, events/sec:36, KB/sec:28.257812
INFO  [2019-11-11 11:53:42,549] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:354,968, events/sec:36, KB/sec:28.257812
INFO  [2019-11-11 11:53:42,549] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:354,968, events/sec:36, KB/sec:28.345703
INFO  [2019-11-11 11:53:42,549] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:354,968, events/sec:36, KB/sec:28.345703
INFO  [2019-11-11 11:54:12,548] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:354,968, events/sec:36, KB/sec:28.169922
```
Following is the Operator logs for successful upgrade:
```
2019/11/11 11:06:52 Updating version history adding version 0.6.0-2408.7312399
time="2019-11-11T11:06:52Z" level=info msg="Upgrade completed for all pravega components."
time="2019-11-11T11:06:52Z" level=info msg="Reconciling PravegaCluster default/pravega\n"
time="2019-11-11T11:06:52Z" level=info msg="syncing to version '0.6.0-2408.7312399' completed"
time="2019-11-11T11:06:52Z" level=info msg="Webhook is handling incoming requests"
time="2019-11-11T11:06:52Z" level=info msg="Webhook is handling incoming requests"
```
Pravega config:
```
bookkeeper:0.6.0-2408.7312399
pravega:0.6.0-2408.7312399
pravega/pravega-operator:0.4.2
pravega/zookeeper:0.2.4
pravega/zookeeper-operator:0.2.4
```
Uploading Metrics details and K8 logs on corresponding Jira.

**Comment by shrids** [comment] 2019-11-12 15:17
- The upgrade from  0.6.0-2401.83b62b8 to 0.6.0-2408.7312399 worked fine.

- The next test performed was from an upgrade from ` 0.6.0-2395.c87f623` to `0.6.0-2408.7312399` and with this upgrade, the longevity reads and writes stopped progressing post `2019-11-11 11:53:12,551`. The longevity was using txns for reading and writing for this run.
```
172.28.43.3 - - [11/Nov/2019:11:52:42 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 1208 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 5
INFO  [2019-11-11 11:53:12,551] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 2h 40m
INFO  [2019-11-11 11:53:12,551] io.pravega.longevity.utils.PerformanceUtils: Writers (1/1): events:354,968, events/sec:36, KB/sec:28.345703
INFO  [2019-11-11 11:53:12,551] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 23517, perSec:1.2380208333333333, committed:11885, failed:0, aborted:11631, aborted but read: 0
INFO  [2019-11-11 11:53:12,551] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 64,841, average block time (ms): 52
INFO  [2019-11-11 11:53:12,551] io.pravega.longevity.utils.PerformanceUtils: Readers (1/1): events:354,968, events/sec:36, KB/sec:28.345703
```
- From the logs Pravega was upgraded @ around 2019-11-11 11:05:17,011 293**
```
// start logs snippets.
./oldlogs_pravega-pravega-segmentstore-0/segmentstore_2019-11-11.0.log:2019-11-11 11:05:17,011 293  [main] INFO  i.p.s.server.host.ServiceStarter - Segment store configuration:
./oldlogs_pravega-pravega-segmentstore-1/segmentstore_2019-11-11.0.log:2019-11-11 11:05:43,488 299  [main] INFO  i.p.s.server.host.ServiceStarter - Segment store configuration:
./oldlogs_pravega-pravega-segmentstore-2/segmentstore_2019-11-11.0.log:2019-11-11 11:06:12,806 306  [main] INFO  i.p.s.server.host.ServiceStarter - Segment store configuration:

./oldlogs_pravega-pravega-controller-6cbf86b5f4-kx666/controller_2019-11-11.0.log:2019-11-11 11:06:31,834 328  [main] INFO  io.pravega.controller.util.Config - Controller configuration:
./oldlogs_pravega-pravega-controller-6cbf86b5f4-l66s4/controller_2019-11-11.0.log:2019-11-11 11:06:24,127 325  [main] INFO  io.pravega.controller.util.Config - Controller configuration:
```
This implies the upgrade was successful. Transaction IOs did work for 50 mins post the upgrade.

Findings on the why the longevity did not proceed further post 50 mins of the run --> 

- The last transaction to be created by the longevity test is // Create transaction invoked @ 2019-11-11 11:52:53,575 2789773 
```
./controller_2019-11-11.44.log:2019-11-11 11:52:53,575 2789773 [grpc-default-executor-17] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - createTransaction called for stream longevity/smallScaleTxBytes
```
The transaction id is 0000001b-0000-0000-0000-00000000dc6a  lowbits: 56426 highBits: 115964116992
All 14 segments were created as part of the transaction at around :2019-11-11 11:52:53,603
```
grep -r "CREATE_SEGMENT" ./ | grep "#transaction.0000001b00000000000000000000dc6a" | wc -l
14
```
- Setup appends  were invoked only for the 4 transaction segments since the test has writes for these segments.(This implies the test did initiate writes)
```
./oldlogs_pravega-pravega-segmentstore-0/segmentstore_2019-11-11.8.log:2019-11-11 11:52:53,624 2856906 [epollEventLoopGroup-11-4] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: f75ae94d-a12c-4213-bed2-81d422e8954a on segment: longevity/smallScaleTxBytes/24.#epoch.27#transaction.0000001b00000000000000000000dc6a
./oldlogs_pravega-pravega-segmentstore-1/segmentstore_2019-11-11.15.log:2019-11-11 11:52:53,645 2830456 [epollEventLoopGroup-11-3] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: 864ed7fd-99bb-41bb-af53-ede2a531f65f on segment: longevity/smallScaleTxBytes/17.#epoch.27#transaction.0000001b00000000000000000000dc6a
./oldlogs_pravega-pravega-segmentstore-1/segmentstore_2019-11-11.15.log:2019-11-11 11:52:53,684 2830495 [epollEventLoopGroup-11-4] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: c7e60451-cadd-4159-bde0-4147eb76ad79 on segment: longevity/smallScaleTxBytes/29.#epoch.27#transaction.0000001b00000000000000000000dc6a
./oldlogs_pravega-pravega-segmentstore-2/segmentstore_2019-11-11.9.log:2019-11-11 11:52:53,667 2801167 [epollEventLoopGroup-11-8] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: 22224c10-e05d-419a-8d28-71ffdc215986 on segment: longevity/smallScaleTxBytes/27.#epoch.27#transaction.0000001b00000000000000000000dc6a
```
- Pings for these transactions was routinely sent and was received and processed by the controller,  as perf configuration.
- The longevity test also invokes check transaction regularly and the transaction status was appropriately sent.
- Commit Transaction for this was never invoked by the test and the test never proceeds further in creating newer transactions too..

- The transaction(id: 0000001b00000000000000000000dc6a)  was aborted around 2019-11-11 20:12:43,174 32779372  around 8 hours since the transaction was created.
```
    2019-11-11 20:12:43,174 32779372 [epollEventLoopGroup-2-4] INFO  i.p.controller.server.SegmentHelper - Closing connection as a result of receiving: WireCommands.SegmentDeleted(type=SEGMENT_DELETED, requestId=5018209723875328, segment=longevity/smallScaleTxBytes/19.#epoch.27#transaction.0000001b00000000000000000000dc6a) // all the segments were deleted.
```

**Summary:**
- Upgrade was successful and IO did happen after upgrade. The longevity failed after 50 mins post the upgrade.
- The longevity test stopped and did not invoke any new transaction. From the available logs the no commit transaction was invoked for the last transaction and hence the test did not proceed further.
- IO stall is due to the test not creating transactions. Interestingly commitTransaction for the last transaction is never seen on the controllers. We will not be able to root cause it without the worker logs during the timestamp mentioned previously.

**Comment by shrids** [comment] 2019-11-14 07:04
Closing this issue due to the following reasons:

1. The upgrade did work fine and IOs did happen post-upgrade.
2. From the SSS and controller logs, we can observe that the transaction was created, the client did send SETUP_APPEND commands. 
3. The test did not invoke either the commit/abort transaction for the next 8 hours.
4. The client did send the periodic ping transactions for the next 8 hours before the transaction was aborted by the controller since the transaction exceeded the max duration.
5. The test did invoke the check transaction status periodically and it was responded with the right response for the 8 hours the transaction was open.
6. No specific errors on the SSS which indicates any issues. From the SSS logs we can see that the CREATE_SEGMENT operation during transaction creation, SETUP_APPEND operation before writing to and DELETE_SEGMENT when the transaction is aborted(after 8 hours) did happen as expected.

Based on the above points we can observe Pravega components did work fine. We would need the worker logs to understand why a commit transaction was not invoked by the application

**Closed by shrids** 2019-11-14 07:04 UTC
Labels: status/more-info-needed, version/0.6.0, version/0.7.0
