### ISSUE TITLE
RetriesExhaustedException while connecting to a newly created segment

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#2792] opened 2018-07-26 19:19 UTC
**Problem description**
With updating to pravega commit `c619054`, our `smallScaleYoung` test started showing reader failures that did not happen with `0.3.0` pravega.
The `smallScaleYoung` has a writer group writing non-transactional events into `hulk/smallScaleYoung` stream that has event-rate based scaling policy, and autoscaling is happening all the time. There is one reader group of three TAIL readers that reads from the stream.
At some point in time one of the readers would fail with `io.pravega.common.util.RetriesExhaustedException`:

```
2018-07-25 20:16:28,879 157606046 [pool-8-thread-2] ERROR c.e.n.h.t.w.readers.PravegaReader - Reader finished with Error
java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
	at java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
	at java.util.concurrent.CompletableFuture.join(Unknown Source)
	at io.pravega.client.segment.impl.SegmentInputStreamImpl.handleRequest(SegmentInputStreamImpl.java:172)
	at io.pravega.client.segment.impl.SegmentInputStreamImpl.readEventData(SegmentInputStreamImpl.java:141)
	at io.pravega.client.segment.impl.SegmentInputStreamImpl.read(SegmentInputStreamImpl.java:111)
	at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:104)
	at com.emc.nautilus.hulk.taskexecutor.workers.readers.PravegaReader.start(PravegaReader.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
	at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$null$6(Retry.java:245)
	at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.failAllInflight(AsyncSegmentInputStreamImpl.java:239)
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.closeConnection(AsyncSegmentInputStreamImpl.java:211)
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.access$100(AsyncSegmentInputStreamImpl.java:40)
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.connectionDropped(AsyncSegmentInputStreamImpl.java:60)
```

The failure is a result of the reader failing to connect to a newly created segment.
Here is segment `hulk/smallScaleYoung/2453.#epoch.1592` being created at 20:14:46,990:
```
2018-07-25 20:14:46,990 157504157 [grpc-default-executor-1395] DEBUG i.p.c.stream.impl.ControllerImpl - Received the following data from the controller [segment {
  segmentId {
    streamInfo {
      scope: "hulk"
      stream: "smallScaleYoung"
    }
    segmentId: 6837587937685
  }
  maxKey: 0.22530785053527153
}
value: 6777458395519
value: 6777458395520
]
2018-07-25 20:14:46,990 157504157 [epollEventLoopGroup-2-23] DEBUG i.p.c.n.i.ClientConnectionInboundHandler - 172.16.15.23 processing reply: WireCommands.DataAppended(type=DATA_APPENDED, writerId=452ef418-c4de-498b-8755-dc36b9a3fb99, eventNumber=283, previousEventNumber=282)
2018-07-25 20:14:46,990 157504157 [ScalingRetransmition-hulk/smallScaleYoung-1389] DEBUG i.p.c.stream.impl.SegmentSelector - Creating writer for segment hulk/smallScaleYoung/2453.#epoch.1592
2018-07-25 20:14:46,990 157504157 [ScalingRetransmition-hulk/smallScaleYoung-1389] DEBUG i.p.c.s.i.SegmentOutputStreamImpl - (Re)connect invoked, Segment: hulk/smallScaleYoung/2453.#epoch.1592, writerID: 1f4789bc-f12f-4afa-b7c1-bb791e342363
2018-07-25 20:14:46,990 157504157 [ScalingRetransmition-hulk/smallScaleYoung-1389] DEBUG i.p.common.util.ReusableFutureLatch - Running releaser now, runningThread:ScalingRetransmition-hulk/smallScaleYoung-1389
2018-07-25 20:14:46,991 157504158 [clientInternal-10] DEBUG i.p.c.s.i.SegmentOutputStreamImpl - Running reconnect for segment:hulk/smallScaleYoung/2453.#epoch.1592 writerID: 1f4789bc-f12f-4afa-b7c1-bb791e342363
2018-07-25 20:14:46,991 157504158 [ScalingRetransmition-hulk/smallScaleYoung-1389] DEBUG i.p.c.stream.impl.SegmentSelector - Fetch unacked events for segment: hulk/smallScaleYoung/2432.#epoch.1578, and adding new segments StreamSegments:{0.22530785053527153=hulk/smallScaleYoung/2453.#epoch.1592, 0.37468351753621515=hulk/smallScaleYoung/2443.#epoch.1585, 0.43267882291690607=hulk/smallScaleYoung/2449.#epoch.1589, 0.49067412829759693=hulk/smallScaleYoung/2450.#epoch.1589, 0.5498491625708387=hulk/smallScaleYoung/2451.#epoch.1590, 0.5597116682830456=hulk/smallScaleYoung/2441.#epoch.1584, 0.5695741739952527=hulk/smallScaleYoung/2442.#epoch.1584, 0.5958741892278046=hulk/smallScaleYoung/2376.#epoch.1542, 0.6126816436154293=hulk/smallScaleYoung/2382.#epoch.1546, 0.6210853708092416=hulk/smallScaleYoung/2424.#epoch.1574, 0.6294890980030541=hulk/smallScaleYoung/2425.#epoch.1574, 0.6378289963413443=hulk/smallScaleYoung/2444.#epoch.1586, 0.6461688946796345=hulk/smallScaleYoung/2445.#epoch.1586, 0.6555216679667181=hulk/smallScaleYoung/2438.#epoch.1582, 0.6648744412538017=hulk/smallScaleYoung/2439.#epoch.1582, 0.6835799878279689=hulk/smallScaleYoung/2396.#epoch.1555, 0.7209910809763033=hulk/smallScaleYoung/2345.#epoch.1521, 0.7958132672729721=hulk/smallScaleYoung/2333.#epoch.1514, 0.8637641048447001=hulk/smallScaleYoung/2306.#epoch.1498, 0.880751814237632=hulk/smallScaleYoung/2325.#epoch.1509, 0.8892456689340981=hulk/smallScaleYoung/2452.#epoch.1591, 0.8977395236305641=hulk/smallScaleYoung/2434.#epoch.1579, 0.923304642722923=hulk/smallScaleYoung/2413.#epoch.1567, 0.9296959224960127=hulk/smallScaleYoung/2436.#epoch.1581, 0.9328915623825575=hulk/smallScaleYoung/2446.#epoch.1587, 0.9360872022691025=hulk/smallScaleYoung/2447.#epoch.1587, 1.0=hulk/smallScaleYoung/2448.#epoch.1588}
```

Segment is assigned to reader group at 20:14:47,027:
```
2018-07-25 20:14:47,027 157504194 [pool-8-thread-2] DEBUG i.p.c.s.i.ReaderGroupStateManager - Marking segment hulk/smallScaleYoung/2431.#epoch.1578 as completed in reader group. CurrentState is: ReaderGroupState{ CheckpointState { ongoingCheckpoints: [faf80fba-1d5d-46a8-9915-ad38f83b8b53],  readersBlockingEachCheckpoint: {} } futureSegments: {hulk/smallScaleYoung/2453.#epoch.1592=[6777458395519]} assignedSegments: {HulkSmallScaleYoung8230d88190cd47418757fce7e3a23193={hulk/smallScaleYoung/2447.#epoch.1587=0, hulk/smallScaleYoung/2442.#epoch.1584=0, hulk/smallScaleYoung/2443.#epoch.1585=0, hulk/smallScaleYoung/2448.#epoch.1588=0, hulk/smallScaleYoung/2413.#epoch.1567=0, hulk/smallScaleYoung/2434.#epoch.1579=0, hulk/smallScaleYoung/2436.#epoch.1581=0}, HulkSmallScaleYounge9af1571ec014545a9bdb0d7015c66ee={hulk/smallScaleYoung/2446.#epoch.1587=0, hulk/smallScaleYoung/2425.#epoch.1574=218574, hulk/smallScaleYoung/2424.#epoch.1574=0, hulk/smallScaleYoung/2451.#epoch.1590=0, hulk/smallScaleYoung/2439.#epoch.1582=0, hulk/smallScaleYoung/2441.#epoch.1584=0}, HulkSmallScaleYoung3e22cf30b01c4b3caa51726e567e171f={hulk/smallScaleYoung/2445.#epoch.1586=0, hulk/smallScaleYoung/2444.#epoch.1586=0, hulk/smallScaleYoung/2431.#epoch.1578=0, hulk/smallScaleYoung/2449.#epoch.1589=0, hulk/smallScaleYoung/2452.#epoch.1591=0, hulk/smallScaleYoung/2438.#epoch.1582=0, hulk/smallScaleYoung/2401.#epoch.1558=0, hulk/smallScaleYoung/2450.#epoch.1589=0}} unassignedSegments: {} }
```

And here the segment is acquired by a reader, then the reader connects at 20:14:47,074, and  then  the connection is closed at 20:14:47,080:
```
2018-07-25 20:14:47,055 157504222 [pool-8-thread-2] INFO  i.p.c.s.impl.EventStreamReaderImpl - EventStreamReaderImpl( id=HulkSmallScaleYoung3e22cf30b01c4b3caa51726e567e171f) acquiring segments {hulk/smallScaleYoung/2453.#epoch.1592=0}
...
2018-07-25 20:14:47,074 157504241 [epollEventLoopGroup-5-1] INFO  i.p.c.n.i.ClientConnectionInboundHandler - Connection established ChannelHandlerContext(ClientConnectionInboundHandler#0, [id: 0xccb83359]) 
2018-07-25 20:14:47,074 157504241 [epollEventLoopGroup-5-1] DEBUG i.p.c.n.impl.ConnectionFactoryImpl - Connect operation completed for channel:ccb83359, local address:/172.16.15.22:55700, remote address:172.16.15.22/172.16.15.22:12345
...
2018-07-25 20:14:47,080 157504247 [epollEventLoopGroup-5-1] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Closing connection to segment hulk/smallScaleYoung/2453.#epoch.1592 with exception: {}
io.pravega.shared.protocol.netty.ConnectionFailedException: null
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.connectionDropped(AsyncSegmentInputStreamImpl.java:60)
	at io.pravega.client.netty.impl.ClientConnectionInboundHandler.channelUnregistered(ClientConnectionInboundHandler.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
...
2018-07-25 20:14:47,081 157504248 [epollEventLoopGroup-5-1] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Connection failed due to a io.pravega.shared.protocol.netty.ConnectionFailedException. Read requests will be retransmitted.
2018-07-25 20:14:47,081 157504248 [epollEventLoopGroup-5-1] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScaleYoung/2453.#epoch.1592
io.pravega.shared.protocol.netty.ConnectionFailedException: null
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.connectionDropped(AsyncSegmentInputStreamImpl.java:60)
	at io.pravega.client.netty.impl.ClientConnectionInboundHandler.channelUnregistered(ClientConnectionInboundHandler.java:86)
```

Then there is a retry that fails too:
```
2018-07-25 20:14:47,081 157504248 [epollEventLoopGroup-5-1] DEBUG io.pravega.common.util.Retry - Retrying command. Retry #2, timestamp=2018-07-25T20:14:47.081Z
...
2018-07-25 20:14:47,096 157504263 [epollEventLoopGroup-5-2] INFO  i.p.c.n.i.ClientConnectionInboundHandler - Connection established ChannelHandlerContext(ClientConnectionInboundHandler#0, [id: 0x463e14c2]) 
2018-07-25 20:14:47,097 157504264 [epollEventLoopGroup-5-2] DEBUG i.p.c.n.impl.ConnectionFactoryImpl - Connect operation completed for channel:463e14c2, local address:/172.16.15.22:55706, remote address:172.16.15.22/172.16.15.22:12345
2018-07-25 20:14:47,100 157504267 [epollEventLoopGroup-5-2] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Closing connection to segment hulk/smallScaleYoung/2453.#epoch.1592 with exception: {}
io.pravega.shared.protocol.netty.ConnectionFailedException: null
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.connectionDropped(AsyncSegmentInputStreamImpl.java:60)
	at io.pravega.client.netty.impl.ClientConnectionInboundHandler.channelUnregistered(ClientConnectionInboundHandler.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)

```

This is going on for 10 retries, after that the reader fails with `RetriesExhaustedException` at 20:16:28,879 UTC.
What is interesting is that when another reader picks up the segment, it has no problem connecting and reading from from it.

The client log:
[gargoyle.smallScaleYoung.controller_server_2018-07-25.339.log](https://github.com/pravega/pravega/files/2233159/gargoyle.smallScaleYoung.controller_server_2018-07-25.339.log)

**Problem location**
Client?

**Suggestions for an improvement**
Readers should be able to connect to all new segments and to keep reading.

**Comment by tkaitchuck** [comment] 2018-08-09 17:51
If the connection is being dropped after being established it is because there is an error on the server. Without server side logs I don't have a way to diagnose this.

**Comment by fpj** [comment] 2018-09-03 22:44
I wonder if the cause of this issue is the problem reported here: 

https://github.com/pravega/pravega/issues/2816

which we have already fixed. If it is, then we can close this issue.

**Closed** 2018-09-24 18:11 UTC
