### ISSUE TITLE
Writer process failed with DataCorruptionException in Docker Swarm with IO

### ISSUE THREAD

**Issue by sumit-bm** [pravega/pravega#2993] opened 2018-10-19 09:01 UTC
**Problem description**
While running multiple writers on a 3 node docker swarm environment with 1 Controller, 1 Segment Store, 3 Bookkeeper, 1 Zookeeper with benchmark IO tool and moderate progressive workload, one of the writer failed with DataCorruptionException. Following are snip:

` 57 records Writing,      57.0 records/sec,     0.001 MB/sec, 17.5439 ms avg latency.
[epollEventLoopGroup-4-21] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Failing connection for writer 6c897448-10e8-4ad8-a56c-60b58695297a with exception io.pravega.shared.protocol.netty.ConnectionFailedException
[epollEventLoopGroup-4-26] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection for segment Scope/StreamName-r1/1.#epoch.1 on writer 6c897448-10e8-4ad8-a56c-60b58695297a failed due to: WireCommands.WrongHost(type=WRONG_HOST, requestId=2, segment=Scope/StreamName-r1/1.#epoch.1, correctHost=, serverStackTrace=)
[epollEventLoopGroup-4-26] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - 6c897448-10e8-4ad8-a56c-60b58695297a Failed to connect:
java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=2, segment=Scope/StreamName-r1/1.#epoch.1, correctHost=, serverStackTrace=)
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:874)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)`

None of the docker containers had been failed (segment store Xmxsize = 100Gb and it was 6.2 Gb occupied, following is in segment store log snip:
[segement_Store_log_10182018.zip](https://github.com/pravega/pravega/files/2495112/segement_Store_log_10182018.zip)

`2018-10-18 19:56:27,554 2501062 [core-26] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[0]: Iteration[5].CriticalError.
io.pravega.segmentstore.server.DataCorruptionException: Unable to retrieve CacheContents for 'AggregatedAppend: SegmentId = 20, Offsets = [34060817-34880864), SeqNo = 75919'.
        at io.pravega.segmentstore.server.writer.SegmentAggregator.getFlushArgs(SegmentAggregator.java:763)
        at io.pravega.segmentstore.server.writer.SegmentAggregator.flushPendingAppends(SegmentAggregator.java:696)
        at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$flushExcess$14(SegmentAggregator.java:646)
        at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:690)
        at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:659)
        at io.pravega.common.concurrent.Futures.runOrFail(Futures.java:572)
        at io.pravega.common.concurrent.Futures$Loop.run(Futures.java:703)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2018-10-18 19:56:27,554 2501062 [core-26] INFO  i.p.c.c.AbstractThreadPoolService - StorageWriter[0]: Stopping.
2018-10-18 19:56:27,555 2501063 [core-18] INFO  i.p.c.c.AbstractThreadPoolService - StorageWriter[0]: Stopped.
2018-10-18 19:56:27,555 2501063 [core-3] WARN  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Writer failed. Shutting down StreamSegmentContainer.`

Complete segment store log is attached.

**Problem location**
Docker swarm based Pravega deployment with IO benchmark write-only IO workload

**Comment by RaulGracia** [comment] 2018-11-07 19:53
@sumit-bm If I'm not wrong, this error appeared in a Docker Swarm deployment with Tier2 misconfigured (HDFS) (see #3082). It would be interesting to reproduce this error in a correctly configured Swarm deployment if possible, or otherwise close the issue.

**Comment by shrids** [comment] 2018-12-04 12:54
As mentioned by @RaulGracia  Tier2 is mis-configured in the above logs. Please find the reasons for this listed below. 

*Details:*

`swarm/pravega.yml`  (updated in PR 3082) sets the following env variables
```      
TIER2_STORAGE: HDFS
HDFS_REPLICATION: 1
```
`init_tier2.sh` sets the system property `pravegaservice.storageImplementation` based on this.
Now, if the system property `pravegaservice.storageImplementation` is set then the startup of SegmentStore should print the log 
```
[main] INFO  i.p.s.server.host.ServiceStarter - pravegaservice.storageImplementation = HDFS

```
This log is missing in the uploaded segmentstore log which implies that this is due to misconfiguration.

Closing this issue, @sumit-bm please reopen this if you observe the same issue with the updated `pravega.yml`

**Closed by shrids** 2018-12-04 12:54 UTC
Labels: area/client, kind/bug, priority/P1, status/needs-attention
