### ISSUE TITLE
Controller restarted with "java.lang.OutOfMemoryError: GC overhead limit exceeded" while running IO

### ISSUE THREAD

**Issue by vedanthh** [pravega/pravega#4137] opened 2019-08-23 07:01 UTC
**Controller restarted with "java.lang.OutOfMemoryError: GC overhead limit exceeded" while running IO**

**Environment details: PKS / K8 with medium cluster:**
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
8 worker nodes @ xlarge.cpu(8 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
**Pravega details:**
```
Pravega version: 0.6.0-2333.fed6fd5
Pravega Operator: pravega/pravega-operator:0.4.2-rc0
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Zookeeper version:  pravega/zookeeper:0.2.2
```

**Snip of error from controller log:**
```
2019-08-23 02:21:20,676 442710 [Curator-PathChildrenCache-7] WARN  o.a.c.retry.ExponentialBackoffRetry - Sleep extension too large (5000). Pinning to 1000
java.lang.OutOfMemoryError: GC overhead limit exceeded
Dumping heap to /tmp/dumpfile/heap/java_pid1.hprof ...
Unable to create /tmp/dumpfile/heap/java_pid1.hprof: File exists
Aborting due to java.lang.OutOfMemoryError: GC overhead limit exceeded
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (debug.cpp:308), pid=1, tid=0x00007f495ba79ae8
#  fatal error: OutOfMemory encountered: GC overhead limit exceeded
#
# JRE version: OpenJDK Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
# Java VM: OpenJDK 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.9.0
# Distribution: Custom build (Tue Oct 23 11:27:22 UTC 2018)
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /opt/pravega/hs_err_pid1.log
```

Note: Have shared the logs in internal slack separately.

**Comment by shiveshr** [comment] 2019-08-28 13:07
```
2019-08-23 02:21:20,676 442710 [Curator-PathChildrenCache-7] WARN  o.a.c.retry.ExponentialBackoffRetry - Sleep extension too large (5000). Pinning to 1000
java.lang.OutOfMemoryError: GC overhead limit exceeded
Dumping heap to /tmp/dumpfile/heap/java_pid1.hprof ...
Unable to create /tmp/dumpfile/heap/java_pid1.hprof: File exists
Aborting due to java.lang.OutOfMemoryError: GC overhead limit exceeded
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (debug.cpp:308), pid=1, tid=0x00007f495ba79ae8
#  fatal error: OutOfMemory encountered: GC overhead limit exceeded
#
# JRE version: OpenJDK Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
# Java VM: OpenJDK 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.9.0
# Distribution: Custom build (Tue Oct 23 11:27:22 UTC 2018)
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /opt/pravega/hs_err_pid1.log
```
 
Anyway, i believe this is related to zookeeper session expiration which happened two minutes before OOM:
 
```
2019-08-23 02:19:45,139 347173 [ControllerServiceMain-SendThread(pravega-zk-2.pravega-zk-headless.default.svc.cluster.local:2181)] WARN  org.apache.zookeeper.ClientCnxn - Unable to reconnect to ZooKeeper service, session 0x200220badd76558 has expired
```
However, even after 2 minutes, none of the curator calls have failed with zk session expired. Nor is the sessionExpirationListener triggered. 

So curator is internally retrying on a failed session while also trying to inject session expiration. And this causes OOM.

**Comment by RaulGracia** [comment] 2019-11-04 17:31
As far as I know, this issue has not been reproduced in a while. Since this issue was reported, we have upgraded both Zookeeper server (https://github.com/pravega/zookeeper-operator/pull/83) and client library (#3842) to 3.5.5. I'm in favor to close this issue and re-open it again if it manifests and we are able to reproduce it.

**Closed by RaulGracia** 2019-11-04 17:31 UTC
Labels: area/controller, kind/bug, priority/P1, version/0.6.0
