### ISSUE TITLE
Writer created before container failover fails to write post container recovery.

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#1308] opened 2017-05-11 10:16 UTC
**Problem description**
Summary: A writer created before an SSS failover fails to write into a segment whose container was recovered. i.e. SETUP_APPEND fails continously after SSS failover.

Details: 
The relavent log snippets is present @ 
https://emcnautilus.slack.com/archives/G3EP14GK1/p1494309559507865?thread_ts=1494267131.678688&cid=G3EP14GK1
https://emcnautilus.slack.com/archives/G3EP14GK1/p1494342693192850?thread_ts=1494325036.108639&cid=G3EP14GK1

Logs: Complete logs have been uploaded @ https://emcnautilus.slack.com/archives/G3EP14GK1/p1494261725357201
**Problem location**
Writer

**Comment by shrids** [comment] 2017-05-11 14:36
Log snippet from slack:
```
> 2017-05-08 15:32:12,028 855915 [epollEventLoopGroup-6-8] DEBUG i.p.c.n.i.ClientConnectionInboundHandler - 172.16.24.3 processing reply: WireCommands.AppendSetup(type=APPEND_SETUP, requestId=24, segment=_system/_requeststream/0, connectionId=0247534d-65f7-4183-a756-2ef8233d1962, lastEventNumber=4)
> 2017-05-08 15:32:12,028 855915 [epollEventLoopGroup-6-8] WARN  i.p.c.s.i.SegmentOutputStreamImpl - Connection failed due to: null
> 2017-05-08 15:32:12,028 855915 [epollEventLoopGroup-6-8] WARN  i.p.c.s.i.SegmentOutputStreamImpl - Connection failed due to: null
```

**Comment by tkaitchuck** [comment] 2017-05-15 18:36
I suspect this is a duplicate of #1280. Lets see if #1303 fixes this.

**Closed** 2017-06-15 00:21 UTC
Labels: area/client
