### ISSUE TITLE
ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection:ava.lang.IllegalStateException: Data from unexpected connection

### ISSUE THREAD

**Issue by ipsitapravega** [pravega/pravega#3694] opened 2019-04-25 05:42 UTC
Description :segment store exception after running small -scale IO 
```
exception after i.p.s.s.h.handler.AppendProcessor - Segment 'longevity/smallScale/1728.#epoch.1123' is sealed and 245ebb10-03e0-4e54-9523-7c388564aecb cannot perform operation 'appending data'.

after this , readers are getting exhausted from 4 readers to 1 reader while small scale IO .

```
segment store log snippet :
```
2019-04-24 13:49:03,931 13638957 [epollEventLoopGroup-11-7] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection:
java.lang.IllegalStateException: Data from unexpected connection
[pravega-k8s-logging-2019-04-24-21-24-34.zip](https://github.com/pravega/pravega/files/3115342/pravega-k8s-logging-2019-04-24-21-24-34.zip)
[pravega-k8s-logging-2019-04-24-21-24-34.zip](https://github.com/pravega/pravega/files/3115350/pravega-k8s-logging-2019-04-24-21-24-34.zip)

: eb767a39-457d-4764-ac4b-991f3a9dffae.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:588)
        at io.pravega.segmentstore.server.host.handler.AppendProcessor.append(AppendProcessor.java:395)
        at io.pravega.shared.protocol.netty.Append.process(Append.java:55)
        at io.pravega.segmentstore.server.host.handler.ServerConnectionInboundHandler.channelRead(ServerConnectionInboundHandler.java:46)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
````

Deployment Details:-
```
bookkeeper:0.5.0-2222.8ba5431
pravega:0.5.0-2222.8ba5431
zookeeper:3.5.4-beta-operator
pravega-operator:0.3.2
zookeeper-operator:0.2.1
```
Environment details: PKS / K8 with medium cluster:
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```

**Comment by ipsitapravega** [comment] 2019-04-25 06:03
logs available
[pravega-k8s-logging-2019-04-24-21-24-34.zip](https://github.com/pravega/pravega/files/3115356/pravega-k8s-logging-2019-04-24-21-24-34.zip)

**Comment by RaulGracia** [comment] 2019-04-25 07:11
Duplicate of #2150.

**Comment by sumit-bm** [comment] 2019-04-25 12:16
@tkaitchuck @RaulGracia what would be plan for #2150, would that get fix soon?

**Comment by tkaitchuck** [comment] 2019-05-31 17:14
Actually, I think the two snippits above are unrelated. The "Data from unexpected connection" should be a recoverable error.

**Closed** 2020-01-24 23:03 UTC
Labels: kind/bug, version/0.5.0
