### ISSUE TITLE
Readers failed while running mid-scale longevity on AWS cluster

### ISSUE THREAD

**Issue by deenav** [pravega/pravega#4138] opened 2019-08-23 09:10 UTC
**Problem description**
While running mid-scale longevity on AWS cluster, Readers failed (0/8) from 3 worker pods after 1.30hr of run and also observed one of the worker pod readers are failed to read events from the beginning of the test run.

Longevity assertion error message shows below stack trace:
```
io.pravega.client.stream.TruncatedDataException\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.handleSegmentTruncated(EventStreamReaderImpl.java:282)\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:127)\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:94)\n\tat io.pravega.longevity.testworker.workers.readers.PravegaReader.start(PravegaReader.java:99)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n"
```

**Environment details: PKS / K8 with medium cluster:**
```
AWS - PKS cluster
3 master nodes @ large.cpu (2 CPU, 7.5 GB Ram, 32 GB Disk)
5 worker nodes @ 2xlarge.cpu(8 cpu, 30 GB Ram, 128 GB Disk)
Tier-1 storage is from AWS EBS storageclass
Tier-2 storage is from AWS EFS filesystem
```
**Pravega details:**
```
pravega/pravega-operator:0.4.2-rc0
pravega/zookeeper:0.2.2
pravega/zookeeper-operator:0.2.2
quay.io/external_storage/efs-provisioner:v2.1.0-k8s1.11
vedanthh/bookkeeper:0.6.0-2333.fed6fd5
vedanthh/pravega:0.6.0-2333.fed6fd5
```
**Pod details**
```
# kubectl get po --all-namespaces
NAMESPACE           NAME                                           READY   STATUS      RESTARTS   AGE
default             grafana-766bf7d564-nb6wm                       1/1     Running     0          15h
default             influxdb-698d798588-nrxc5                      1/1     Running     0          15h
default             mean-jackal-efs-provisioner-5f55655c6c-mb787   1/1     Running     0          16h
default             pravega-bookie-0                               1/1     Running     0          14h
default             pravega-bookie-1                               1/1     Running     0          14h
default             pravega-bookie-2                               1/1     Running     0          14h
default             pravega-bookie-3                               1/1     Running     0          14h
default             pravega-operator-5fb689474d-kkwbc              1/1     Running     0          14h
default             pravega-pravega-controller-75f857cfc4-hkjpv    1/1     Running     0          14h
default             pravega-pravega-controller-75f857cfc4-wnvl9    1/1     Running     0          14h
default             pravega-pravega-segmentstore-0                 1/1     Running     0          14h
default             pravega-pravega-segmentstore-1                 1/1     Running     0          14h
default             pravega-pravega-segmentstore-2                 1/1     Running     0          14h
default             pravega-zk-0                                   1/1     Running     0          23h
default             pravega-zk-1                                   1/1     Running     0          23h
default             pravega-zk-2                                   1/1     Running     0          23h
default             zookeeper-operator-747c796d9-b59h8             1/1     Running     0          23h
kube-system         coredns-54586579f6-p6jcb                       1/1     Running     0          35h
kube-system         coredns-54586579f6-vcq9q                       1/1     Running     0          35h
kube-system         coredns-54586579f6-xnzwv                       1/1     Running     0          35h
kube-system         kubernetes-dashboard-6c68548bc9-xnjm2          1/1     Running     0          35h
kube-system         metrics-server-5475446b7f-r9jzw                1/1     Running     0          35h
kube-system         tiller-deploy-7575566df7-kbb7j                 1/1     Running     0          23h
pks-system          cert-generator-v0.19-7wtcb                     0/1     Completed   0          35h
pks-system          event-controller-5c764cbc6-wvw9k               2/2     Running     106        35h
pks-system          fluent-bit-9ktvg                               3/3     Running     0          35h
pks-system          fluent-bit-9v8hs                               3/3     Running     0          35h
pks-system          fluent-bit-fpr9w                               3/3     Running     0          35h
pks-system          fluent-bit-k2krl                               3/3     Running     0          35h
pks-system          fluent-bit-pm9tc                               3/3     Running     0          35h
pks-system          fluent-bit-zgbqv                               3/3     Running     0          35h
pks-system          metric-controller-585878fc8c-4mmdx             1/1     Running     0          35h
pks-system          observability-manager-8d95f455d-vgr5q          1/1     Running     0          35h
pks-system          sink-controller-b6bbd7d68-mfpls                1/1     Running     0          35h
pks-system          telegraf-f7gt4                                 1/1     Running     0          35h
pks-system          telegraf-g89bm                                 1/1     Running     0          35h
pks-system          telegraf-hf9dp                                 1/1     Running     0          35h
pks-system          telegraf-mnrb7                                 1/1     Running     0          35h
pks-system          telegraf-ws2r7                                 1/1     Running     0          35h
pks-system          telegraf-xn7zz                                 1/1     Running     0          35h
pks-system          telemetry-agent-776d45f8d8-sfmsh               1/1     Running     0          35h
pks-system          validator-8568fd5c8f-chhfb                     1/1     Running     0          35h
pravega-longevity   mid-scale-manager-79565bcc5-n4llw              1/1     Running     0          14h
pravega-longevity   mid-scale-worker-7bd44b5bc4-gffdz              1/1     Running     0          14h
pravega-longevity   mid-scale-worker-7bd44b5bc4-m4ltd              1/1     Running     0          14h
pravega-longevity   mid-scale-worker-7bd44b5bc4-mjzqs              1/1     Running     0          14h
pravega-longevity   mid-scale-worker-7bd44b5bc4-tqgvx              1/1     Running     0          14h
```

```
 kubectl get pvc
NAME                                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cache-pravega-pravega-segmentstore-0   Bound    pvc-e9c881fc-c50a-11e9-b80f-0645cb2f0ea8   30Gi       RWO            cache          7m46s
cache-pravega-pravega-segmentstore-1   Bound    pvc-21a53cd0-c50b-11e9-b80f-0645cb2f0ea8   30Gi       RWO            cache          6m12s
cache-pravega-pravega-segmentstore-2   Bound    pvc-3b8286af-c50b-11e9-b80f-0645cb2f0ea8   30Gi       RWO            cache          5m29s
data-pravega-zk-0                      Bound    pvc-c40a88bf-c4c1-11e9-b80f-0645cb2f0ea8   20Gi       RWO            standard       8h
data-pravega-zk-1                      Bound    pvc-e35f285a-c4c1-11e9-b80f-0645cb2f0ea8   20Gi       RWO            standard       8h
data-pravega-zk-2                      Bound    pvc-fe078508-c4c1-11e9-b80f-0645cb2f0ea8   20Gi       RWO            standard       8h
index-pravega-bookie-0                 Bound    pvc-e965cb3d-c50a-11e9-b80f-0645cb2f0ea8   30Gi       RWO            cache          7m47s
index-pravega-bookie-1                 Bound    pvc-e98ae288-c50a-11e9-b80f-0645cb2f0ea8   30Gi       RWO            cache          7m46s
index-pravega-bookie-2                 Bound    pvc-e99d2464-c50a-11e9-b80f-0645cb2f0ea8   30Gi       RWO            cache          7m46s
index-pravega-bookie-3                 Bound    pvc-e9b68684-c50a-11e9-b80f-0645cb2f0ea8   30Gi       RWO            cache          7m46s
journal-pravega-bookie-0               Bound    pvc-e96bbb1a-c50a-11e9-b80f-0645cb2f0ea8   250Gi      RWO            bookie         7m47s
journal-pravega-bookie-1               Bound    pvc-e97de48d-c50a-11e9-b80f-0645cb2f0ea8   250Gi      RWO            bookie         7m47s
journal-pravega-bookie-2               Bound    pvc-e99683b0-c50a-11e9-b80f-0645cb2f0ea8   250Gi      RWO            bookie         7m46s
journal-pravega-bookie-3               Bound    pvc-e9aa200a-c50a-11e9-b80f-0645cb2f0ea8   250Gi      RWO            bookie         7m46s
ledger-pravega-bookie-0                Bound    pvc-e973d803-c50a-11e9-b80f-0645cb2f0ea8   250Gi      RWO            bookie         7m47s
ledger-pravega-bookie-1                Bound    pvc-e983b07d-c50a-11e9-b80f-0645cb2f0ea8   250Gi      RWO            bookie         7m47s
ledger-pravega-bookie-2                Bound    pvc-e99a4170-c50a-11e9-b80f-0645cb2f0ea8   250Gi      RWO            bookie         7m46s
ledger-pravega-bookie-3                Bound    pvc-e9b0e26e-c50a-11e9-b80f-0645cb2f0ea8   250Gi      RWO            bookie         7m46s
pravega-tier2                          Bound    pvc-c861bea5-c4fe-11e9-ac20-0a6f1e39e09e   1000Gi     RWX            efs            94m
```

**Longevity Assertion details**
```
{
  "minutesRunning": 796,
  "humanRunning": "13h 16m",
  "minutesLeft": -795,
  "humanLeft": "-15m -12s",
  "state": "RUNNING",
  "streams": {
    "longevity/midScale": {
      "writers": {
        "events": 181555797,
        "eventsPerSec": 3800.464644561668,
        "eventsPerWorkerPerSec": 950.116155907226,
        "bytes": 147633036687,
        "kbPerSec": 3017.9365,
        "workerStats": {
          "count": 4,
          "active": 4,
          "idle": 0,
          "dead": 0
        },
        "txStarted": 0,
        "txCommitted": 0,
        "txAborted": 0,
        "txFailed": 0,
        "txPerSec": 0.0,
        "timesBlocked": 9900172,
        "averageBlockTime": 6.196348002842458
      },
      "readers": {
        "events": 32595,
        "eventsPerSec": 0.6823034413463954,
        "eventsPerWorkerPerSec": 0.08528008038181362,
        "bytes": 26505799,
        "kbPerSec": 0.5410156,
        "workerStats": {
          "count": 8,
          "active": 0,
          "idle": 0,
          "dead": 8
        },
        "readerGroups": {
          "LongevityMidScale": {
            "events": 32595,
            "eventsPerSec": 0.6823034413463954,
            "eventsPerWorkerPerSec": 0.08528008038181362,
            "bytes": 26505799,
            "kbPerSec": 0.5410156,
            "workerStats": {
              "count": 8,
              "active": 0,
              "idle": 0,
              "dead": 8
            },
            "eventsOutOfSequence": 0
          }
        },
        "eventsOutOfSequence": 0,
        "readers": {
          "460216700": {
            "readerID": "460216700",
            "readerGroupName": "LongevityMidScale",
            "lastEventTime": "2019-08-22T20:25:42.009786Z",
            "lastEventSize": 791,
            "forgetful": false,
            "lastEventReadAt": "2019-08-22T20:25:42.753769Z",
            "lag": "PT0.743983S"
          }
        },
        "txAbortedRead": 0
      }
    }
  },
  "assertionResults": {
    "succeeded": false,
    "assertions": {
      "hasAtLeastXActiveWriters": {
        "succeeded": false,
        "expected": "at least 16, got 4"
      },
      "eventsInSequence": {
        "succeeded": true,
        "expected": "0, got 0"
      },
      "isRunningState": {
        "succeeded": true,
        "expected": "'RUNNING', got 'RUNNING'"
      },
      "readerBytesAreIncreasing": {
        "succeeded": false,
        "expected": "bytes increase\nGroup: LongevityMidScale, previous: 18760083457, current: 26505799"
      },
      "hasAtLeastXActiveReaders": {
        "succeeded": false,
        "expected": "at least 32, got 0"
      },
      "writerBytesAreIncreasing": {
        "succeeded": true,
        "expected": "bytes increase, previous: 130417436862, current: 147633036687"
      }
    }
  },
  "errors": [
    {
      "message": null,
      "stacktrace": "io.pravega.client.stream.TruncatedDataException\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.handleSegmentTruncated(EventStreamReaderImpl.java:282)\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:127)\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:94)\n\tat io.pravega.longevity.testworker.workers.readers.PravegaReader.start(PravegaReader.java:99)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n",
      "logsFilename": null
    },
    {
      "message": null,
      "stacktrace": "io.pravega.client.stream.TruncatedDataException\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.handleSegmentTruncated(EventStreamReaderImpl.java:282)\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:127)\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:94)\n\tat io.pravega.longevity.testworker.workers.readers.PravegaReader.start(PravegaReader.java:99)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n",
      "logsFilename": null
    },
    {
      "message": null,
      "stacktrace": "io.pravega.client.stream.TruncatedDataException\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.handleSegmentTruncated(EventStreamReaderImpl.java:282)\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:127)\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:94)\n\tat io.pravega.longevity.testworker.workers.readers.PravegaReader.start(PravegaReader.java:99)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n",
      "logsFilename": null
    },
    {
      "message": null,
      "stacktrace": "io.pravega.client.stream.TruncatedDataException\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.handleSegmentTruncated(EventStreamReaderImpl.java:282)\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:127)\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:94)\n\tat io.pravega.longevity.testworker.workers.readers.PravegaReader.start(PravegaReader.java:99)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n",
      "logsFilename": null
    },
    {
      "message": null,
      "stacktrace": "io.pravega.client.stream.TruncatedDataException\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.handleSegmentTruncated(EventStreamReaderImpl.java:282)\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:127)\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:94)\n\tat io.pravega.longevity.testworker.workers.readers.PravegaReader.start(PravegaReader.java:99)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n",
      "logsFilename": null
    },
    {
      "message": null,
      "stacktrace": "io.pravega.client.stream.TruncatedDataException\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.handleSegmentTruncated(EventStreamReaderImpl.java:282)\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:127)\n\tat io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:94)\n\tat io.pravega.longevity.testworker.workers.readers.PravegaReader.start(PravegaReader.java:99)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n",
      "logsFilename": null
    }
   ]
}
```

**Note:** I have shared the logs in internal location separately due to size limitation.

**Comment by deenav** [comment] 2019-08-23 10:18
Pravega manifest details
```
apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "pravega"
spec:
  version: 0.6.0-2333.fed6fd5
  zookeeperUri: "pravega-zk-0.pravega-zk-headless.default.svc.cluster.local:2181,pravega-zk-1.pravega-zk-headless.default.svc.cluster.local:2181,pravega-zk-2.pravega-zk-headless.default.svc.cluster.local:2181"
  externalAccess:
    enabled: true
    type: LoadBalancer
​
  bookkeeper:
    serviceAccountName: pravega-components
    image:
      repository: docker.io/vedanthh/bookkeeper
      pullPolicy: Always
​
    replicas: 4
    resources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "6Gi"
        cpu: "3000m"
​
    storage:
      ledgerVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "bookie"
        resources:
          requests:
            storage: 250Gi
​
      journalVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "bookie"
        resources:
          requests:
            storage: 250Gi
​
      indexVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "cache"
        resources:
          requests:
            storage: 30Gi
​
    autoRecovery: true
    options:
      useHostNameAsBookieID: "true"
      minorCompactionThreshold: "0.4"
      minorCompactionInterval: "1800"
      majorCompactionThreshold: "0.8"
      majorCompactionInterval: "43200"
      isForceGCAllowWhenNoSpace: "true"
      diskUsageThreshold: "0.90"
      diskUsageWarnThreshold: "0.85"
      diskUsageLwmThreshold: "0.85"
​
  pravega:
    controllerServiceAccountName: pravega-components
    segmentStoreServiceAccountName: pravega-components
    controllerReplicas: 2
    controllerResources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "3Gi"
        cpu: "2000m"
​
    segmentStoreReplicas: 3
    segmentStoreResources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "8Gi"
        cpu: "4000m"
​
    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "cache"
      resources:
        requests:
          storage: 30Gi
​
    image:
      repository: docker.io/vedanthh/pravega
      pullPolicy: Always
​
    options:
      bookkeeper.bkWriteQuorumSize: "3"
      bookkeeper.bkAckQuorumSize: "3"
      pravegaservice.cacheMaxSize: "3221225472"
      pravegaservice.cacheMaxTimeSeconds: "600"
      rocksdb.writeBufferSizeMB: "64"
      rocksdb.readCacheSizeMB: "8"
      rocksdb.cacheBlockSizeKB: "32"
      writer.flushThresholdBytes: "1048576"
      writer.maxFlushSizeBytes: "1048576"
      hdfs.blockSize: "67108864"
      pravegaservice.containerCount: "32"
      controller.containerCount: "32"
      pravegaservice.threadPoolSize: "30"
      controller.retention.bucketCount: "10"
      controller.service.asyncTaskPoolSize: "20"
      controller.retention.threadCount: "4"
      log.level: "INFO"
      metrics.dynamicCacheSize: "100000"
      metrics.enableStatistics: "true"
      metrics.enableStatsDReporter: "false"
      metrics.statsdHost: "telegraph.default"
      metrics.statsdPort: "8125"
      metrics.enableInfluxDBReporter: "true"
      metrics.outputFrequencySeconds: "10"
      metrics.influxDBURI: "http://10.200.20.4:8086"
      controller.metrics.dynamicCacheSize: "100000"
      controller.metrics.enableStatistics: "true"
      controller.metrics.enableStatsDReporter: "false"
      controller.metrics.statsdHost: "telegraph.default"
      controller.metrics.statsdPort: "8125"
      controller.metrics.enableInfluxDBReporter: "true"
      controller.metrics.outputFrequencySeconds: "10"
      controller.metrics.influxDBURI: "http://10.200.20.4:8086"
​
    tier2:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2
```

**Comment by shrids** [comment] 2019-08-27 04:52
- The readers lagged and hence faced the `TruncationDataException` since the retention policy of the stream caused a truncation of the stream. This is as per the current reader API.
The real issue here is what caused the lag in the readers and from the metrics we observe that things are fine from the Pravega side of things. (@andreipaduroiu also helped to confirm this)
![deena_setup_snip](https://user-images.githubusercontent.com/11114165/63741338-4cd0d880-c8b2-11e9-885d-86f766268b48.jpg)

- Verified the manifest and deployment configuration of Pravega and it is as per the recommendation.

-  Observing that the mid scale test manager shows one test worker pod not reading any events. But the all the test worker pods indicate events are being read which is strange. 

@deenav could you confirm that there is no other issue on the test harness side? Also can you share the logs of the worker pod which was not able to read the events (if true), around timestamp 2019-08-22 20:25:34,976.

**Comment by shrids** [comment] 2019-08-27 05:27
- The readers lagged and hence faced the `TruncationDataException` since the retention policy of the stream caused a truncation of the stream. This is as per the current reader API.
The real issue here is what caused the lag in the readers and from the metrics we observe that things are fine from the Pravega side of things. (@andreipaduroiu also helped to confirm this)
![deena_setup_snip](https://user-images.githubusercontent.com/11114165/63741338-4cd0d880-c8b2-11e9-885d-86f766268b48.jpg)

- Verified the manifest and deployment configuration of Pravega and it is as per the recommendation.

-  Observing that the mid scale test manager shows one test worker pod not reading any events. But the all the test worker pods indicate events are being read which is strange. 

@deenav could you confirm that there is no other issue on the test harness side? Also can you share the logs of the worker pod which was not able to read the events (if true), around timestamp 2019-08-22 20:25:34,976.

**Comment by kevinhan88** [comment] 2019-09-04 22:40
@deenav - please provide the longevity test workload details as well.

**Comment by kevinhan88** [comment] 2019-09-04 22:45
https://github.com/pravega/pravega/issues/4122 is a separate issue per the current understanding, however just mention it here for the potential link under the hood.

**Comment by shrids** [comment] 2019-09-05 04:57
@kevinhan88 from the logs we can see that this issue is not related to issue 4122 ( which is related to compaction of State synchronizer stream). The issue here is that the readers were lagging behind the writers when the stream's retention policy truncated the stream. This truncation caused the readers to throw a TruncatedDataException, which is as per expectation.

**Comment by shrids** [comment] 2019-09-05 05:20
Closing this issue based on the following points:

- From the shared logs do not see an issue from the Pravega side. 
- We would need additional logs of the test harness worker pod which was not able to read events (according to the `mid scale test manager ` logs). A test worker pod not starting up correctly will the causes for the readers to lag behind the writers leading to a TruncatedDataException.

(Please reopen this issue if this is observed again)

**Closed by shrids** 2019-09-05 05:20 UTC
Labels: area/client, priority/P1, status/more-info-needed, version/0.6.0

**Comment by RaulGracia** [comment] 2019-09-05 06:25
Thanks, @shrids. For everyone: please, every time you see `TruncatedDataException` in a longevity experiment, look at the metrics in depth and share them with us (dashboard location) in the same way as logs. One common cause for this problem is that Tier 2 is slow, which means that the cache is full all the time, and this makes readers to read more slowly than writers. Readers continue lagging and the auto retention mechanism eventually truncates the stream in a position ahead of where readers are reading, thus causing the `TruncatedDataException`. We can see in the snapshot posted that after 12 hours of experiment, we see spikes in `Storage Write Latency` (tier 2). But we would need cache metrics to confirm that. Also, please verify that the Tier 2 you are using (e.g., Isilon) is the proper one for the cluster you are using.
