### ISSUE TITLE
Unit test failure: DataRecoveryTest.testDataRecoveryCommand

### ISSUE THREAD

**Issue by derekm** [pravega/pravega#5497] opened 2021-01-10 07:11 UTC
**Problem description**
Stack trace:
```
io.pravega.cli.admin.dataRecovery.DataRecoveryTest > testDataRecoveryCommand FAILED
    io.pravega.controller.store.stream.StoreException$DataNotFoundException: addNewEntry: key: RG table: _system/_tables/testScope/readerGroupsInScope.#.8c844f7d-1bbb-4902-aebd-5a22e8845946
        at io.pravega.controller.store.stream.StoreException.create(StoreException.java:90)
        at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$exceptionalCallback$55(PravegaTablesStoreHelper.java:550)
        at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
        at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at io.pravega.client.connection.impl.RawClient.reply(RawClient.java:126)
        at io.pravega.client.connection.impl.RawClient.access$300(RawClient.java:39)
        at io.pravega.client.connection.impl.RawClient$ResponseProcessor.process(RawClient.java:72)
        at io.pravega.client.connection.impl.FlowHandler.process(FlowHandler.java:204)
        at io.pravega.client.connection.impl.TcpClientConnection$ConnectionReader.run(TcpClientConnection.java:121)
        at java.base/java.lang.Thread.run(Thread.java:834)

        Caused by:
        io.pravega.controller.server.WireCommandFailedException: WireCommandFailed with type UPDATE_TABLE_ENTRIES reason SegmentDoesNotExist
            at io.pravega.controller.server.SegmentHelper.handleReply(SegmentHelper.java:680)
            at io.pravega.controller.server.SegmentHelper.lambda$updateTableEntries$13(SegmentHelper.java:419)
            at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
            ... 8 more
```

**Problem location**
`DataRecoveryTest.testDataRecoveryCommand`

**Suggestions for an improvement**
Test should pass reliably.

**Comment by ManishKumarKeshri** [comment] 2021-01-13 07:16
@andreipaduroiu Can you please assign it to me? 
Hi @derekm, does this run include #5439 changes?

**Comment by pbelgundi** [comment] 2021-01-18 10:32
This test failure is resolved (masked) by PR: https://github.com/pravega/pravega/pull/5517
However, the real underlying root cause is issue: https://github.com/pravega/pravega/issues/5527 which needs to be fixed.

**Closed by pbelgundi** 2021-01-18 10:32 UTC
Labels: area/controller, kind/flakeyTest
