### ISSUE TITLE
Sporadic unit test failure: SegmentStoreIntegrationtests.TimeoutException

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#1462] opened 2017-06-21 09:01 UTC
**Problem description**
SegmentStoreIntegrationTest.testEndToEnd timed out and SynchronousStreamSegmentStoreTests.testEndToEnd failed

1. io.pravega.segmentstore.server.host.SegmentStoreIntegrationTest > testEndToEnd FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 300 seconds

2. SynchronousStreamSegmentStoreTests > testEndToEnd failed

**Problem location**
SSS

**Suggestions for an improvement**
bug fix

**Comment by andreipaduroiu** [comment] 2017-06-22 14:49
This is just one of many tests that fail sporadically in Travis/Jenkins due to timeouts. I can't reproduce this locally. If this doesn't happen again by 7/22/2017, I will close this issue.

**Comment by Prabha-Veerubhotla** [comment] 2017-06-27 15:05
```
io.pravega.segmentstore.server.mocks.SynchronousStreamSegmentStoreTests > testEndToEnd FAILED
    java.util.concurrent.CompletionException: io.pravega.segmentstore.server.IllegalContainerStateException: Container 3 is in an invalid state for this operation. Expected: RUNNING; Actual: STOPPING.
        Caused by:
        io.pravega.segmentstore.server.IllegalContainerStateException: Container 3 is in an invalid state for this operation. Expected: RUNNING; Actual: STOPPING.
```

**Closed** 2017-07-03 08:00 UTC
