### ISSUE TITLE
Sporadic build failure: ScaleRequestHandlerTest.testScaleRequest times out

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#2053] opened 2017-11-07 05:02 UTC
**Problem description**
io.pravega.controller.server.eventProcessor.ScaleRequestHandlerTest > testScaleRequest FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 20000 milliseconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1695)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1775)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
        at io.pravega.common.concurrent.Futures.lambda$await$0(Futures.java:68)
        at io.pravega.common.concurrent.Futures$$Lambda$344/962124175.run(Unknown Source)
        at io.pravega.common.Exceptions.handleInterrupted(Exceptions.java:90)
        at io.pravega.common.concurrent.Futures.await(Futures.java:66)
        at io.pravega.common.concurrent.Futures.await(Futures.java:53)
        at io.pravega.controller.server.eventProcessor.ScaleRequestHandlerTest.testScaleRequest(ScaleRequestHandlerTest.java:197)

**Problem location**

**Suggestions for an improvement**

**Comment by andreipaduroiu** [comment] 2018-06-14 21:39
duplicate of #2402

**Closed by andreipaduroiu** 2018-06-14 21:39 UTC
