### ISSUE TITLE
Cleanup Exception handling: Getting `ConcurrentEventProcessor Processing failed` in controller logs

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#3734] opened 2019-05-02 09:42 UTC
**Getting `ConcurrentEventProcessor Processing failed, exiting {}` error inside controller logs while IO is running:**

**Environment details: PKS / K8 with medium cluster:**

```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
```
Pravega version: 0.5.0-2236.5228e2d
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```
**Controller Logs:**
```
2019-05-02 07:29:46,096 2618339 [controllerpool-6] ERROR i.p.c.e.i.ConcurrentEventProcessor - ConcurrentEventProcessor Processing failed, exiting {}
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.EpochTransitionOperationExceptions$PreConditionFailureException
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
        at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
        at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:899)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.pravega.controller.server.eventProcessor.requesthandlers.ScaleOperationTask.lambda$execute$0(ScaleOperationTask.java:73)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.controller.store.stream.EpochTransitionOperationExceptions$PreConditionFailureException: null
        at io.pravega.controller.store.stream.PersistentStreamBase.lambda$null$91(PersistentStreamBase.java:706)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580)
        ... 8 common frames omitted
```
Attaching complete logs of all the pods:
[pravega-k8s-logging-2019-05-02-13-09-03.zip](https://github.com/pravega/pravega/files/3137457/pravega-k8s-logging-2019-05-02-13-09-03.zip)

**Comment by shiveshr** [comment] 2019-07-03 07:37
duplicate of #3676

**Closed by shiveshr** 2019-07-03 07:37 UTC
Labels: area/controller, area/logging, kind/enhancement, priority/P3, version/0.5.0
