### ISSUE TITLE
Observing StorageWriter[18]: Iteration[28816].Error. java.io.IOException: I/O error too many times in Segement store

### ISSUE THREAD

**Issue by sumit-bm** [pravega/pravega#3747] opened 2019-05-04 16:47 UTC
While running transnational small IO workload  (single reader, single writer, size=10, events per second = 60) observing IO getting stalled after few hours of operation and following exception is ongoing in segment store:

```
2019-05-02 16:53:33,863 7425198 [storage-io-66] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[18]: Iteration[28816].Error.
java.io.IOException: I/O error
        at sun.nio.ch.FileDispatcherImpl.force0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.force(FileDispatcherImpl.java:76)
        at sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:388)
        at io.pravega.storage.filesystem.FileSystemStorage.doWrite(FileSystemStorage.java:323)
        at io.pravega.storage.filesystem.FileSystemStorage.lambda$write$6(FileSystemStorage.java:155)
        at io.pravega.storage.filesystem.FileSystemStorage.execute(FileSystemStorage.java:405)
        at io.pravega.storage.filesystem.FileSystemStorage.write(FileSystemStorage.java:155)
        at io.pravega.segmentstore.storage.rolling.RollingStorage.write(RollingStorage.java:324)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$write$2(AsyncStorageWrapper.java:93)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$runAsync$12(AsyncStorageWrapper.java:171)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
``` 
Environment details: PKS / K8 with medium cluster:
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
```
Pravega version: 0.5.0-2236.5228e2d
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```
From controller the transaction IO is still processing but never getting completed:
```
2019-05-02 19:59:49,620 18701183 [grpc-default-executor-210] INFO  i.p.c.s.r.g.v.ControllerServiceImpl - checkTransactionState called for stream longevity/smallTx, txnId=lowBits: 8282
```
```
Writers (1/1): events:125,396, events/sec:10, KB/sec:8.280273
Transactions: started: 8282, perSec:0.35607235142118865, committed:4134, failed:0, aborted:4148, aborted but read: 0
Blocked Waiting For ACK: times blocks: 19,698, average block time (ms): 311
Readers (1/1): events:125,396, events/sec:10, KB/sec:8.280273
New runtime for 23965377-1913-4e98-8f4c-541241e49b79  Running for 3h 13m
Dumping stats for stream longevity/smallTx
Writers (1/1): events:125,396, events/sec:10, KB/sec:8.301758
Transactions: started: 8282, perSec:0.35607235142118865, committed:4134, failed:0, aborted:4148, aborted but read: 0
```

**Comment by Raghuveera-Rao** [comment] 2019-05-06 07:02
on the continuation, we also see **BadOffsetException** in StorageWriter

```
2019-05-06 06:58:29,820 344450993 [storage-io-89] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[0]: Iteration[1001567].Error.
io.pravega.segmentstore.contracts.BadOffsetException: [Segment 'longevity/smallScaleYoung/1828.#epoch.1181'] Bad Offset. Expected 348379423, given 348377022.
        at io.pravega.segmentstore.storage.rolling.RollingStorage.ensureOffset(RollingStorage.java:823)
        at io.pravega.segmentstore.storage.rolling.RollingStorage.write(RollingStorage.java:309)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$write$2(AsyncStorageWrapper.java:93)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$runAsync$12(AsyncStorageWrapper.java:171)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by sachin-j-joshi** [comment] 2019-05-10 16:06
**Quick update from 5/10**

1. We deployed private branch for longevity tests https://github.com/sachin-j-joshi/pravega/commits/issue-3747-and-3726-cherry-pick. However continued to get the same errors.

2. Sumit also ran a few unix commands on pod and was able to repro I/O errors outside of /independent of pravega. 
He encountered the **same errors**.

> /mnt/tier2 # touch testfile
**> /mnt/tier2 # dd if=/dev/zero of=test bs=1024k count=100
> dd: test: I/O error (it wrote only 11 MB)**

> /mnt/tier2 # sync
> /mnt/tier2 # sync
> /mnt/tier2 # dd if=/dev/zero of=test bs=1024k count=10 
> 10+0 records in
> 10+0 records out
> 
> /mnt/tier2 # dd if=/dev/zero of=test bs=1024k count=12
> 12+0 records in
> 12+0 records out
> /mnt/tier2 # dd if=/dev/zero of=test bs=1024k count=100
> 100+0 records in
> 100+0 records out
> again tried 100 MB write and went fine.

3. At this point it does not look like this issue is caused by any pravega bug. These seem to be truely intermittent failures coming from the underlying storage driver that talks with nfs (over the possibly flaky network). 
The tier-2 code is correctly handling the exceptions and simply logging them.
The storage writer will retry the operations and eventually the writes will succeed. This is _expected normal operation for StorageWriter_
These intermittent exceptions are not a problem as long as system is recovering from it.  If system is recovering successfully. not sure at this point there is anything specific that code needs to differently

**Next steps** 

Close the issue after confirming that the StorageContainers are not restarted and that system eventually recovers correctly despite any i/o errors.


CC: @sumit-bm @andreipaduroiu

**Comment by sachin-j-joshi** [comment] 2019-05-21 20:15
This issue is caused by hardware that is not in healthy state. 
At this point there is nothing actionable to be done at the code level.
CC: @sumit-bm

**Comment by andreipaduroiu** [comment] 2019-06-03 22:32
We haven't seen this since the hardware was fixed. Please create a new issue if it comes back and we have healthy hardware.

**Closed by andreipaduroiu** 2019-06-03 22:32 UTC
Labels: kind/bug, priority/P1, version/0.5.0

**Comment by Raghuveera-Rao** [comment] 2019-06-04 11:27
> We haven't seen this since the hardware was fixed. Please create a new issue if it comes back and we have healthy hardware.

Tried this with new tier-2 mounting points.
Saw this `ERROR i.p.s.server.writer.StorageWriter ` in segment store logs in build:
```
bookkeeper:0.5.0-2260.b477eec
pravega:0.5.0-2260.b477eec
zookeeper:3.5.4-beta-operator
pravega/pravega-operator:0.3.2
pravega/zookeeper-operator:0.2.1
```

complete error 
```
2019-06-03 20:57:17,544 19381581 [core-9] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[7]: Iteration[294551].Error.
io.pravega.segmentstore.storage.DataLogWriterNotPrimaryException: Unable to acquire exclusive write lock for log (path = 'pravega/pravega/segmentstore/containers/7/0/7').
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.persistMetadata(BookKeeperLog.java:802)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.tryTruncate(BookKeeperLog.java:675)
        at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.lambda$truncate$4(BookKeeperLog.java:323)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /pravega/pravega/segmentstore/containers/7/0/7
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.setData(ZooKeeper.java:2272)
        at org.apache.curator.framework.imps.SetDataBuilderImpl$4.call(SetDataBuilderImpl.java:291)
        at org.apache.curator.framework.imps.SetDataBuilderImpl$4.call(SetDataBuilderImpl.java:287)
        at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64)
        at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)
```

Previously , segment store logs had large  number of  'ERROR i.p.s.server.writer.StorageWriter'. Now, frequency of this error is drastically decreased with new tier-2 mounting.
