### ISSUE TITLE
Sporadic failure: ContainerKeyIndexTests testRecovery

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#4202] opened 2019-09-24 06:20 UTC
**Problem description**
Encountered failure in test on travis. 
```
io.pravega.segmentstore.server.tables.ContainerKeyIndexTests > testRecovery FAILED
    java.lang.AssertionError: Expected getBucketOffsets() to block.
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertFalse(Assert.java:64)
        at io.pravega.segmentstore.server.tables.ContainerKeyIndexTests.testRecovery(ContainerKeyIndexTests.java:469)
```

**Problem location**
ContainerKeyIndexTests.java

**Suggestions for an improvement**
Fix the issue

**Comment by shiveshr** [comment] 2019-09-25 03:08
another failure in the same test but a different error this time:
```
io.pravega.segmentstore.server.tables.ContainerKeyIndexTests > testRecovery FAILED

    java.lang.AssertionError: Not expecting anything to be unblocked at this point

        at org.junit.Assert.fail(Assert.java:88)

        at org.junit.Assert.assertTrue(Assert.java:41)

        at org.junit.Assert.assertFalse(Assert.java:64)

        at io.pravega.segmentstore.server.tables.ContainerKeyIndexTests.testRecovery(ContainerKeyIndexTests.java:485)```

**Comment by andreipaduroiu** [comment] 2019-09-25 18:04
duplicate of #4193

**Closed by andreipaduroiu** 2019-09-25 18:04 UTC
Labels: area/testing, kind/bug, priority/P1, version/0.6.0
