### ISSUE TITLE
Tracking issue for extended S3 put-if-absent semantics not working

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#1564] opened 2017-07-12 07:24 UTC
**Problem description**
In the implementation of the Extended S3 binding, to ensure that a call to putObject does not lose data, we need to use put-if-absent (create) semantics as described here: http://www.emc.com/techpubs/api/ecs/v3-0-0-0/S3ObjectOperations_createOrUpdateObject_7916bd6f789d0ae0ff39961c0e660d00_ba672412ac371bb6cf4e69291344510e_detail.htm

Unfortunately, with the backend that we are using for this binding, ECS, the call to `putObject` using `ifNoneMatch` does not work as per our tests. By using `ifNoneMatch("*")`, we should be able to put an object only if no previous object has been created with the same key, which is the semantics that we require.

**Problem location**
Extended S3 implementation of `putObject` API call with`setIfNoneMatch("*") `. 

**Suggestions for an improvement**
Wait until this fixed so that we use implement it correctly.

**Comment by sachin-j-joshi** [comment] 2019-04-04 22:57
The underlying ECS store is not behaving as expected. 
Expected - When "If-None-match:*" is set, then put-if-absent semantics for the createObject
Actual - The object gets overwritten and returns previous length . 

We'll have to wait or find work around.

**Comment by sachin-j-joshi** [comment] 2019-04-08 14:45
Tested against https://object.ecstestdrive.com with ExtendedS3StorageConfig.USENONEMATCH set to true.
The  ifNoneMatch("*") behavior correctly throws following exception 

> com.emc.object.s3.S3Exception: At least one of the preconditions you specified did not hold.

This exception is correctly translated into _StreamSegmentExistsException_

**We can close this issue as not repro.**
There are no code changes required either.

**Comment by fpj** [comment] 2020-08-13 10:07
@sachin-j-joshi if the issue is gone on its own, then can we fix this comment here?

**Comment by fpj** [comment] 2021-02-09 18:04
If this behavior is fixed in ECS, then can we fix the comment in the code and corresponding configuration?

cc/ @medvedevigorek

**Closed** 2021-11-01 16:36 UTC
Labels: kind/bug, area/lts, area/segmentstore, status/needs-attention, version/unversioned
