### ISSUE TITLE
Controller in Unhealthy State

### ISSUE THREAD

**Issue by chrisdail** [pravega/pravega#1993] opened 2017-10-19 12:19 UTC
**Problem description**

After a few hours of running the controller gets into an unhealthy state as returned from the mesos health check. The mesos health check is using the Ping call in the controller. The health check is extremely generous allowing for 20 sequential failures on a 30 second interval. So the controller was down for a long time. This is the ping API call used:

```
http://localhost:{{PRAVEGA_CONTROLLER_HTTP_PORT}}/ping
```

There are actually two separate issues here:

1) The controller gets into a state where it no longer responds to requests (like the ping) causing mesos to kill it.
2) After the first controller was killed by mesos, a second was started to recover. This controller is non-functional. Even after this came back it is not possible to read/write from any streams.

I think the zookeeper connection may be flaky from some of the logs. The controller should recover from this though.

**Problem location**

Pravega build: 0.2.0-1635.87eb580

This occurred on two separate environments so I have two sets of logs.

Logs from mi-13 from controller that failed health checks and was killed:
[mi-13-killed-instance-controller-stderr.txt](https://github.com/pravega/pravega/files/1398264/mi-13-killed-instance-controller-stderr.txt)
[mi-13-Killed-instance-controller.log](https://github.com/pravega/pravega/files/1398256/mi-13-Killed-instance-controller.log)

Logs from hammer cluster from controller that failed health checks and was killed:
[hammer-killed-instance-controller.log](https://github.com/pravega/pravega/files/1398255/hammer-killed-instance-controller.log)
[hammer-killed-instance-controller-stderr.txt](https://github.com/pravega/pravega/files/1398263/hammer-killed-instance-controller-stderr.txt)

Logs from hammer cluster from new controller that started which was unable to serve requests:
[hammer-non-functional-new-controller.log](https://github.com/pravega/pravega/files/1398254/hammer-non-functional-new-controller.log)
[hammer-non-functional-controller-stderr.txt](https://github.com/pravega/pravega/files/1398262/hammer-non-functional-controller-stderr.txt)

**Suggestions for an improvement**

**Comment by shiveshr** [comment] 2017-10-20 07:23
So original controller failure (killed instances) are because of zookeeper session expiry.. 
the logic we have is to shutdown controller in case we find zk session expired to have expired. 
Now the issue that is coming up is that as we attempt a clean shutdown of all components some are stuck trying to shutdown with retries and have not shutdown for over 10 minutes. and at some point mesos health check finds controller to be failing and stops it.. 

So one issue we should fix here is "clean shutdown of controller is not happening in case of session expiry" and it is stuck for long until mesos deems controller unhealthy and shuts it down eventually. 

now new controller instance that is started, i see its logs filled with: ```Caused by: java.lang.IllegalStateException: Client is not started
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:114)
```
So for some reason zookeeper client has not been started.. this should also have failed early.. 
my initial suspicion is that these may have surfaced because of our upgrade of dependencies (read curator client). 

will investigate more and update.. clearly we have one issue on controller that we are not able to have clean shutdowns..

**Comment by chrisdail** [comment] 2017-10-24 12:43
ZK is available during this period but we do see connection resets on occasion. We also occasionally see session expiries. So I guess you can consider ZK unstable for a short period of time.

The controller should recover from this though. If the controller dies and comes back everything should still work. If ZK goes away and comes back the controller should still function.

**Comment by shiveshr** [comment] 2017-10-24 12:58
yes, there are two issues here. 
1. controller should have shutdown on its own rather than have mesos kill it upon a zk session expiry.
 
2. the replacement controller should become functional once connectivity to zk is established. The problem is, from the logs i can see that curator is not started even after several minutes of having started this new instance.

**Comment by chrisdail** [comment] 2017-10-26 17:22
We have solved some of the issues with ZK connections. Pravega seems much better with these changes however the fundamental issue still remains if ZK is unavailable for a period of time.

**Comment by shiveshr** [comment] 2018-02-24 03:11
closing this as we have not observed this in a while.

**Closed by shiveshr** 2018-02-24 03:11 UTC
Labels: area/controller, kind/bug, version/0.2.0
