### ISSUE TITLE
PDP-38: Schema Registry

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#4545] opened 2020-01-31 16:40 UTC
**Problem description**
Issue to discuss PDP 38:

https://github.com/pravega/pravega/wiki/PDP-38:-Schema-Registry-(Under-Review)

**Problem location**
Management of schemas for Pravega streams, new component.

**Suggestions for an improvement**
Design and implement.

**Comment by fpj** [comment] 2020-01-31 18:47
> To broadly understand the use case, we will focus on types of applications and classify them into two broad categories. 
> 1. Applications with implicit knowledge of structure of data they work with by having the schema embedded in the code. 
> 2. Applications that do not have schema included in their code base and dynamically react to data they need to process.

Can we come up with terms to talk about these classes of applications? Giving it names might even help with understanding the difference. Also, this whole section is very abstract, it is better to make it more concrete. Give concrete examples where possible.

> In the event that schemas can be much larger than 8 Mb, they can be stored using byte stream apis into a new stream.

I wonder whether this is a reasonable assumption to make. An application might not necessarily have control over all its writers. Think of sensors sprinkled across a large area.

> In the event that schemas can be much larger than 8 Mb, they can be stored using byte stream apis into a new stream.

What happens when a new revision of a schema is added? Do we create a new byte stream or write to the same? If we can always use byte streams and have to do it for really large schemas (which sounds unlikely to happen), shouldn't we always use byte streams to be consistent?

>  So any query will first look up in pravega tables, and if the schema information is not found in the table, then a look up in the revisioned segment starting from lastest position in the table will be performed.

I suppose that we should update the table if we find anything. Also, apparently any miss will induce the additional work of checking the revisioned stream, which is undesirable.

> Compatibility check during development phase

This section is interesting and potentially useful, but the content is super abstract. Make it more concrete, imagine that you are starting an application and describe the steps and options.

**Comment by claudiofahey** [comment] 2020-01-31 19:41
> Can we come up with terms to talk about these classes of applications? Giving it names might even help with understanding the difference. Also, this whole section is very abstract, it is better to make it more concrete. Give concrete examples where possible.

"Static" serialization: Static serializers will serialize a strongly typed instance of a class that is known at compile time. In Java, a static serializer will accept a POJO and output a sequence of bytes. The POJO code (.java file) is generally created by an Avro or Protobuf code generator.

"Dynamic" serialization: Dynamic serializers will accept a dynamic object whose structure is not known at compile time. In Java, a dynamic serializer could accept a `com.fasterxml.jackson.databind.JsonNode` or `org.apache.avro.generic.GenericData.Record` for example. In Python, a `dict` object could be accepted.

>> In the event that schemas can be much larger than 8 Mb, they can be stored using byte stream apis into a new stream.

>I wonder whether this is a reasonable assumption to make. An application might not necessarily have control over all its writers. Think of sensors sprinkled across a large area.

This just applies to the schema which is typically a small JSON file for Avro or a .proto file for Protobuf. The schema registry system does not impose any size limits on the events themselves.

**Comment by claudiofahey** [comment] 2020-01-31 20:10
A few comments on the PDP:

>For data types like Avro, proto etc, the schema would be send in binary or String form.

"String" is not specific enough. Change this to UTF-8. We don't want Java to send UTF-16.

> 8 Mb

I read this as "8 megabits". Change this to "8 MiB" to be precise.

**Comment by claudiofahey** [comment] 2020-01-31 22:54
We may also want to our serializer to support compression. Basically the output of the Avro/protobuf serializer can be fed into a stream compressor such as gzip or snappy. This will not be effective for tiny messages but it will likely be effective for 1 KB+ messages. It will also be very easy to do and will give Pravega a very valuable feature. As far as the schema registry, we would have an enum for compression (gzip, snappy, none, etc.).

**Comment by tkaitchuck** [comment] 2020-02-01 01:12
Under Discarded Alternatives it just lists a bunch of things with no explanation as to why they are discarded. Some of these aren't even mentioned anywhere in the PDP. We should add a section on each of these.

**Comment by tkaitchuck** [comment] 2020-02-01 01:13
This 8 and 24 bit versioning scheme seems very dubious to me. I don't recall us having discussed it. Why aren't we letting the individual formats define this?

**Comment by tkaitchuck** [comment] 2020-02-01 01:19
It proposes adopting the avro compatibility semantics and applying this to all formats. I don't think this actually makes sense. Shouldn't each format have it's own definitions?

**Comment by claudiofahey** [comment] 2020-02-01 02:34
> This 8 and 24 bit versioning scheme seems very dubious to me. I don't recall us having discussed it. Why aren't we letting the individual formats define this?

The 2-4 byte "schema version" in each event is essentially just a pointer to a record in the schema registry. The record will have all the details needed to deserialize the event including SchemaType (Avro, Protobuf), schema (Avro JSON or .proto file), eventType, and compression type. In the proposal, the SchemaType is not known when reading the event so the "schema version" needs to be encoded in the same way regardless of SchemaType.

We could spend an extra byte to encode SchemaType in each event. That would allow the rest of the event to be SchemaType-specific. However, I don't see any benefit in doing this.

**Comment by claudiofahey** [comment] 2020-02-01 02:43
FYI, Here is how the Avro spec proposes to store this info:
https://avro.apache.org/docs/current/spec.html#single_object_encoding:

> Single object encoding specification
> Single Avro objects are encoded as follows:
> A two-byte marker, C3 01, to show that the message is Avro and uses this single-record format (version 1).
> The 8-byte little-endian CRC-64-AVRO fingerprint of the object's schema
> The Avro object encoded using Avro's binary encoding

This uses 8 bytes to reduce the chance of a fatal hash collision to practically 0. Our proposal can completely avoid collisions by using a counter. Further, we could encode it with a variable size integer and use just 1 byte for the first 127 schema versions. Maybe saving a few bytes is not worth this effort though.

**Comment by shiveshr** [comment] 2020-02-01 08:41
> We may also want to our serializer to support compression. Basically the output of the Avro/protobuf serializer can be fed into a stream compressor such as gzip or snappy. This will not be effective for tiny messages but it will likely be effective for 1 KB+ messages. It will also be very easy to do and will give Pravega a very valuable feature. As far as the schema registry, we would have an enum for compression (gzip, snappy, none, etc.).

I like this suggestion. Though i think we need to capture message encoding separate from compression type.
`SchemaInfo` captures encoding format (schemaType) and its identifier (`version`) is referenced in the new header we propose to add to each serialized event. 
We can add `compression Type` into that header as well. 
So compression does not become part of schema information.

**Comment by shiveshr** [comment] 2020-02-01 08:46
> It proposes adopting the avro compatibility semantics and applying this to all formats. I don't think this actually makes sense. Shouldn't each format have it's own definitions?

Yes, actually i have proposed abstracting Compatibility Check on the registry and make it pluggable as well. 
The notion of compatibility may vary for different schema formats. But for the formats that we want to support directly, the popular ones like avro proto or thrift, we could follow the notion of compatibility as described in the PDP. 
There may be restrictive for some of the things that some formats allow for - like renaming a field in protobuf or thrift does not break compatibility but it does in avro. 
Bit we can choose to generalize the rules to treat renames as incompatible change for benefit of applications with "Dynamic Deserializers" as claudio defined earlier.

**Comment by shiveshr** [comment] 2020-02-01 08:48
> This 8 and 24 bit versioning scheme seems very dubious to me. I don't recall us having discussed it. Why aren't we letting the individual formats define this?

Versioning is not format specific. 
A version schema is just imposing an order and identifier to schemas within a stream as they are evolved. 
And this identifier is for the purpose of applications where we include this reference in the header of each serialized event.

**Comment by shiveshr** [comment] 2020-02-01 09:04
>>    In the event that schemas can be much larger than 8 Mb, they can be stored using byte stream apis into a new stream.

> What happens when a new revision of a schema is added? Do we create a new byte stream or write to the same? If we can always use byte streams and have to do it for really large schemas (which sounds unlikely to happen), shouldn't we always use byte streams to be consistent?

Only for very large schemas that cannot fit into a single event, we will store it externally and refer to it in our event. 

To store it externally, ideally we would want to store it in a file or object. But we dont want to have schema registry deal with different storage systems. Hence each new byte stream will only single "schema" and then be sealed.

**Comment by shiveshr** [comment] 2020-02-01 09:56
>>   The responsibility of stopping or upgrading older writers and readers lies with the application and the order of upgrade for downstream and upstream will depend on the compatibility strategy.

> I wonder whether this is a reasonable assumption to make. An application might not necessarily have control over all its writers. Think of sensors sprinkled across a large area, it might not be possible to update all of them. What does the application do in such cases?

Firstly, the upgrade of applications is out of scope for registry. 

A registry is a store for the schemas. Registry's function is limited to doing checks for evolution of schema. It can perform compatibility checks and allow evolution of schemas based on the compatibility setting chosen for a stream. 

Registry provides different compatibility settings for a stream and prescribes an upgrade strategy in conformance with that compatibility. 

If an application wants Backward compatibility, registry will check the new schema for backward compatibility. 
But it cannot force upgrades of applications. That has to be done out of band by application owners. 
If the choice of backward compatibility was chosen for the stream, if you dont upgrade the readers first, they will break because they will not be able to understand data written by upgraded writers. 
Thats all that registry is prescribing there.

**Comment by claudiofahey** [comment] 2020-02-01 16:10
> > We may also want to our serializer to support compression. 
> 
> I like this suggestion. Though i think we need to capture message encoding separate from compression type.
> `SchemaInfo` captures encoding format (schemaType) and its identifier (`version`) is referenced in the new header we propose to add to each serialized event.
> We can add `compression Type` into that header as well.
> So compression does not become part of schema information.
> 
> This also means we can have a deployment where some writers could be performing compression
> while others are not even for the same encoding (same schema).
> And we can provide support for that seamlessly.

We can think of the "schema version" in the event as a pointer to a record in the schema registry. The record should have all information needed to deserialize the event including the compression type and schema type. This minimizes the size of the event header. We way want to rename "schema version" to "serialization version" or something similar.

Different writers to the same stream could still choose their own compression type. When querying the schema registry for their "serialization version", they would get different values.
I still think should store the compression type in the schema registry.

Also, by including compression type in the schema registry, one could know ahead of time the compression types in use for the stream and eventType. Since some platforms may not have snappy compression, for instance, this could be a useful check during initialization.

**Comment by shiveshr** [comment] 2020-02-02 02:11
>We can think of the "schema version" in the event as a pointer to a record in the schema registry. The record should have all information needed to deserialize the event including the compression type and schema type. This minimizes the size of the event header. We way want to rename "schema version" to "serialization version" or something similar.

The problem is that is we would be including a lot of new "serialization versions" which have otherwise identical schemas but have different compressions. This could make evolution of schemas a bit cumbersome. We may need to handle how we manage these records differently. Take for example - Same schema existing as different records at different times just because of compression could make evolution of schema complicated. Take for example schema A and schema B and compression type C1 and compression type C2. 
Now if schema B is compatible with A in backward direction, it doesnt mean it would also be compatible in forward direction. But by including compression type into the record and making A(c1) and A(c2) as separate records, we could be in a situation where say we have following timeline --> A(c1) -> B(c1) -> A(c2). 
The registry would reject A(c2) unless we handle it in a more complicated fashion just to give A(c2) a new version while not performing any compatibility checks if its schema is already present. 

This would also make our api signatures to require support for compression coupled with schemas. Visualizing schemas in UI will need to tackle it and disambiguate. 

However, if compression type(s) were a property at stream level and stored separate from individual schema records, then we could have schema evolution like `A->B` and compressionTypes = {c1, c2} stored for the stream separately. 
With compression types not being a very large set, 1 byte should be more than enough for encoding it in the header. Yes its an additional one byte with every record, but we can optimize encoding the event header by making it a bit more complex. But the header is processed by registry client+serializer and its just about reading bits to know how to interpret the header.

> Also, by including compression type in the schema registry, one could know ahead of time the compression types in use for the stream and eventType. Since some platforms may not have snappy compression, for instance, this could be a useful check during initialization.

This can also be achieved by making a list of "compression types" per stream property in the registry as suggested above. So this will let anyone querying the registry know the "schemas" and "compression types" for a stream.

**Comment by claudiofahey** [comment] 2020-02-02 21:16
> The problem is that is we would be including a lot of new "serialization versions" which have otherwise identical schemas but have different compressions. This could make evolution of schemas a bit cumbersome. We may need to handle how we manage these records differently. Take for example - A and schema B and compression type C1 and compression type C2. Different "serialization records" can have same schema but different compression types added to the registry at different times.
Now if schema B is compatible with A in backward direction, it doesnt mean it would also be compatible in forward direction. But by including compression type into the record and making A(c1) and A(c2) as separate records, we could be in a situation where say we have following timeline --> A(c1) -> B(c1) -> A(c2).
The registry would reject A(c2) unless we handle it in a more complicated fashion just to give A(c2) a new version. For this we may need to identify its a known schema so no need to perform any compatibility checks but include it in the list of versions as a new record.

This is a good point. This problem can be solved by a level of indirection. First we insert the functional dependency (scope, stream, eventType, schemaType, versionNumber) -> (schemaData). Schema validation occurs here and does not depend on the compression. Then we insert the mapping (scope, stream, serializationId) -> (eventType, schemaType, version, compressionType). SerializationId can be the only field that is stored with each event.

I agree that this adds some complication to the schema registry including the UI. Adding an extra byte to an event to keep compression out of the schema registry is likely acceptable. However, another thing to think about is where we would want to store the key/value pairs or any future fields. The 2-layer approach explained above offers more flexibility without complicating schema validation.

**Comment by shiveshr** [comment] 2020-02-03 06:07
> I agree that this adds some complication to the schema registry including the UI. Adding an extra byte to an event to keep compression out of the schema registry is likely acceptable. However, another thing to think about is where we would want to store the key/value pairs or any future fields. The 2-layer approach explained above offers more flexibility without complicating schema validation.

The key/value corresponding to a schema is set of properties that are stored along with the schema in something called a schema record.
So in the pravega revisioned segment, we write schema records. These schema records contain the schema and other properties for the schema. 
This is where i see the key values or any other property also being added. 
 
I have considered a schema record to be immutable. And schema is the unique identifier in a schema record. So as an example if two different calls with same schema but different properties were made to the system to evolve the schema for the stream, if compatibility checks passed, the first request would be accepted while second is treated as an idempotent case. 
As an example: say i have schema S1
two requests to add schema were:
R1 = {S1, prop1}
R2 = {S1, prop2}

If R1 is processed first then S1 is added with prop1. R2 is treated as idempotent case and prop2 are never included in the system. 

The thought is that schema is the first class entity that is unique and evolution rules apply to. Any properties are supplementary information. 
They are kept immutable. 
If we want the ability to keep them mutable, then we need to separate out schema and the properties and follow two layer storage approach you suggested. 
Where we store schemas as an ordered set. And any adjoining properties in a second layer which is either mutable or allows for different records that share the same schema entity. 

I do not foresee any benefits from making the properties mutable or allowing multiple versions of schema records that share same underlying schema

**Comment by claudiofahey** [comment] 2020-02-03 17:12
It's great that you brought up the mutability of this data. In thinking about a UI, we may want fields containing personally identifiable information to be hidden in the UI. This would require flags or an access control list to be associated with a schema. Further, it makes perfect sense that an administrator may want to modify these flags and have that change apply immediately in the UI, without having to completely rewrite a stream. This would require mutating the non-schema part of the schema registry tables.

Of course, this adds even more complication. Here's my suggestion:

```
Schema table - immutable:
(scope, stream, eventType, schemaType, versionNumber) -> (schemaData)
Serialization table - immutable:
(scope, stream, serializationId) -> (eventType, schemaType, version, compressionType)
Properties table - mutable:
(scope, stream, serializationId) -> (key/value pairs such as ACLs)
```

**Comment by derekm** [comment] 2020-07-25 20:55
Most recent link: https://github.com/pravega/schema-registry/wiki/PDP-1:-Schema-Registry

**Closed** 2020-08-07 04:15 UTC
Labels: area/integration, kind/feature, priority/P1, status/in-progress
