### ISSUE TITLE
SegmentStore returns SegmentAlreadyExists for ReadTableEntry

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#3817] opened 2019-05-22 07:02 UTC
**Problem description**
In a run against 0.5 branch @deenav 's attempt to create stream failed because SegmentStore replied to controllers request to read Table Entry with SegmentAlreadyExists (an unexpected response). 

SmallScale stream's first create stream request is initiated at 13:09. 
This involves first checking if stream exists. Where we attempt a readTable on ` _system/_tables/longevity/smallScale/metadata.#.dfc825b6-7f7d-4142-adf1-0a0097d7d42c` and get an unexpected response saying Segment Already Exists. 

Controller logs: 
```
2019-05-17 13:09:18,726 308863 [epollEventLoopGroup-2-3] INFO  i.p.s.protocol.netty.CommandDecoder - => Reading command Segment already exists: _system/_tables/longevity/smallScale/metadata.#.dfc825b6-7f7d-4142-adf1-0a0097d7d42c on channel [id: 0xb52078a9, L:/172.24.16.7:53096 - R:172.24.16.15/172.24.16.15:12345]
2019-05-17 13:09:18,727 308864 [epollEventLoopGroup-2-3] WARN  i.p.client.netty.impl.FlowHandler - ReplyProcessor.process failed for reply Segment already exists: _system/_tables/longevity/smallScale/metadata.#.dfc825b6-7f7d-4142-adf1-0a0097d7d42c due to Segment already exists: _system/_tables/longevity/smallScale/metadata.#.dfc825b6-7f7d-4142-adf1-0a0097d7d42c
2019-05-17 13:09:18,727 308864 [epollEventLoopGroup-2-3] ERROR i.p.controller.server.SegmentHelper - [requestId=307] readTable _system/_tables/longevity/smallScale/metadata.#.dfc825b6-7f7d-4142-adf1-0a0097d7d42c failed
java.lang.IllegalStateException: Segment already exists: _system/_tables/longevity/smallScale/metadata.#.dfc825b6-7f7d-4142-adf1-0a0097d7d42c
        at io.pravega.shared.protocol.netty.FailingReplyProcessor.segmentAlreadyExists(FailingReplyProcessor.java:75)
```

Corresponding segmentStore logs:
```
2019-05-17 13:09:18,587 245097 [epollEventLoopGroup-11-1] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=306] Reading from table WireCommands.ReadTable(type=READ_TABLE, requestId=306, segment=_system/_tables/longevity/smallScale/metadata.#.dfc825b6-7f7d-4142-adf1-0a0097d7d42c, delegationToken=, keys=[WireCommands.TableKey(data=UnpooledHeapByteBuf(ridx: 0, widx: 12, cap: 12/12), keyVersion=-9223372036854775808)]).
2019-05-17 13:09:18,609 245119 [storage-io-173] ERROR i.p.s.s.h.h.PravegaRequestProcessor - [requestId=306] Error (Segment = '_system/_tables/longevity/smallScale/metadata.#.dfc825b6-7f7d-4142-adf1-0a0097d7d42c', Operation = 'readTable')
java.nio.file.FileSystemException: /mnt/tier2/_system/containers/metadata_6$attributes.index$header: I/O error
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.createFile(Files.java:632)
        at io.pravega.storage.filesystem.FileSystemStorage.doCreate(FileSystemStorage.java:284)
        at io.pravega.storage.filesystem.FileSystemStorage.lambda$create$5(FileSystemStorage.java:150)
        at io.pravega.storage.filesystem.FileSystemStorage.execute(FileSystemStorage.java:405)
        at io.pravega.storage.filesystem.FileSystemStorage.create(FileSystemStorage.java:150)
        at io.pravega.segmentstore.storage.rolling.RollingStorage.create(RollingStorage.java:257)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$create$1(AsyncStorageWrapper.java:88)
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)




...
2019-05-17 13:09:18,726 245236 [storage-io-175] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=307] Segment '_system/_tables/longevity/smallScale/metadata.#.dfc825b6-7f7d-4142-adf1-0a0097d7d42c' already exists and cannot perform operation 'readTable'.
```

SegmentStore-1 seems to be in some bad state. 
It has NPE for segmentAggregator which keeps coming and is logged over and over. 
And it also keeps throwing SegmentAlreadyExists exceptions. 

```
2019-05-17 13:09:16,946 243456 [ForkJoinPool.commonPool-worker-1] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[8]: Iteration[219].Error.
java.lang.NullPointerException: null
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.write(AsyncStorageWrapper.java:93)
        at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$flushPendingAppends$17(SegmentAggregator.java:775)
```

So this request failed with above error which resulted in segmentAlreadyExists response received on controller which caused stream creation to fail. 

This whole experiment is repeated two more times, trying to create the stream smallScale twice. we get into the same problem. 

**Problem location**

**Suggestions for an improvement**

**Comment by andreipaduroiu** [comment] 2019-05-22 16:07
Duplicate of #3784.

The NullPtr is because you are using an outdated image which doesn't have the latest fixes, one of which is for that one.

**Closed by andreipaduroiu** 2019-05-22 16:07 UTC
Labels: area/server, area/tables, kind/bug, priority/P1, version/0.5.0
